// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-axios";
import type {
  PaymentsServiceUpdatePaymentStatusData,
  PaymentsServiceUpdatePaymentStatusError,
  PaymentsServiceUpdatePaymentStatusResponse,
  PaymentsServiceListAllPaymentsData,
  PaymentsServiceListAllPaymentsError,
  PaymentsServiceListAllPaymentsResponse,
  PaymentsServiceListPaymentsData,
  PaymentsServiceListPaymentsError,
  PaymentsServiceListPaymentsResponse,
  PaymentsServiceInitiatePaymentsData,
  PaymentsServiceInitiatePaymentsError,
  PaymentsServiceInitiatePaymentsResponse,
  PaymentsServiceGetPaymentByIdData,
  PaymentsServiceGetPaymentByIdError,
  PaymentsServiceGetPaymentByIdResponse,
  PaymentsServicePawaPayWebhookData,
  PaymentsServicePawaPayWebhookError,
  PaymentsServicePawaPayWebhookResponse,
  PaymentsServiceStripeWebhookData,
  PaymentsServiceStripeWebhookError,
  PaymentsServiceStripeWebhookResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * UpdatePaymentStatus allows admins to manually update payment status
 * Used for manual intervention or payment reconciliation
 */
export const paymentsServiceUpdatePaymentStatus = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    PaymentsServiceUpdatePaymentStatusData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).patch<
    PaymentsServiceUpdatePaymentStatusResponse,
    PaymentsServiceUpdatePaymentStatusError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/user/{userId}/payments/{paymentId}/status",
  });
};

/**
 * ListAllPayments retrieves all payment records with optional filtering
 * Admin endpoint for viewing all payments across users
 */
export const paymentsServiceListAllPayments = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    PaymentsServiceListAllPaymentsData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    PaymentsServiceListAllPaymentsResponse,
    PaymentsServiceListAllPaymentsError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/users/{userId}/payments",
  });
};

/**
 * ListPayments retrieves all payments for a specific user
 * Client endpoint with pagination and status filtering
 */
export const paymentsServiceListPayments = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<PaymentsServiceListPaymentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PaymentsServiceListPaymentsResponse,
    PaymentsServiceListPaymentsError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/user/{userId}/payments",
  });
};

/**
 * InitiatePayments creates a new payment and returns checkout instructions
 * Starts the payment flow with Stripe or PawaPay
 */
export const paymentsServiceInitiatePayments = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    PaymentsServiceInitiatePaymentsData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    PaymentsServiceInitiatePaymentsResponse,
    PaymentsServiceInitiatePaymentsError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/user/{userId}/payments/initiate-pawapay-payment",
  });
};

/**
 * GetPaymentByID retrieves a single payment record by ID
 * Client endpoint for viewing individual payment details
 */
export const paymentsServiceGetPaymentById = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<PaymentsServiceGetPaymentByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PaymentsServiceGetPaymentByIdResponse,
    PaymentsServiceGetPaymentByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/user/{userId}/payments/{paymentId}",
  });
};

/**
 * PawaPay webhook endpoint
 * Used by PawaPay to notify deposit status changes
 */
export const paymentsServicePawaPayWebhook = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<PaymentsServicePawaPayWebhookData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PaymentsServicePawaPayWebhookResponse,
    PaymentsServicePawaPayWebhookError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/public/webhook/pawapay/payments",
  });
};

/**
 * Stripe webhook endpoint
 * Used by Stripe to notify payment status changes
 */
export const paymentsServiceStripeWebhook = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<PaymentsServiceStripeWebhookData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PaymentsServiceStripeWebhookResponse,
    PaymentsServiceStripeWebhookError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/public/webhook/stripe/payments",
  });
};
