// This file is auto-generated by @hey-api/openapi-ts

export type PayerAddress = {
  value?: string;
};

export type PaymentsServiceInitiatePaymentsBody = {
  subscriptionId?: string;
  paymentMethod?: v2PaymentMethod;
  /**
   * payer_phone_number is required when payment method is PAWAPAY.
   */
  payerPhoneNumber?: string;
  /**
   * email and callback_url are required when payment method is STRIPE.
   */
  email?: string;
  callbackUrl?: string;
};

export type PaymentsServiceUpdatePaymentStatusBody = {
  status?: v2PaymentStatus;
};

export type protobufAny = {
  [key: string]: unknown;
};

export type rpcStatus = {
  code?: number;
  message?: string;
  details?: Array<protobufAny>;
};

export type v2CorrespondentIds = {
  mtnInit?: string;
  mtnFinal?: string;
};

export type v2FailureReason = {
  failureCode?: string;
  failureMessage?: string;
};

export type v2GetPaymentStatsResponse = {
  payment?: v2Payment;
};

export type v2InitiatePaymentsResponse = {
  paymentId?: string;
  instructions?: v2PaymentInstructions;
  checkoutUrl?: string;
};

export type v2ListAllPaymentsResponse = {
  payments?: Array<v2Payment>;
  totalCount?: string;
  page?: string;
  pageSize?: string;
};

export type v2ListPaymentsResponse = {
  payments?: Array<v2Payment>;
  totalCount?: string;
  page?: string;
  pageSize?: string;
};

export type v2Metadata = {
  orderId?: string;
  customerId?: string;
};

export type v2PawaPayWebhookRequest = {
  depositId?: string;
  status?: string;
  requestedAmount?: string;
  currency?: string;
  country?: string;
  correspondent?: string;
  payer?: v2Payer;
  customerTimestamp?: string;
  statementDescription?: string;
  created?: string;
  depositedAmount?: string;
  respondedByPayer?: string;
  correspondentIds?: v2CorrespondentIds;
  suspiciousActivityReport?: Array<v2SuspiciousActivityReport>;
  failureReason?: v2FailureReason;
  metadata?: v2Metadata;
};

export type v2PawaPayWebhookResponse = {
  success?: boolean;
  message?: string;
};

export type v2Payer = {
  type?: string;
  address?: PayerAddress;
};

export type v2Payment = {
  paymentId?: string;
  userId?: string;
  subscriptionId?: string;
  amountXaf?: string;
  amountUsd?: string;
  paymentMethod?: v2PaymentMethod;
  status?: v2PaymentStatus;
  failureReason?: string;
  payerPhoneNumber?: string;
  callbackUrl?: string;
  email?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type v2PaymentInstructions = {
  en?: string;
  fr?: string;
};

export type v2PaymentMethod =
  | "PAYMENT_METHOD_UNSPECIFIED"
  | "PAYMENT_METHOD_STRIPE"
  | "PAYMENT_METHOD_PAWAPAY";

export type v2PaymentStatus =
  | "PAYMENT_STATUS_UNSPECIFIED"
  | "PAYMENT_STATUS_PENDING"
  | "PAYMENT_STATUS_COMPLETED"
  | "PAYMENT_STATUS_FAILED"
  | "PAYMENT_STATUS_REFUNDED"
  | "PAYMENT_STATUS_CANCELLED";

export type v2StripeWebhookRequest = {
  id?: string;
  type?: string;
  created?: string;
  object?: string;
};

export type v2StripeWebhookResponse = {
  success?: boolean;
  message?: string;
};

export type v2SuspiciousActivityReport = {
  activityType?: string;
  comment?: string;
};

export type v2UpdatePaymentStatusResponse = {
  payment?: v2Payment;
};

export type PaymentsServiceUpdatePaymentStatusData = {
  body: PaymentsServiceUpdatePaymentStatusBody;
  path: {
    /**
     * Payment to update
     */
    paymentId: string;
    /**
     * User associated with the payment
     */
    userId: string;
  };
};

export type PaymentsServiceUpdatePaymentStatusResponse =
  v2UpdatePaymentStatusResponse;

export type PaymentsServiceUpdatePaymentStatusError = rpcStatus;

export type PaymentsServiceListAllPaymentsData = {
  path: {
    /**
     * Optional user filter
     */
    userId: string;
  };
  query?: {
    /**
     * Page number (1-indexed)
     */
    page?: string;
    /**
     * Number of records per page
     */
    pageSize?: string;
    /**
     * Optional payment method filter
     */
    paymentMethod?:
      | "PAYMENT_METHOD_UNSPECIFIED"
      | "PAYMENT_METHOD_STRIPE"
      | "PAYMENT_METHOD_PAWAPAY";
    /**
     * Optional status filter
     */
    status?:
      | "PAYMENT_STATUS_UNSPECIFIED"
      | "PAYMENT_STATUS_PENDING"
      | "PAYMENT_STATUS_COMPLETED"
      | "PAYMENT_STATUS_FAILED"
      | "PAYMENT_STATUS_REFUNDED"
      | "PAYMENT_STATUS_CANCELLED";
  };
};

export type PaymentsServiceListAllPaymentsResponse = v2ListAllPaymentsResponse;

export type PaymentsServiceListAllPaymentsError = rpcStatus;

export type PaymentsServiceListPaymentsData = {
  path: {
    /**
     * User whose payments to retrieve
     */
    userId: string;
  };
  query?: {
    /**
     * Page number (1-indexed)
     */
    page?: string;
    /**
     * Number of records per page
     */
    pageSize?: string;
    /**
     * Optional status filter
     */
    status?:
      | "PAYMENT_STATUS_UNSPECIFIED"
      | "PAYMENT_STATUS_PENDING"
      | "PAYMENT_STATUS_COMPLETED"
      | "PAYMENT_STATUS_FAILED"
      | "PAYMENT_STATUS_REFUNDED"
      | "PAYMENT_STATUS_CANCELLED";
  };
};

export type PaymentsServiceListPaymentsResponse = v2ListPaymentsResponse;

export type PaymentsServiceListPaymentsError = rpcStatus;

export type PaymentsServiceInitiatePaymentsData = {
  body: PaymentsServiceInitiatePaymentsBody;
  path: {
    userId: string;
  };
};

export type PaymentsServiceInitiatePaymentsResponse =
  v2InitiatePaymentsResponse;

export type PaymentsServiceInitiatePaymentsError = rpcStatus;

export type PaymentsServiceGetPaymentByIdData = {
  path: {
    /**
     * payment id for the payment to retrieve
     */
    paymentId: string;
    /**
     * 'user_id' for the user that owns that payment
     */
    userId: string;
  };
};

export type PaymentsServiceGetPaymentByIdResponse = v2GetPaymentStatsResponse;

export type PaymentsServiceGetPaymentByIdError = rpcStatus;

export type PaymentsServicePawaPayWebhookData = {
  body: v2PawaPayWebhookRequest;
};

export type PaymentsServicePawaPayWebhookResponse = v2PawaPayWebhookResponse;

export type PaymentsServicePawaPayWebhookError = rpcStatus;

export type PaymentsServiceStripeWebhookData = {
  body: v2StripeWebhookRequest;
};

export type PaymentsServiceStripeWebhookResponse = v2StripeWebhookResponse;

export type PaymentsServiceStripeWebhookError = rpcStatus;
