// This file is auto-generated by @hey-api/openapi-ts

import type { OptionsLegacyParser } from "@hey-api/client-axios";
import { queryOptions, type UseMutationOptions } from "@tanstack/react-query";
import type {
  UserServiceGetOtpByRequestIdData,
  UserServiceCancelAdminInvitationData,
  UserServiceCancelAdminInvitationError,
  UserServiceCancelAdminInvitationResponse,
  UserServiceInviteAdminData,
  UserServiceInviteAdminError,
  UserServiceInviteAdminResponse,
  UserServiceResendAdminInvitationData,
  UserServiceResendAdminInvitationError,
  UserServiceResendAdminInvitationResponse,
  UserServiceGenerateNewFiresbaseCustomTokenData,
  UserServiceGenerateNewFiresbaseCustomTokenError,
  UserServiceGenerateNewFiresbaseCustomTokenResponse,
  UserServiceCompleteProfileData,
  UserServiceCompleteProfileError,
  UserServiceCompleteProfileResponse,
  UserServiceActivateAdminUsersAccountData,
  UserServiceActivateAdminUsersAccountError,
  UserServiceActivateAdminUsersAccountResponse,
  UserServiceAuthenticateData,
  UserServiceAuthenticateError,
  UserServiceAuthenticateResponse,
  UserServiceRefreshAccessTokenData,
  UserServiceRefreshAccessTokenError,
  UserServiceRefreshAccessTokenResponse,
  UserServiceSendSignupEmailVerificationLinkData,
  UserServiceSendSignupEmailVerificationLinkError,
  UserServiceSendSignupEmailVerificationLinkResponse,
  UserServiceSendSignupOtpData,
  UserServiceSendSignupOtpError,
  UserServiceSendSignupOtpResponse,
  UserServiceSignupData,
  UserServiceSignupError,
  UserServiceSignupResponse,
  UserServiceVerifyOtpData,
  UserServiceVerifyOtpError,
  UserServiceVerifyOtpResponse,
  UserServiceVerifyEmailData,
  UserServiceUpdateUserData,
  UserServiceUpdateUserError,
  UserServiceUpdateUserResponse,
} from "../types.gen";
import {
  client,
  userServiceGetOtpByRequestId,
  userServiceCancelAdminInvitation,
  userServiceInviteAdmin,
  userServiceResendAdminInvitation,
  userServiceGenerateNewFiresbaseCustomToken,
  userServiceCompleteProfile,
  userServiceActivateAdminUsersAccount,
  userServiceAuthenticate,
  userServiceRefreshAccessToken,
  userServiceSendSignupEmailVerificationLink,
  userServiceSendSignupOtp,
  userServiceSignup,
  userServiceVerifyOtp,
  userServiceVerifyEmail,
  userServiceUpdateUser,
} from "../sdk.gen";
import type { AxiosError } from "axios";

type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};

export const userServiceGetOtpByRequestIdQueryKey = (
  options: OptionsLegacyParser<UserServiceGetOtpByRequestIdData>,
) => [createQueryKey("userServiceGetOtpByRequestId", options)];

export const userServiceGetOtpByRequestIdOptions = (
  options: OptionsLegacyParser<UserServiceGetOtpByRequestIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userServiceGetOtpByRequestId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: userServiceGetOtpByRequestIdQueryKey(options),
  });
};

export const userServiceCancelAdminInvitationQueryKey = (
  options: OptionsLegacyParser<UserServiceCancelAdminInvitationData>,
) => [createQueryKey("userServiceCancelAdminInvitation", options)];

export const userServiceCancelAdminInvitationOptions = (
  options: OptionsLegacyParser<UserServiceCancelAdminInvitationData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userServiceCancelAdminInvitation({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: userServiceCancelAdminInvitationQueryKey(options),
  });
};

export const userServiceCancelAdminInvitationMutation = (
  options?: Partial<OptionsLegacyParser<UserServiceCancelAdminInvitationData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UserServiceCancelAdminInvitationResponse,
    AxiosError<UserServiceCancelAdminInvitationError>,
    OptionsLegacyParser<UserServiceCancelAdminInvitationData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await userServiceCancelAdminInvitation({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const userServiceInviteAdminQueryKey = (
  options: OptionsLegacyParser<UserServiceInviteAdminData>,
) => [createQueryKey("userServiceInviteAdmin", options)];

export const userServiceInviteAdminOptions = (
  options: OptionsLegacyParser<UserServiceInviteAdminData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userServiceInviteAdmin({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: userServiceInviteAdminQueryKey(options),
  });
};

export const userServiceInviteAdminMutation = (
  options?: Partial<OptionsLegacyParser<UserServiceInviteAdminData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UserServiceInviteAdminResponse,
    AxiosError<UserServiceInviteAdminError>,
    OptionsLegacyParser<UserServiceInviteAdminData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await userServiceInviteAdmin({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const userServiceResendAdminInvitationMutation = (
  options?: Partial<OptionsLegacyParser<UserServiceResendAdminInvitationData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UserServiceResendAdminInvitationResponse,
    AxiosError<UserServiceResendAdminInvitationError>,
    OptionsLegacyParser<UserServiceResendAdminInvitationData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await userServiceResendAdminInvitation({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const userServiceGenerateNewFiresbaseCustomTokenQueryKey = (
  options: OptionsLegacyParser<UserServiceGenerateNewFiresbaseCustomTokenData>,
) => [createQueryKey("userServiceGenerateNewFiresbaseCustomToken", options)];

export const userServiceGenerateNewFiresbaseCustomTokenOptions = (
  options: OptionsLegacyParser<UserServiceGenerateNewFiresbaseCustomTokenData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userServiceGenerateNewFiresbaseCustomToken({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: userServiceGenerateNewFiresbaseCustomTokenQueryKey(options),
  });
};

export const userServiceGenerateNewFiresbaseCustomTokenMutation = (
  options?: Partial<
    OptionsLegacyParser<UserServiceGenerateNewFiresbaseCustomTokenData>
  >,
) => {
  const mutationOptions: UseMutationOptions<
    UserServiceGenerateNewFiresbaseCustomTokenResponse,
    AxiosError<UserServiceGenerateNewFiresbaseCustomTokenError>,
    OptionsLegacyParser<UserServiceGenerateNewFiresbaseCustomTokenData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await userServiceGenerateNewFiresbaseCustomToken({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const userServiceCompleteProfileMutation = (
  options?: Partial<OptionsLegacyParser<UserServiceCompleteProfileData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UserServiceCompleteProfileResponse,
    AxiosError<UserServiceCompleteProfileError>,
    OptionsLegacyParser<UserServiceCompleteProfileData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await userServiceCompleteProfile({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const userServiceActivateAdminUsersAccountQueryKey = (
  options: OptionsLegacyParser<UserServiceActivateAdminUsersAccountData>,
) => [createQueryKey("userServiceActivateAdminUsersAccount", options)];

export const userServiceActivateAdminUsersAccountOptions = (
  options: OptionsLegacyParser<UserServiceActivateAdminUsersAccountData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userServiceActivateAdminUsersAccount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: userServiceActivateAdminUsersAccountQueryKey(options),
  });
};

export const userServiceActivateAdminUsersAccountMutation = (
  options?: Partial<
    OptionsLegacyParser<UserServiceActivateAdminUsersAccountData>
  >,
) => {
  const mutationOptions: UseMutationOptions<
    UserServiceActivateAdminUsersAccountResponse,
    AxiosError<UserServiceActivateAdminUsersAccountError>,
    OptionsLegacyParser<UserServiceActivateAdminUsersAccountData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await userServiceActivateAdminUsersAccount({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const userServiceAuthenticateQueryKey = (
  options: OptionsLegacyParser<UserServiceAuthenticateData>,
) => [createQueryKey("userServiceAuthenticate", options)];

export const userServiceAuthenticateOptions = (
  options: OptionsLegacyParser<UserServiceAuthenticateData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userServiceAuthenticate({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: userServiceAuthenticateQueryKey(options),
  });
};

export const userServiceAuthenticateMutation = (
  options?: Partial<OptionsLegacyParser<UserServiceAuthenticateData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UserServiceAuthenticateResponse,
    AxiosError<UserServiceAuthenticateError>,
    OptionsLegacyParser<UserServiceAuthenticateData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await userServiceAuthenticate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const userServiceRefreshAccessTokenQueryKey = (
  options: OptionsLegacyParser<UserServiceRefreshAccessTokenData>,
) => [createQueryKey("userServiceRefreshAccessToken", options)];

export const userServiceRefreshAccessTokenOptions = (
  options: OptionsLegacyParser<UserServiceRefreshAccessTokenData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userServiceRefreshAccessToken({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: userServiceRefreshAccessTokenQueryKey(options),
  });
};

export const userServiceRefreshAccessTokenMutation = (
  options?: Partial<OptionsLegacyParser<UserServiceRefreshAccessTokenData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UserServiceRefreshAccessTokenResponse,
    AxiosError<UserServiceRefreshAccessTokenError>,
    OptionsLegacyParser<UserServiceRefreshAccessTokenData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await userServiceRefreshAccessToken({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const userServiceSendSignupEmailVerificationLinkQueryKey = (
  options: OptionsLegacyParser<UserServiceSendSignupEmailVerificationLinkData>,
) => [createQueryKey("userServiceSendSignupEmailVerificationLink", options)];

export const userServiceSendSignupEmailVerificationLinkOptions = (
  options: OptionsLegacyParser<UserServiceSendSignupEmailVerificationLinkData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userServiceSendSignupEmailVerificationLink({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: userServiceSendSignupEmailVerificationLinkQueryKey(options),
  });
};

export const userServiceSendSignupEmailVerificationLinkMutation = (
  options?: Partial<
    OptionsLegacyParser<UserServiceSendSignupEmailVerificationLinkData>
  >,
) => {
  const mutationOptions: UseMutationOptions<
    UserServiceSendSignupEmailVerificationLinkResponse,
    AxiosError<UserServiceSendSignupEmailVerificationLinkError>,
    OptionsLegacyParser<UserServiceSendSignupEmailVerificationLinkData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await userServiceSendSignupEmailVerificationLink({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const userServiceSendSignupOtpQueryKey = (
  options: OptionsLegacyParser<UserServiceSendSignupOtpData>,
) => [createQueryKey("userServiceSendSignupOtp", options)];

export const userServiceSendSignupOtpOptions = (
  options: OptionsLegacyParser<UserServiceSendSignupOtpData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userServiceSendSignupOtp({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: userServiceSendSignupOtpQueryKey(options),
  });
};

export const userServiceSendSignupOtpMutation = (
  options?: Partial<OptionsLegacyParser<UserServiceSendSignupOtpData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UserServiceSendSignupOtpResponse,
    AxiosError<UserServiceSendSignupOtpError>,
    OptionsLegacyParser<UserServiceSendSignupOtpData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await userServiceSendSignupOtp({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const userServiceSignupQueryKey = (
  options: OptionsLegacyParser<UserServiceSignupData>,
) => [createQueryKey("userServiceSignup", options)];

export const userServiceSignupOptions = (
  options: OptionsLegacyParser<UserServiceSignupData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userServiceSignup({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: userServiceSignupQueryKey(options),
  });
};

export const userServiceSignupMutation = (
  options?: Partial<OptionsLegacyParser<UserServiceSignupData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UserServiceSignupResponse,
    AxiosError<UserServiceSignupError>,
    OptionsLegacyParser<UserServiceSignupData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await userServiceSignup({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const userServiceVerifyOtpQueryKey = (
  options: OptionsLegacyParser<UserServiceVerifyOtpData>,
) => [createQueryKey("userServiceVerifyOtp", options)];

export const userServiceVerifyOtpOptions = (
  options: OptionsLegacyParser<UserServiceVerifyOtpData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userServiceVerifyOtp({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: userServiceVerifyOtpQueryKey(options),
  });
};

export const userServiceVerifyOtpMutation = (
  options?: Partial<OptionsLegacyParser<UserServiceVerifyOtpData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UserServiceVerifyOtpResponse,
    AxiosError<UserServiceVerifyOtpError>,
    OptionsLegacyParser<UserServiceVerifyOtpData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await userServiceVerifyOtp({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const userServiceVerifyEmailQueryKey = (
  options: OptionsLegacyParser<UserServiceVerifyEmailData>,
) => [createQueryKey("userServiceVerifyEmail", options)];

export const userServiceVerifyEmailOptions = (
  options: OptionsLegacyParser<UserServiceVerifyEmailData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userServiceVerifyEmail({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: userServiceVerifyEmailQueryKey(options),
  });
};

export const userServiceUpdateUserMutation = (
  options?: Partial<OptionsLegacyParser<UserServiceUpdateUserData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UserServiceUpdateUserResponse,
    AxiosError<UserServiceUpdateUserError>,
    OptionsLegacyParser<UserServiceUpdateUserData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await userServiceUpdateUser({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
