// This file is auto-generated by @hey-api/openapi-ts

import type { OptionsLegacyParser } from "@hey-api/client-axios";
import {
  type UseMutationOptions,
  queryOptions,
  infiniteQueryOptions,
  type InfiniteData,
} from "@tanstack/react-query";
import type {
  SubscriptionsDeleteKycDocumentData,
  SubscriptionsDeleteKycDocumentError,
  SubscriptionsDeleteKycDocumentResponse,
  SubscriptionsListKycDocumentsData,
  SubscriptionsListKycDocumentsError,
  SubscriptionsListKycDocumentsResponse,
  SubscriptionsGetKycDocumentData,
  SubscriptionsUpdateKycDocumentStatusData,
  SubscriptionsUpdateKycDocumentStatusError,
  SubscriptionsUpdateKycDocumentStatusResponse,
  SubscriptionsAdminCreatePlanData,
  SubscriptionsAdminCreatePlanError,
  SubscriptionsAdminCreatePlanResponse,
  SubscriptionsAdminUpdatePlanData,
  SubscriptionsAdminUpdatePlanError,
  SubscriptionsAdminUpdatePlanResponse,
  SubscriptionsAdminListPlansData,
  SubscriptionsAdminListPlansError,
  SubscriptionsAdminListPlansResponse,
  SubscriptionsAdminDeletePlanData,
  SubscriptionsAdminDeletePlanError,
  SubscriptionsAdminDeletePlanResponse,
  SubscriptionsAdminActivateUserSubscriptionData,
  SubscriptionsAdminActivateUserSubscriptionError,
  SubscriptionsAdminActivateUserSubscriptionResponse,
  SubscriptionsAdminSuspendUserSubscriptionData,
  SubscriptionsAdminSuspendUserSubscriptionError,
  SubscriptionsAdminSuspendUserSubscriptionResponse,
  SubscriptionsAdminVerifyUserSubscriptionData,
  SubscriptionsAdminVerifyUserSubscriptionError,
  SubscriptionsAdminVerifyUserSubscriptionResponse,
  SubscriptionsSaveKycDocumentsData,
  SubscriptionsSaveKycDocumentsError,
  SubscriptionsSaveKycDocumentsResponse,
  SubscriptionsUpdateUserSubscriptionData,
  SubscriptionsUpdateUserSubscriptionError,
  SubscriptionsUpdateUserSubscriptionResponse,
  SubscriptionsListPlansData,
  SubscriptionsListPlansError,
  SubscriptionsListPlansResponse,
  SubscriptionsGetPlanData,
  SubscriptionsListUserSubscriptionsData,
  SubscriptionsListUserSubscriptionsError,
  SubscriptionsListUserSubscriptionsResponse,
  SubscriptionsCreateUserSubscriptionData,
  SubscriptionsCreateUserSubscriptionError,
  SubscriptionsCreateUserSubscriptionResponse,
  SubscriptionsGetActiveUserSubscriptionData,
  SubscriptionsSendOrganizationPlanIntentToAdminData,
  SubscriptionsSendOrganizationPlanIntentToAdminError,
  SubscriptionsSendOrganizationPlanIntentToAdminResponse,
  SubscriptionsGetUserSubscriptionData,
  SubscriptionsCancelUserSubscriptionData,
  SubscriptionsCancelUserSubscriptionError,
  SubscriptionsCancelUserSubscriptionResponse,
} from "../types.gen";
import type { AxiosError } from "axios";
import {
  subscriptionsDeleteKycDocument,
  client,
  subscriptionsListKycDocuments,
  subscriptionsGetKycDocument,
  subscriptionsUpdateKycDocumentStatus,
  subscriptionsAdminCreatePlan,
  subscriptionsAdminUpdatePlan,
  subscriptionsAdminListPlans,
  subscriptionsAdminDeletePlan,
  subscriptionsAdminActivateUserSubscription,
  subscriptionsAdminSuspendUserSubscription,
  subscriptionsAdminVerifyUserSubscription,
  subscriptionsSaveKycDocuments,
  subscriptionsUpdateUserSubscription,
  subscriptionsListPlans,
  subscriptionsGetPlan,
  subscriptionsListUserSubscriptions,
  subscriptionsCreateUserSubscription,
  subscriptionsGetActiveUserSubscription,
  subscriptionsSendOrganizationPlanIntentToAdmin,
  subscriptionsGetUserSubscription,
  subscriptionsCancelUserSubscription,
} from "../sdk.gen";

export const subscriptionsDeleteKycDocumentMutation = (
  options?: Partial<OptionsLegacyParser<SubscriptionsDeleteKycDocumentData>>,
) => {
  const mutationOptions: UseMutationOptions<
    SubscriptionsDeleteKycDocumentResponse,
    AxiosError<SubscriptionsDeleteKycDocumentError>,
    OptionsLegacyParser<SubscriptionsDeleteKycDocumentData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await subscriptionsDeleteKycDocument({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};

export const subscriptionsListKycDocumentsQueryKey = (
  options: OptionsLegacyParser<SubscriptionsListKycDocumentsData>,
) => [createQueryKey("subscriptionsListKycDocuments", options)];

export const subscriptionsListKycDocumentsOptions = (
  options: OptionsLegacyParser<SubscriptionsListKycDocumentsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionsListKycDocuments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: subscriptionsListKycDocumentsQueryKey(options),
  });
};

const createInfiniteParams = <
  K extends Pick<
    QueryKey<OptionsLegacyParser>[0],
    "body" | "headers" | "path" | "query"
  >,
>(
  queryKey: QueryKey<OptionsLegacyParser>,
  page: K,
) => {
  const params = queryKey[0];
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...queryKey[0].path,
      ...page.path,
    };
  }
  if (page.query) {
    params.query = {
      ...queryKey[0].query,
      ...page.query,
    };
  }
  return params as unknown as typeof page;
};

export const subscriptionsListKycDocumentsInfiniteQueryKey = (
  options: OptionsLegacyParser<SubscriptionsListKycDocumentsData>,
): QueryKey<OptionsLegacyParser<SubscriptionsListKycDocumentsData>> => [
  createQueryKey("subscriptionsListKycDocuments", options, true),
];

export const subscriptionsListKycDocumentsInfiniteOptions = (
  options: OptionsLegacyParser<SubscriptionsListKycDocumentsData>,
) => {
  return infiniteQueryOptions<
    SubscriptionsListKycDocumentsResponse,
    AxiosError<SubscriptionsListKycDocumentsError>,
    InfiniteData<SubscriptionsListKycDocumentsResponse>,
    QueryKey<OptionsLegacyParser<SubscriptionsListKycDocumentsData>>,
    | number
    | Pick<
        QueryKey<OptionsLegacyParser<SubscriptionsListKycDocumentsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<OptionsLegacyParser<SubscriptionsListKycDocumentsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await subscriptionsListKycDocuments({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: subscriptionsListKycDocumentsInfiniteQueryKey(options),
    },
  );
};

export const subscriptionsGetKycDocumentQueryKey = (
  options: OptionsLegacyParser<SubscriptionsGetKycDocumentData>,
) => [createQueryKey("subscriptionsGetKycDocument", options)];

export const subscriptionsGetKycDocumentOptions = (
  options: OptionsLegacyParser<SubscriptionsGetKycDocumentData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionsGetKycDocument({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: subscriptionsGetKycDocumentQueryKey(options),
  });
};

export const subscriptionsUpdateKycDocumentStatusMutation = (
  options?: Partial<
    OptionsLegacyParser<SubscriptionsUpdateKycDocumentStatusData>
  >,
) => {
  const mutationOptions: UseMutationOptions<
    SubscriptionsUpdateKycDocumentStatusResponse,
    AxiosError<SubscriptionsUpdateKycDocumentStatusError>,
    OptionsLegacyParser<SubscriptionsUpdateKycDocumentStatusData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await subscriptionsUpdateKycDocumentStatus({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const subscriptionsAdminCreatePlanQueryKey = (
  options: OptionsLegacyParser<SubscriptionsAdminCreatePlanData>,
) => [createQueryKey("subscriptionsAdminCreatePlan", options)];

export const subscriptionsAdminCreatePlanOptions = (
  options: OptionsLegacyParser<SubscriptionsAdminCreatePlanData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionsAdminCreatePlan({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: subscriptionsAdminCreatePlanQueryKey(options),
  });
};

export const subscriptionsAdminCreatePlanMutation = (
  options?: Partial<OptionsLegacyParser<SubscriptionsAdminCreatePlanData>>,
) => {
  const mutationOptions: UseMutationOptions<
    SubscriptionsAdminCreatePlanResponse,
    AxiosError<SubscriptionsAdminCreatePlanError>,
    OptionsLegacyParser<SubscriptionsAdminCreatePlanData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await subscriptionsAdminCreatePlan({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const subscriptionsAdminUpdatePlanMutation = (
  options?: Partial<OptionsLegacyParser<SubscriptionsAdminUpdatePlanData>>,
) => {
  const mutationOptions: UseMutationOptions<
    SubscriptionsAdminUpdatePlanResponse,
    AxiosError<SubscriptionsAdminUpdatePlanError>,
    OptionsLegacyParser<SubscriptionsAdminUpdatePlanData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await subscriptionsAdminUpdatePlan({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const subscriptionsAdminListPlansQueryKey = (
  options: OptionsLegacyParser<SubscriptionsAdminListPlansData>,
) => [createQueryKey("subscriptionsAdminListPlans", options)];

export const subscriptionsAdminListPlansOptions = (
  options: OptionsLegacyParser<SubscriptionsAdminListPlansData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionsAdminListPlans({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: subscriptionsAdminListPlansQueryKey(options),
  });
};

export const subscriptionsAdminListPlansInfiniteQueryKey = (
  options: OptionsLegacyParser<SubscriptionsAdminListPlansData>,
): QueryKey<OptionsLegacyParser<SubscriptionsAdminListPlansData>> => [
  createQueryKey("subscriptionsAdminListPlans", options, true),
];

export const subscriptionsAdminListPlansInfiniteOptions = (
  options: OptionsLegacyParser<SubscriptionsAdminListPlansData>,
) => {
  return infiniteQueryOptions<
    SubscriptionsAdminListPlansResponse,
    AxiosError<SubscriptionsAdminListPlansError>,
    InfiniteData<SubscriptionsAdminListPlansResponse>,
    QueryKey<OptionsLegacyParser<SubscriptionsAdminListPlansData>>,
    | number
    | Pick<
        QueryKey<OptionsLegacyParser<SubscriptionsAdminListPlansData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<OptionsLegacyParser<SubscriptionsAdminListPlansData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await subscriptionsAdminListPlans({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: subscriptionsAdminListPlansInfiniteQueryKey(options),
    },
  );
};

export const subscriptionsAdminDeletePlanMutation = (
  options?: Partial<OptionsLegacyParser<SubscriptionsAdminDeletePlanData>>,
) => {
  const mutationOptions: UseMutationOptions<
    SubscriptionsAdminDeletePlanResponse,
    AxiosError<SubscriptionsAdminDeletePlanError>,
    OptionsLegacyParser<SubscriptionsAdminDeletePlanData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await subscriptionsAdminDeletePlan({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const subscriptionsAdminActivateUserSubscriptionQueryKey = (
  options: OptionsLegacyParser<SubscriptionsAdminActivateUserSubscriptionData>,
) => [createQueryKey("subscriptionsAdminActivateUserSubscription", options)];

export const subscriptionsAdminActivateUserSubscriptionOptions = (
  options: OptionsLegacyParser<SubscriptionsAdminActivateUserSubscriptionData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionsAdminActivateUserSubscription({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: subscriptionsAdminActivateUserSubscriptionQueryKey(options),
  });
};

export const subscriptionsAdminActivateUserSubscriptionMutation = (
  options?: Partial<
    OptionsLegacyParser<SubscriptionsAdminActivateUserSubscriptionData>
  >,
) => {
  const mutationOptions: UseMutationOptions<
    SubscriptionsAdminActivateUserSubscriptionResponse,
    AxiosError<SubscriptionsAdminActivateUserSubscriptionError>,
    OptionsLegacyParser<SubscriptionsAdminActivateUserSubscriptionData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await subscriptionsAdminActivateUserSubscription({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const subscriptionsAdminSuspendUserSubscriptionQueryKey = (
  options: OptionsLegacyParser<SubscriptionsAdminSuspendUserSubscriptionData>,
) => [createQueryKey("subscriptionsAdminSuspendUserSubscription", options)];

export const subscriptionsAdminSuspendUserSubscriptionOptions = (
  options: OptionsLegacyParser<SubscriptionsAdminSuspendUserSubscriptionData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionsAdminSuspendUserSubscription({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: subscriptionsAdminSuspendUserSubscriptionQueryKey(options),
  });
};

export const subscriptionsAdminSuspendUserSubscriptionMutation = (
  options?: Partial<
    OptionsLegacyParser<SubscriptionsAdminSuspendUserSubscriptionData>
  >,
) => {
  const mutationOptions: UseMutationOptions<
    SubscriptionsAdminSuspendUserSubscriptionResponse,
    AxiosError<SubscriptionsAdminSuspendUserSubscriptionError>,
    OptionsLegacyParser<SubscriptionsAdminSuspendUserSubscriptionData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await subscriptionsAdminSuspendUserSubscription({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const subscriptionsAdminVerifyUserSubscriptionQueryKey = (
  options: OptionsLegacyParser<SubscriptionsAdminVerifyUserSubscriptionData>,
) => [createQueryKey("subscriptionsAdminVerifyUserSubscription", options)];

export const subscriptionsAdminVerifyUserSubscriptionOptions = (
  options: OptionsLegacyParser<SubscriptionsAdminVerifyUserSubscriptionData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionsAdminVerifyUserSubscription({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: subscriptionsAdminVerifyUserSubscriptionQueryKey(options),
  });
};

export const subscriptionsAdminVerifyUserSubscriptionMutation = (
  options?: Partial<
    OptionsLegacyParser<SubscriptionsAdminVerifyUserSubscriptionData>
  >,
) => {
  const mutationOptions: UseMutationOptions<
    SubscriptionsAdminVerifyUserSubscriptionResponse,
    AxiosError<SubscriptionsAdminVerifyUserSubscriptionError>,
    OptionsLegacyParser<SubscriptionsAdminVerifyUserSubscriptionData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await subscriptionsAdminVerifyUserSubscription({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const subscriptionsSaveKycDocumentsQueryKey = (
  options: OptionsLegacyParser<SubscriptionsSaveKycDocumentsData>,
) => [createQueryKey("subscriptionsSaveKycDocuments", options)];

export const subscriptionsSaveKycDocumentsOptions = (
  options: OptionsLegacyParser<SubscriptionsSaveKycDocumentsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionsSaveKycDocuments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: subscriptionsSaveKycDocumentsQueryKey(options),
  });
};

export const subscriptionsSaveKycDocumentsMutation = (
  options?: Partial<OptionsLegacyParser<SubscriptionsSaveKycDocumentsData>>,
) => {
  const mutationOptions: UseMutationOptions<
    SubscriptionsSaveKycDocumentsResponse,
    AxiosError<SubscriptionsSaveKycDocumentsError>,
    OptionsLegacyParser<SubscriptionsSaveKycDocumentsData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await subscriptionsSaveKycDocuments({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const subscriptionsUpdateUserSubscriptionMutation = (
  options?: Partial<
    OptionsLegacyParser<SubscriptionsUpdateUserSubscriptionData>
  >,
) => {
  const mutationOptions: UseMutationOptions<
    SubscriptionsUpdateUserSubscriptionResponse,
    AxiosError<SubscriptionsUpdateUserSubscriptionError>,
    OptionsLegacyParser<SubscriptionsUpdateUserSubscriptionData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await subscriptionsUpdateUserSubscription({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const subscriptionsListPlansQueryKey = (
  options: OptionsLegacyParser<SubscriptionsListPlansData>,
) => [createQueryKey("subscriptionsListPlans", options)];

export const subscriptionsListPlansOptions = (
  options: OptionsLegacyParser<SubscriptionsListPlansData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionsListPlans({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: subscriptionsListPlansQueryKey(options),
  });
};

export const subscriptionsListPlansInfiniteQueryKey = (
  options: OptionsLegacyParser<SubscriptionsListPlansData>,
): QueryKey<OptionsLegacyParser<SubscriptionsListPlansData>> => [
  createQueryKey("subscriptionsListPlans", options, true),
];

export const subscriptionsListPlansInfiniteOptions = (
  options: OptionsLegacyParser<SubscriptionsListPlansData>,
) => {
  return infiniteQueryOptions<
    SubscriptionsListPlansResponse,
    AxiosError<SubscriptionsListPlansError>,
    InfiniteData<SubscriptionsListPlansResponse>,
    QueryKey<OptionsLegacyParser<SubscriptionsListPlansData>>,
    | number
    | Pick<
        QueryKey<OptionsLegacyParser<SubscriptionsListPlansData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<OptionsLegacyParser<SubscriptionsListPlansData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await subscriptionsListPlans({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: subscriptionsListPlansInfiniteQueryKey(options),
    },
  );
};

export const subscriptionsGetPlanQueryKey = (
  options: OptionsLegacyParser<SubscriptionsGetPlanData>,
) => [createQueryKey("subscriptionsGetPlan", options)];

export const subscriptionsGetPlanOptions = (
  options: OptionsLegacyParser<SubscriptionsGetPlanData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionsGetPlan({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: subscriptionsGetPlanQueryKey(options),
  });
};

export const subscriptionsListUserSubscriptionsQueryKey = (
  options: OptionsLegacyParser<SubscriptionsListUserSubscriptionsData>,
) => [createQueryKey("subscriptionsListUserSubscriptions", options)];

export const subscriptionsListUserSubscriptionsOptions = (
  options: OptionsLegacyParser<SubscriptionsListUserSubscriptionsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionsListUserSubscriptions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: subscriptionsListUserSubscriptionsQueryKey(options),
  });
};

export const subscriptionsListUserSubscriptionsInfiniteQueryKey = (
  options: OptionsLegacyParser<SubscriptionsListUserSubscriptionsData>,
): QueryKey<OptionsLegacyParser<SubscriptionsListUserSubscriptionsData>> => [
  createQueryKey("subscriptionsListUserSubscriptions", options, true),
];

export const subscriptionsListUserSubscriptionsInfiniteOptions = (
  options: OptionsLegacyParser<SubscriptionsListUserSubscriptionsData>,
) => {
  return infiniteQueryOptions<
    SubscriptionsListUserSubscriptionsResponse,
    AxiosError<SubscriptionsListUserSubscriptionsError>,
    InfiniteData<SubscriptionsListUserSubscriptionsResponse>,
    QueryKey<OptionsLegacyParser<SubscriptionsListUserSubscriptionsData>>,
    | number
    | Pick<
        QueryKey<
          OptionsLegacyParser<SubscriptionsListUserSubscriptionsData>
        >[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<
            OptionsLegacyParser<SubscriptionsListUserSubscriptionsData>
          >[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await subscriptionsListUserSubscriptions({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: subscriptionsListUserSubscriptionsInfiniteQueryKey(options),
    },
  );
};

export const subscriptionsCreateUserSubscriptionQueryKey = (
  options: OptionsLegacyParser<SubscriptionsCreateUserSubscriptionData>,
) => [createQueryKey("subscriptionsCreateUserSubscription", options)];

export const subscriptionsCreateUserSubscriptionOptions = (
  options: OptionsLegacyParser<SubscriptionsCreateUserSubscriptionData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionsCreateUserSubscription({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: subscriptionsCreateUserSubscriptionQueryKey(options),
  });
};

export const subscriptionsCreateUserSubscriptionMutation = (
  options?: Partial<
    OptionsLegacyParser<SubscriptionsCreateUserSubscriptionData>
  >,
) => {
  const mutationOptions: UseMutationOptions<
    SubscriptionsCreateUserSubscriptionResponse,
    AxiosError<SubscriptionsCreateUserSubscriptionError>,
    OptionsLegacyParser<SubscriptionsCreateUserSubscriptionData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await subscriptionsCreateUserSubscription({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const subscriptionsGetActiveUserSubscriptionQueryKey = (
  options: OptionsLegacyParser<SubscriptionsGetActiveUserSubscriptionData>,
) => [createQueryKey("subscriptionsGetActiveUserSubscription", options)];

export const subscriptionsGetActiveUserSubscriptionOptions = (
  options: OptionsLegacyParser<SubscriptionsGetActiveUserSubscriptionData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionsGetActiveUserSubscription({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: subscriptionsGetActiveUserSubscriptionQueryKey(options),
  });
};

export const subscriptionsSendOrganizationPlanIntentToAdminQueryKey = (
  options: OptionsLegacyParser<SubscriptionsSendOrganizationPlanIntentToAdminData>,
) => [
  createQueryKey("subscriptionsSendOrganizationPlanIntentToAdmin", options),
];

export const subscriptionsSendOrganizationPlanIntentToAdminOptions = (
  options: OptionsLegacyParser<SubscriptionsSendOrganizationPlanIntentToAdminData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionsSendOrganizationPlanIntentToAdmin({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: subscriptionsSendOrganizationPlanIntentToAdminQueryKey(options),
  });
};

export const subscriptionsSendOrganizationPlanIntentToAdminMutation = (
  options?: Partial<
    OptionsLegacyParser<SubscriptionsSendOrganizationPlanIntentToAdminData>
  >,
) => {
  const mutationOptions: UseMutationOptions<
    SubscriptionsSendOrganizationPlanIntentToAdminResponse,
    AxiosError<SubscriptionsSendOrganizationPlanIntentToAdminError>,
    OptionsLegacyParser<SubscriptionsSendOrganizationPlanIntentToAdminData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await subscriptionsSendOrganizationPlanIntentToAdmin({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const subscriptionsGetUserSubscriptionQueryKey = (
  options: OptionsLegacyParser<SubscriptionsGetUserSubscriptionData>,
) => [createQueryKey("subscriptionsGetUserSubscription", options)];

export const subscriptionsGetUserSubscriptionOptions = (
  options: OptionsLegacyParser<SubscriptionsGetUserSubscriptionData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionsGetUserSubscription({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: subscriptionsGetUserSubscriptionQueryKey(options),
  });
};

export const subscriptionsCancelUserSubscriptionQueryKey = (
  options: OptionsLegacyParser<SubscriptionsCancelUserSubscriptionData>,
) => [createQueryKey("subscriptionsCancelUserSubscription", options)];

export const subscriptionsCancelUserSubscriptionOptions = (
  options: OptionsLegacyParser<SubscriptionsCancelUserSubscriptionData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionsCancelUserSubscription({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: subscriptionsCancelUserSubscriptionQueryKey(options),
  });
};

export const subscriptionsCancelUserSubscriptionMutation = (
  options?: Partial<
    OptionsLegacyParser<SubscriptionsCancelUserSubscriptionData>
  >,
) => {
  const mutationOptions: UseMutationOptions<
    SubscriptionsCancelUserSubscriptionResponse,
    AxiosError<SubscriptionsCancelUserSubscriptionError>,
    OptionsLegacyParser<SubscriptionsCancelUserSubscriptionData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await subscriptionsCancelUserSubscription({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
