export interface Country {
  name: string
  code: string
  emoji: string
  unicode: string
  image: string
  dial_code: string
  currency_code: string
}

export const countries: Country[] = [
  { name: "Afghanistan", code: "AF", emoji: "🇦🇫", unicode: "U+1F1E6 U+1F1EB", image: "AF.svg", dial_code: "+93", currency_code: "AFN" },
  { name: "Åland Islands", code: "AX", emoji: "🇦🇽", unicode: "U+1F1E6 U+1F1FD", image: "AX.svg", dial_code: "+358", currency_code: "EUR" },
  { name: "Albania", code: "AL", emoji: "🇦🇱", unicode: "U+1F1E6 U+1F1F1", image: "AL.svg", dial_code: "+355", currency_code: "ALL" },
  { name: "Algeria", code: "DZ", emoji: "🇩🇿", unicode: "U+1F1E9 U+1F1FF", image: "DZ.svg", dial_code: "+213", currency_code: "DZD" },
  { name: "American Samoa", code: "AS", emoji: "🇦🇸", unicode: "U+1F1E6 U+1F1F8", image: "AS.svg", dial_code: "+1684", currency_code: "USD" },
  { name: "Andorra", code: "AD", emoji: "🇦🇩", unicode: "U+1F1E6 U+1F1E9", image: "AD.svg", dial_code: "+376", currency_code: "EUR" },
  { name: "Angola", code: "AO", emoji: "🇦🇴", unicode: "U+1F1E6 U+1F1F4", image: "AO.svg", dial_code: "+244", currency_code: "AOA" },
  { name: "Anguilla", code: "AI", emoji: "🇦🇮", unicode: "U+1F1E6 U+1F1EE", image: "AI.svg", dial_code: "+1264", currency_code: "XCD" },
  { name: "Antarctica", code: "AQ", emoji: "🇦🇶", unicode: "U+1F1E6 U+1F1F6", image: "AQ.svg", dial_code: "+672", currency_code: "XCD" },
  { name: "Antigua & Barbuda", code: "AG", emoji: "🇦🇬", unicode: "U+1F1E6 U+1F1EC", image: "AG.svg", dial_code: "+1268", currency_code: "XCD" },
  { name: "Argentina", code: "AR", emoji: "🇦🇷", unicode: "U+1F1E6 U+1F1F7", image: "AR.svg", dial_code: "+54", currency_code: "ARS" },
  { name: "Armenia", code: "AM", emoji: "🇦🇲", unicode: "U+1F1E6 U+1F1F2", image: "AM.svg", dial_code: "+374", currency_code: "AMD" },
  { name: "Aruba", code: "AW", emoji: "🇦🇼", unicode: "U+1F1E6 U+1F1FC", image: "AW.svg", dial_code: "+297", currency_code: "AWG" },
  { name: "Australia", code: "AU", emoji: "🇦🇺", unicode: "U+1F1E6 U+1F1FA", image: "AU.svg", dial_code: "+61", currency_code: "AUD" },
  { name: "Austria", code: "AT", emoji: "🇦🇹", unicode: "U+1F1E6 U+1F1F9", image: "AT.svg", dial_code: "+43", currency_code: "EUR" },
  { name: "Azerbaijan", code: "AZ", emoji: "🇦🇿", unicode: "U+1F1E6 U+1F1FF", image: "AZ.svg", dial_code: "+994", currency_code: "AZN" },
  { name: "Bahamas", code: "BS", emoji: "🇧🇸", unicode: "U+1F1E7 U+1F1F8", image: "BS.svg", dial_code: "+1242", currency_code: "BSD" },
  { name: "Bahrain", code: "BH", emoji: "🇧🇭", unicode: "U+1F1E7 U+1F1ED", image: "BH.svg", dial_code: "+973", currency_code: "BHD" },
  { name: "Bangladesh", code: "BD", emoji: "🇧🇩", unicode: "U+1F1E7 U+1F1E9", image: "BD.svg", dial_code: "+880", currency_code: "BDT" },
  { name: "Barbados", code: "BB", emoji: "🇧🇧", unicode: "U+1F1E7 U+1F1E7", image: "BB.svg", dial_code: "+1246", currency_code: "BBD" },
  { name: "Belarus", code: "BY", emoji: "🇧🇾", unicode: "U+1F1E7 U+1F1FE", image: "BY.svg", dial_code: "+375", currency_code: "BYN" },
  { name: "Belgium", code: "BE", emoji: "🇧🇪", unicode: "U+1F1E7 U+1F1EA", image: "BE.svg", dial_code: "+32", currency_code: "EUR" },
  { name: "Belize", code: "BZ", emoji: "🇧🇿", unicode: "U+1F1E7 U+1F1FF", image: "BZ.svg", dial_code: "+501", currency_code: "BZD" },
  { name: "Benin", code: "BJ", emoji: "🇧🇯", unicode: "U+1F1E7 U+1F1EF", image: "BJ.svg", dial_code: "+229", currency_code: "XOF" },
  { name: "Bermuda", code: "BM", emoji: "🇧🇲", unicode: "U+1F1E7 U+1F1F2", image: "BM.svg", dial_code: "+1441", currency_code: "BMD" },
  { name: "Bhutan", code: "BT", emoji: "🇧🇹", unicode: "U+1F1E7 U+1F1F9", image: "BT.svg", dial_code: "+975", currency_code: "BTN" },
  { name: "Bolivia", code: "BO", emoji: "🇧🇴", unicode: "U+1F1E7 U+1F1F4", image: "BO.svg", dial_code: "+591", currency_code: "BOB" },
  { name: "Bosnia & Herzegovina", code: "BA", emoji: "🇧🇦", unicode: "U+1F1E7 U+1F1E6", image: "BA.svg", dial_code: "+387", currency_code: "BAM" },
  { name: "Botswana", code: "BW", emoji: "🇧🇼", unicode: "U+1F1E7 U+1F1FC", image: "BW.svg", dial_code: "+267", currency_code: "BWP" },
  { name: "Brazil", code: "BR", emoji: "🇧🇷", unicode: "U+1F1E7 U+1F1F7", image: "BR.svg", dial_code: "+55", currency_code: "BRL" },
  { name: "British Indian Ocean Territory", code: "IO", emoji: "🇮🇴", unicode: "U+1F1EE U+1F1F4", image: "IO.svg", dial_code: "+246", currency_code: "USD" },
  { name: "Brunei", code: "BN", emoji: "🇧🇳", unicode: "U+1F1E7 U+1F1F3", image: "BN.svg", dial_code: "+673", currency_code: "BND" },
  { name: "Bulgaria", code: "BG", emoji: "🇧🇬", unicode: "U+1F1E7 U+1F1EC", image: "BG.svg", dial_code: "+359", currency_code: "BGN" },
  { name: "Burkina Faso", code: "BF", emoji: "🇧🇫", unicode: "U+1F1E7 U+1F1EB", image: "BF.svg", dial_code: "+226", currency_code: "XOF" },
  { name: "Burundi", code: "BI", emoji: "🇧🇮", unicode: "U+1F1E7 U+1F1EE", image: "BI.svg", dial_code: "+257", currency_code: "BIF" },
  { name: "Cambodia", code: "KH", emoji: "🇰🇭", unicode: "U+1F1F0 U+1F1ED", image: "KH.svg", dial_code: "+855", currency_code: "KHR" },
  { name: "Cameroon", code: "CM", emoji: "🇨🇲", unicode: "U+1F1E8 U+1F1F2", image: "CM.svg", dial_code: "+237", currency_code: "XAF" },
  { name: "Canada", code: "CA", emoji: "🇨🇦", unicode: "U+1F1E8 U+1F1E6", image: "CA.svg", dial_code: "+1", currency_code: "CAD" },
  { name: "Cape Verde", code: "CV", emoji: "🇨🇻", unicode: "U+1F1E8 U+1F1FB", image: "CV.svg", dial_code: "+238", currency_code: "CVE" },
  { name: "Cayman Islands", code: "KY", emoji: "🇰🇾", unicode: "U+1F1F0 U+1F1FE", image: "KY.svg", dial_code: "+345", currency_code: "KYD" },
  { name: "Central African Republic", code: "CF", emoji: "🇨🇫", unicode: "U+1F1E8 U+1F1EB", image: "CF.svg", dial_code: "+236", currency_code: "XAF" },
  { name: "Chad", code: "TD", emoji: "🇹🇩", unicode: "U+1F1F9 U+1F1E9", image: "TD.svg", dial_code: "+235", currency_code: "CDF" },
  { name: "Chile", code: "CL", emoji: "🇨🇱", unicode: "U+1F1E8 U+1F1F1", image: "CL.svg", dial_code: "+56", currency_code: "CLP" },
  { name: "China", code: "CN", emoji: "🇨🇳", unicode: "U+1F1E8 U+1F1F3", image: "CN.svg", dial_code: "+86", currency_code: "CNY" },
  { name: "Colombia", code: "CO", emoji: "🇨🇴", unicode: "U+1F1E8 U+1F1F4", image: "CO.svg", dial_code: "+57", currency_code: "COP" },
  { name: "Comoros", code: "KM", emoji: "🇰🇲", unicode: "U+1F1F0 U+1F1F2", image: "KM.svg", dial_code: "+269", currency_code: "KMF" },
  { name: "Congo - Brazzaville", code: "CG", emoji: "🇨🇬", unicode: "U+1F1E8 U+1F1EC", image: "CG.svg", dial_code: "+242", currency_code: "XAF" },
  { name: "Congo - Kinshasa", code: "CD", emoji: "🇨🇩", unicode: "U+1F1E8 U+1F1E9", image: "CD.svg", dial_code: "+243", currency_code: "CDF" },
  { name: "Costa Rica", code: "CR", emoji: "🇨🇷", unicode: "U+1F1E8 U+1F1F7", image: "CR.svg", dial_code: "+506", currency_code: "CRC" },
  { name: "Côte d'Ivoire", code: "CI", emoji: "🇨🇮", unicode: "U+1F1E8 U+1F1EE", image: "CI.svg", dial_code: "+225", currency_code: "XOF" },
  { name: "Croatia", code: "HR", emoji: "🇭🇷", unicode: "U+1F1ED U+1F1F7", image: "HR.svg", dial_code: "+385", currency_code: "EUR" },
  { name: "Cuba", code: "CU", emoji: "🇨🇺", unicode: "U+1F1E8 U+1F1FA", image: "CU.svg", dial_code: "+53", currency_code: "CUP" },
  { name: "Cyprus", code: "CY", emoji: "🇨🇾", unicode: "U+1F1E8 U+1F1FE", image: "CY.svg", dial_code: "+357", currency_code: "EUR" },
  { name: "Czechia", code: "CZ", emoji: "🇨🇿", unicode: "U+1F1E8 U+1F1FF", image: "CZ.svg", dial_code: "+420", currency_code: "CZK" },
  { name: "Denmark", code: "DK", emoji: "🇩🇰", unicode: "U+1F1E9 U+1F1F0", image: "DK.svg", dial_code: "+45", currency_code: "DKK" },
  { name: "Djibouti", code: "DJ", emoji: "🇩🇯", unicode: "U+1F1E9 U+1F1EF", image: "DJ.svg", dial_code: "+253", currency_code: "DJF" },
  { name: "Dominica", code: "DM", emoji: "🇩🇲", unicode: "U+1F1E9 U+1F1F2", image: "DM.svg", dial_code: "+1767", currency_code: "XCD" },
  { name: "Dominican Republic", code: "DO", emoji: "🇩🇴", unicode: "U+1F1E9 U+1F1F4", image: "DO.svg", dial_code: "+1849", currency_code: "DOP" },
  { name: "Ecuador", code: "EC", emoji: "🇪🇨", unicode: "U+1F1EA U+1F1E8", image: "EC.svg", dial_code: "+593", currency_code: "USD" },
  { name: "Egypt", code: "EG", emoji: "🇪🇬", unicode: "U+1F1EA U+1F1EC", image: "EG.svg", dial_code: "+20", currency_code: "EGP" },
  { name: "El Salvador", code: "SV", emoji: "🇸🇻", unicode: "U+1F1F8 U+1F1FB", image: "SV.svg", dial_code: "+503", currency_code: "SVC" },
  { name: "Eritrea", code: "ER", emoji: "🇪🇷", unicode: "U+1F1EA U+1F1F7", image: "ER.svg", dial_code: "+291", currency_code: "ERN" },
  { name: "Estonia", code: "EE", emoji: "🇪🇪", unicode: "U+1F1EA U+1F1EA", image: "EE.svg", dial_code: "+372", currency_code: "EUR" },
  { name: "Eswatini", code: "SZ", emoji: "🇸🇿", unicode: "U+1F1F8 U+1F1FF", image: "SZ.svg", dial_code: "+268", currency_code: "SZL" },
  { name: "Ethiopia", code: "ET", emoji: "🇪🇹", unicode: "U+1F1EA U+1F1F9", image: "ET.svg", dial_code: "+251", currency_code: "ETB" },
  { name: "Finland", code: "FI", emoji: "🇫🇮", unicode: "U+1F1EB U+1F1EE", image: "FI.svg", dial_code: "+358", currency_code: "EUR" },
  { name: "France", code: "FR", emoji: "🇫🇷", unicode: "U+1F1EB U+1F1F7", image: "FR.svg", dial_code: "+33", currency_code: "EUR" },
  { name: "Gabon", code: "GA", emoji: "🇬🇦", unicode: "U+1F1EC U+1F1E6", image: "GA.svg", dial_code: "+241", currency_code: "XAF" },
  { name: "Gambia", code: "GM", emoji: "🇬🇲", unicode: "U+1F1EC U+1F1F2", image: "GM.svg", dial_code: "+220", currency_code: "GMD" },
  { name: "Georgia", code: "GE", emoji: "🇬🇪", unicode: "U+1F1EC U+1F1EA", image: "GE.svg", dial_code: "+995", currency_code: "GEL" },
  { name: "Germany", code: "DE", emoji: "🇩🇪", unicode: "U+1F1E9 U+1F1EA", image: "DE.svg", dial_code: "+49", currency_code: "EUR" },
  { name: "Ghana", code: "GH", emoji: "🇬🇭", unicode: "U+1F1EC U+1F1ED", image: "GH.svg", dial_code: "+233", currency_code: "GHS" },
  { name: "Greece", code: "GR", emoji: "🇬🇷", unicode: "U+1F1EC U+1F1F7", image: "GR.svg", dial_code: "+30", currency_code: "EUR" },
  { name: "Guatemala", code: "GT", emoji: "🇬🇹", unicode: "U+1F1EC U+1F1F9", image: "GT.svg", dial_code: "+502", currency_code: "GTQ" },
  { name: "Guinea", code: "GN", emoji: "🇬🇳", unicode: "U+1F1EC U+1F1F3", image: "GN.svg", dial_code: "+224", currency_code: "GNF" },
  { name: "Guinea-Bissau", code: "GW", emoji: "🇬🇼", unicode: "U+1F1EC U+1F1FC", image: "GW.svg", dial_code: "+245", currency_code: "XOF" },
  { name: "Haiti", code: "HT", emoji: "🇭🇹", unicode: "U+1F1ED U+1F1F9", image: "HT.svg", dial_code: "+509", currency_code: "HTG" },
  { name: "Honduras", code: "HN", emoji: "🇭🇳", unicode: "U+1F1ED U+1F1F3", image: "HN.svg", dial_code: "+504", currency_code: "HNL" },
  { name: "Hong Kong SAR China", code: "HK", emoji: "🇭🇰", unicode: "U+1F1ED U+1F1F0", image: "HK.svg", dial_code: "+852", currency_code: "HKD" },
  { name: "Hungary", code: "HU", emoji: "🇭🇺", unicode: "U+1F1ED U+1F1FA", image: "HU.svg", dial_code: "+36", currency_code: "HUF" },
  { name: "Iceland", code: "IS", emoji: "🇮🇸", unicode: "U+1F1EE U+1F1F8", image: "IS.svg", dial_code: "+354", currency_code: "ISK" },
  { name: "India", code: "IN", emoji: "🇮🇳", unicode: "U+1F1EE U+1F1F3", image: "IN.svg", dial_code: "+91", currency_code: "INR" },
  { name: "Indonesia", code: "ID", emoji: "🇮🇩", unicode: "U+1F1EE U+1F1E9", image: "ID.svg", dial_code: "+62", currency_code: "IDR" },
  { name: "Iran", code: "IR", emoji: "🇮🇷", unicode: "U+1F1EE U+1F1F7", image: "IR.svg", dial_code: "+98", currency_code: "IRR" },
  { name: "Iraq", code: "IQ", emoji: "🇮🇶", unicode: "U+1F1EE U+1F1F6", image: "IQ.svg", dial_code: "+964", currency_code: "IQD" },
  { name: "Ireland", code: "IE", emoji: "🇮🇪", unicode: "U+1F1EE U+1F1EA", image: "IE.svg", dial_code: "+353", currency_code: "EUR" },
  { name: "Israel", code: "IL", emoji: "🇮🇱", unicode: "U+1F1EE U+1F1F1", image: "IL.svg", dial_code: "+972", currency_code: "ILS" },
  { name: "Italy", code: "IT", emoji: "🇮🇹", unicode: "U+1F1EE U+1F1F9", image: "IT.svg", dial_code: "+39", currency_code: "EUR" },
  { name: "Jamaica", code: "JM", emoji: "🇯🇲", unicode: "U+1F1EF U+1F1F2", image: "JM.svg", dial_code: "+1876", currency_code: "JMD" },
  { name: "Japan", code: "JP", emoji: "🇯🇵", unicode: "U+1F1EF U+1F1F5", image: "JP.svg", dial_code: "+81", currency_code: "JPY" },
  { name: "Jordan", code: "JO", emoji: "🇯🇴", unicode: "U+1F1EF U+1F1F4", image: "JO.svg", dial_code: "+962", currency_code: "JOD" },
  { name: "Kazakhstan", code: "KZ", emoji: "🇰🇿", unicode: "U+1F1F0 U+1F1FF", image: "KZ.svg", dial_code: "+77", currency_code: "KZT" },
  { name: "Kenya", code: "KE", emoji: "🇰🇪", unicode: "U+1F1F0 U+1F1EA", image: "KE.svg", dial_code: "+254", currency_code: "KES" },
  { name: "Kuwait", code: "KW", emoji: "🇰🇼", unicode: "U+1F1F0 U+1F1FC", image: "KW.svg", dial_code: "+965", currency_code: "KWD" },
  { name: "Kyrgyzstan", code: "KG", emoji: "🇰🇬", unicode: "U+1F1F0 U+1F1EC", image: "KG.svg", dial_code: "+996", currency_code: "KGS" },
  { name: "Laos", code: "LA", emoji: "🇱🇦", unicode: "U+1F1F1 U+1F1E6", image: "LA.svg", dial_code: "+856", currency_code: "LAK" },
  { name: "Latvia", code: "LV", emoji: "🇱🇻", unicode: "U+1F1F1 U+1F1FB", image: "LV.svg", dial_code: "+371", currency_code: "EUR" },
  { name: "Lebanon", code: "LB", emoji: "🇱🇧", unicode: "U+1F1F1 U+1F1E7", image: "LB.svg", dial_code: "+961", currency_code: "LBP" },
  { name: "Lesotho", code: "LS", emoji: "🇱🇸", unicode: "U+1F1F1 U+1F1F8", image: "LS.svg", dial_code: "+266", currency_code: "LSL" },
  { name: "Liberia", code: "LR", emoji: "🇱🇷", unicode: "U+1F1F1 U+1F1F7", image: "LR.svg", dial_code: "+231", currency_code: "LRD" },
  { name: "Libya", code: "LY", emoji: "🇱🇾", unicode: "U+1F1F1 U+1F1FE", image: "LY.svg", dial_code: "+218", currency_code: "LYD" },
  { name: "Liechtenstein", code: "LI", emoji: "🇱🇮", unicode: "U+1F1F1 U+1F1EE", image: "LI.svg", dial_code: "+423", currency_code: "CHF" },
  { name: "Lithuania", code: "LT", emoji: "🇱🇹", unicode: "U+1F1F1 U+1F1F9", image: "LT.svg", dial_code: "+370", currency_code: "EUR" },
  { name: "Luxembourg", code: "LU", emoji: "🇱🇺", unicode: "U+1F1F1 U+1F1FA", image: "LU.svg", dial_code: "+352", currency_code: "EUR" },
  { name: "Madagascar", code: "MG", emoji: "🇲🇬", unicode: "U+1F1F2 U+1F1EC", image: "MG.svg", dial_code: "+261", currency_code: "MGA" },
  { name: "Malawi", code: "MW", emoji: "🇲🇼", unicode: "U+1F1F2 U+1F1FC", image: "MW.svg", dial_code: "+265", currency_code: "MWK" },
  { name: "Malaysia", code: "MY", emoji: "🇲🇾", unicode: "U+1F1F2 U+1F1FE", image: "MY.svg", dial_code: "+60", currency_code: "MYR" },
  { name: "Maldives", code: "MV", emoji: "🇲🇻", unicode: "U+1F1F2 U+1F1FB", image: "MV.svg", dial_code: "+960", currency_code: "MVR" },
  { name: "Mali", code: "ML", emoji: "🇲🇱", unicode: "U+1F1F2 U+1F1F1", image: "ML.svg", dial_code: "+223", currency_code: "XOF" },
  { name: "Malta", code: "MT", emoji: "🇲🇹", unicode: "U+1F1F2 U+1F1F9", image: "MT.svg", dial_code: "+356", currency_code: "EUR" },
  { name: "Mauritania", code: "MR", emoji: "🇲🇷", unicode: "U+1F1F2 U+1F1F7", image: "MR.svg", dial_code: "+222", currency_code: "MRU" },
  { name: "Mauritius", code: "MU", emoji: "🇲🇺", unicode: "U+1F1F2 U+1F1FA", image: "MU.svg", dial_code: "+230", currency_code: "MUR" },
  { name: "Mexico", code: "MX", emoji: "🇲🇽", unicode: "U+1F1F2 U+1F1FD", image: "MX.svg", dial_code: "+52", currency_code: "MXN" },
  { name: "Moldova", code: "MD", emoji: "🇲🇩", unicode: "U+1F1F2 U+1F1E9", image: "MD.svg", dial_code: "+373", currency_code: "MDL" },
  { name: "Monaco", code: "MC", emoji: "🇲🇨", unicode: "U+1F1F2 U+1F1E8", image: "MC.svg", dial_code: "+377", currency_code: "EUR" },
  { name: "Mongolia", code: "MN", emoji: "🇲🇳", unicode: "U+1F1F2 U+1F1F3", image: "MN.svg", dial_code: "+976", currency_code: "MNT" },
  { name: "Montenegro", code: "ME", emoji: "🇲🇪", unicode: "U+1F1F2 U+1F1EA", image: "ME.svg", dial_code: "+382", currency_code: "EUR" },
  { name: "Morocco", code: "MA", emoji: "🇲🇦", unicode: "U+1F1F2 U+1F1E6", image: "MA.svg", dial_code: "+212", currency_code: "MAD" },
  { name: "Mozambique", code: "MZ", emoji: "🇲🇿", unicode: "U+1F1F2 U+1F1FF", image: "MZ.svg", dial_code: "+258", currency_code: "MZN" },
  { name: "Myanmar (Burma)", code: "MM", emoji: "🇲🇲", unicode: "U+1F1F2 U+1F1F2", image: "MM.svg", dial_code: "+95", currency_code: "MMK" },
  { name: "Namibia", code: "NA", emoji: "🇳🇦", unicode: "U+1F1F3 U+1F1E6", image: "NA.svg", dial_code: "+264", currency_code: "NAD" },
  { name: "Nepal", code: "NP", emoji: "🇳🇵", unicode: "U+1F1F3 U+1F1F5", image: "NP.svg", dial_code: "+977", currency_code: "NPR" },
  { name: "Netherlands", code: "NL", emoji: "🇳🇱", unicode: "U+1F1F3 U+1F1F1", image: "NL.svg", dial_code: "+31", currency_code: "EUR" },
  { name: "New Zealand", code: "NZ", emoji: "🇳🇿", unicode: "U+1F1F3 U+1F1FF", image: "NZ.svg", dial_code: "+64", currency_code: "NZD" },
  { name: "Nicaragua", code: "NI", emoji: "🇳🇮", unicode: "U+1F1F3 U+1F1EE", image: "NI.svg", dial_code: "+505", currency_code: "NIO" },
  { name: "Niger", code: "NE", emoji: "🇳🇪", unicode: "U+1F1F3 U+1F1EA", image: "NE.svg", dial_code: "+227", currency_code: "XOF" },
  { name: "Nigeria", code: "NG", emoji: "🇳🇬", unicode: "U+1F1F3 U+1F1EC", image: "NG.svg", dial_code: "+234", currency_code: "NGN" },
  { name: "North Macedonia", code: "MK", emoji: "🇲🇰", unicode: "U+1F1F2 U+1F1F0", image: "MK.svg", dial_code: "+389", currency_code: "MKD" },
  { name: "Norway", code: "NO", emoji: "🇳🇴", unicode: "U+1F1F3 U+1F1F4", image: "NO.svg", dial_code: "+47", currency_code: "NOK" },
  { name: "Oman", code: "OM", emoji: "🇴🇲", unicode: "U+1F1F4 U+1F1F2", image: "OM.svg", dial_code: "+968", currency_code: "OMR" },
  { name: "Pakistan", code: "PK", emoji: "🇵🇰", unicode: "U+1F1F5 U+1F1F0", image: "PK.svg", dial_code: "+92", currency_code: "PKR" },
  { name: "Panama", code: "PA", emoji: "🇵🇦", unicode: "U+1F1F5 U+1F1E6", image: "PA.svg", dial_code: "+507", currency_code: "PAB" },
  { name: "Papua New Guinea", code: "PG", emoji: "🇵🇬", unicode: "U+1F1F5 U+1F1EC", image: "PG.svg", dial_code: "+675", currency_code: "PGK" },
  { name: "Paraguay", code: "PY", emoji: "🇵🇾", unicode: "U+1F1F5 U+1F1FE", image: "PY.svg", dial_code: "+595", currency_code: "PYG" },
  { name: "Peru", code: "PE", emoji: "🇵🇪", unicode: "U+1F1F5 U+1F1EA", image: "PE.svg", dial_code: "+51", currency_code: "PEN" },
  { name: "Philippines", code: "PH", emoji: "🇵🇭", unicode: "U+1F1F5 U+1F1ED", image: "PH.svg", dial_code: "+63", currency_code: "PHP" },
  { name: "Poland", code: "PL", emoji: "🇵🇱", unicode: "U+1F1F5 U+1F1F1", image: "PL.svg", dial_code: "+48", currency_code: "PLN" },
  { name: "Portugal", code: "PT", emoji: "🇵🇹", unicode: "U+1F1F5 U+1F1F9", image: "PT.svg", dial_code: "+351", currency_code: "EUR" },
  { name: "Qatar", code: "QA", emoji: "🇶🇦", unicode: "U+1F1F6 U+1F1E6", image: "QA.svg", dial_code: "+974", currency_code: "QAR" },
  { name: "Romania", code: "RO", emoji: "🇷🇴", unicode: "U+1F1F7 U+1F1F4", image: "RO.svg", dial_code: "+40", currency_code: "RON" },
  { name: "Russia", code: "RU", emoji: "🇷🇺", unicode: "U+1F1F7 U+1F1FA", image: "RU.svg", dial_code: "+7", currency_code: "RUB" },
  { name: "Rwanda", code: "RW", emoji: "🇷🇼", unicode: "U+1F1F7 U+1F1FC", image: "RW.svg", dial_code: "+250", currency_code: "RWF" },
  { name: "Saudi Arabia", code: "SA", emoji: "🇸🇦", unicode: "U+1F1F8 U+1F1E6", image: "SA.svg", dial_code: "+966", currency_code: "SAR" },
  { name: "Senegal", code: "SN", emoji: "🇸🇳", unicode: "U+1F1F8 U+1F1F3", image: "SN.svg", dial_code: "+221", currency_code: "XOF" },
  { name: "Serbia", code: "RS", emoji: "🇷🇸", unicode: "U+1F1F7 U+1F1F8", image: "RS.svg", dial_code: "+381", currency_code: "RSD" },
  { name: "Seychelles", code: "SC", emoji: "🇸🇨", unicode: "U+1F1F8 U+1F1E8", image: "SC.svg", dial_code: "+248", currency_code: "SCR" },
  { name: "Sierra Leone", code: "SL", emoji: "🇸🇱", unicode: "U+1F1F8 U+1F1F1", image: "SL.svg", dial_code: "+232", currency_code: "SLL" },
  { name: "Singapore", code: "SG", emoji: "🇸🇬", unicode: "U+1F1F8 U+1F1EC", image: "SG.svg", dial_code: "+65", currency_code: "SGD" },
  { name: "Slovakia", code: "SK", emoji: "🇸🇰", unicode: "U+1F1F8 U+1F1F0", image: "SK.svg", dial_code: "+421", currency_code: "EUR" },
  { name: "Slovenia", code: "SI", emoji: "🇸🇮", unicode: "U+1F1F8 U+1F1EE", image: "SI.svg", dial_code: "+386", currency_code: "EUR" },
  { name: "Somalia", code: "SO", emoji: "🇸🇴", unicode: "U+1F1F8 U+1F1F4", image: "SO.svg", dial_code: "+252", currency_code: "SOS" },
  { name: "South Africa", code: "ZA", emoji: "🇿🇦", unicode: "U+1F1FF U+1F1E6", image: "ZA.svg", dial_code: "+27", currency_code: "ZAR" },
  { name: "South Korea", code: "KR", emoji: "🇰🇷", unicode: "U+1F1F0 U+1F1F7", image: "KR.svg", dial_code: "+82", currency_code: "KRW" },
  { name: "South Sudan", code: "SS", emoji: "🇸🇸", unicode: "U+1F1F8 U+1F1F8", image: "SS.svg", dial_code: "+211", currency_code: "SSP" },
  { name: "Spain", code: "ES", emoji: "🇪🇸", unicode: "U+1F1EA U+1F1F8", image: "ES.svg", dial_code: "+34", currency_code: "EUR" },
  { name: "Sri Lanka", code: "LK", emoji: "🇱🇰", unicode: "U+1F1F1 U+1F1F0", image: "LK.svg", dial_code: "+94", currency_code: "LKR" },
  { name: "Sudan", code: "SD", emoji: "🇸🇩", unicode: "U+1F1F8 U+1F1E9", image: "SD.svg", dial_code: "+249", currency_code: "SDG" },
  { name: "Suriname", code: "SR", emoji: "🇸🇷", unicode: "U+1F1F8 U+1F1F7", image: "SR.svg", dial_code: "+597", currency_code: "SRD" },
  { name: "Sweden", code: "SE", emoji: "🇸🇪", unicode: "U+1F1F8 U+1F1EA", image: "SE.svg", dial_code: "+46", currency_code: "SEK" },
  { name: "Switzerland", code: "CH", emoji: "🇨🇭", unicode: "U+1F1E8 U+1F1ED", image: "CH.svg", dial_code: "+41", currency_code: "CHF" },
  { name: "Syria", code: "SY", emoji: "🇸🇾", unicode: "U+1F1F8 U+1F1FE", image: "SY.svg", dial_code: "+963", currency_code: "SYP" },
  { name: "Taiwan", code: "TW", emoji: "🇹🇼", unicode: "U+1F1F9 U+1F1FC", image: "TW.svg", dial_code: "+886", currency_code: "TWD" },
  { name: "Tajikistan", code: "TJ", emoji: "🇹🇯", unicode: "U+1F1F9 U+1F1EF", image: "TJ.svg", dial_code: "+992", currency_code: "TJS" },
  { name: "Tanzania", code: "TZ", emoji: "🇹🇿", unicode: "U+1F1F9 U+1F1FF", image: "TZ.svg", dial_code: "+255", currency_code: "TZS" },
  { name: "Thailand", code: "TH", emoji: "🇹🇭", unicode: "U+1F1F9 U+1F1ED", image: "TH.svg", dial_code: "+66", currency_code: "THB" },
  { name: "Togo", code: "TG", emoji: "🇹🇬", unicode: "U+1F1F9 U+1F1EC", image: "TG.svg", dial_code: "+228", currency_code: "XOF" },
  { name: "Trinidad & Tobago", code: "TT", emoji: "🇹🇹", unicode: "U+1F1F9 U+1F1F9", image: "TT.svg", dial_code: "+1868", currency_code: "TTD" },
  { name: "Tunisia", code: "TN", emoji: "🇹🇳", unicode: "U+1F1F9 U+1F1F3", image: "TN.svg", dial_code: "+216", currency_code: "TND" },
  { name: "Turkey", code: "TR", emoji: "🇹🇷", unicode: "U+1F1F9 U+1F1F7", image: "TR.svg", dial_code: "+90", currency_code: "TRY" },
  { name: "Turkmenistan", code: "TM", emoji: "🇹🇲", unicode: "U+1F1F9 U+1F1F2", image: "TM.svg", dial_code: "+993", currency_code: "TMT" },
  { name: "Uganda", code: "UG", emoji: "🇺🇬", unicode: "U+1F1FA U+1F1EC", image: "UG.svg", dial_code: "+256", currency_code: "UGX" },
  { name: "Ukraine", code: "UA", emoji: "🇺🇦", unicode: "U+1F1FA U+1F1E6", image: "UA.svg", dial_code: "+380", currency_code: "UAH" },
  { name: "United Arab Emirates", code: "AE", emoji: "🇦🇪", unicode: "U+1F1E6 U+1F1EA", image: "AE.svg", dial_code: "+971", currency_code: "AED" },
  { name: "United Kingdom", code: "GB", emoji: "🇬🇧", unicode: "U+1F1EC U+1F1E7", image: "GB.svg", dial_code: "+44", currency_code: "GBP" },
  { name: "United States", code: "US", emoji: "🇺🇸", unicode: "U+1F1FA U+1F1F8", image: "US.svg", dial_code: "+1", currency_code: "USD" },
  { name: "Uruguay", code: "UY", emoji: "🇺🇾", unicode: "U+1F1FA U+1F1F8", image: "UY.svg", dial_code: "+598", currency_code: "UYU" },
  { name: "Uzbekistan", code: "UZ", emoji: "🇺🇿", unicode: "U+1F1FA U+1F1FF", image: "UZ.svg", dial_code: "+998", currency_code: "UZS" },
  { name: "Venezuela", code: "VE", emoji: "🇻🇪", unicode: "U+1F1FB U+1F1EA", image: "VE.svg", dial_code: "+58", currency_code: "VES" },
  { name: "Vietnam", code: "VN", emoji: "🇻🇳", unicode: "U+1F1FB U+1F1F3", image: "VN.svg", dial_code: "+84", currency_code: "VND" },
  { name: "Wallis & Futuna", code: "WF", emoji: "🇼🇫", unicode: "U+1F1FC U+1F1EB", image: "WF.svg", dial_code: "+681", currency_code: "XPF" },
]

// Default country (Cameroon) for phone input
export const defaultCountry = countries.find((c) => c.code === "CM") ?? countries[0]
