// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-axios";
import type {
  AnnotationServiceAddBookmarkData,
  AnnotationServiceAddBookmarkError,
  AnnotationServiceAddBookmarkResponse,
  AnnotationServiceCreateUserNoteData,
  AnnotationServiceCreateUserNoteError,
  AnnotationServiceCreateUserNoteResponse,
  AnnotationServiceUpdateUserNoteData,
  AnnotationServiceUpdateUserNoteError,
  AnnotationServiceUpdateUserNoteResponse,
  AnnotationServiceGetBookmarkByIdData,
  AnnotationServiceGetBookmarkByIdError,
  AnnotationServiceGetBookmarkByIdResponse,
  AnnotationServiceRemoveBookmarkData,
  AnnotationServiceRemoveBookmarkError,
  AnnotationServiceRemoveBookmarkResponse,
  AnnotationServiceListsUsersBookmarksData,
  AnnotationServiceListsUsersBookmarksError,
  AnnotationServiceListsUsersBookmarksResponse,
  AnnotationServiceListMaterialNotesData,
  AnnotationServiceListMaterialNotesError,
  AnnotationServiceListMaterialNotesResponse,
  AnnotationServiceGetNoteByIdData,
  AnnotationServiceGetNoteByIdError,
  AnnotationServiceGetNoteByIdResponse,
  AnnotationServiceDeleteNoteData,
  AnnotationServiceDeleteNoteError,
  AnnotationServiceDeleteNoteResponse,
  AnnotationServiceListsUsersNotesData,
  AnnotationServiceListsUsersNotesError,
  AnnotationServiceListsUsersNotesResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Adds a bookmark to a material for a user.
 */
export const annotationServiceAddBookmark = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<AnnotationServiceAddBookmarkData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AnnotationServiceAddBookmarkResponse,
    AnnotationServiceAddBookmarkError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/user/{bookmark.userId}/bookmark",
  });
};

/**
 * Creates a new user note.
 */
export const annotationServiceCreateUserNote = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    AnnotationServiceCreateUserNoteData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    AnnotationServiceCreateUserNoteResponse,
    AnnotationServiceCreateUserNoteError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/user/{note.userId}/note",
  });
};

/**
 * Updates an existing user note.
 */
export const annotationServiceUpdateUserNote = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    AnnotationServiceUpdateUserNoteData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).patch<
    AnnotationServiceUpdateUserNoteResponse,
    AnnotationServiceUpdateUserNoteError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/user/{note.userId}/note",
  });
};

/**
 * Retrieves a bookmark by its ID.
 */
export const annotationServiceGetBookmarkById = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    AnnotationServiceGetBookmarkByIdData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    AnnotationServiceGetBookmarkByIdResponse,
    AnnotationServiceGetBookmarkByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/user/{userId}/bookmark/{bookmarkId}",
  });
};

/**
 * Removes a bookmark using bookmark ID.
 */
export const annotationServiceRemoveBookmark = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    AnnotationServiceRemoveBookmarkData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).delete<
    AnnotationServiceRemoveBookmarkResponse,
    AnnotationServiceRemoveBookmarkError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/user/{userId}/bookmark/{bookmarkId}",
  });
};

/**
 * Retrieves all bookmarks for a user.
 */
export const annotationServiceListsUsersBookmarks = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    AnnotationServiceListsUsersBookmarksData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    AnnotationServiceListsUsersBookmarksResponse,
    AnnotationServiceListsUsersBookmarksError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/user/{userId}/bookmarks",
  });
};

/**
 * Retrieves all notes under a specific material.
 */
export const annotationServiceListMaterialNotes = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    AnnotationServiceListMaterialNotesData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    AnnotationServiceListMaterialNotesResponse,
    AnnotationServiceListMaterialNotesError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/user/{userId}/material/{materialId}/notes",
  });
};

/**
 * Retrieves a note by its ID.
 */
export const annotationServiceGetNoteById = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<AnnotationServiceGetNoteByIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AnnotationServiceGetNoteByIdResponse,
    AnnotationServiceGetNoteByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/user/{userId}/note/{noteId}",
  });
};

/**
 * Deletes a user note by its ID.
 */
export const annotationServiceDeleteNote = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<AnnotationServiceDeleteNoteData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    AnnotationServiceDeleteNoteResponse,
    AnnotationServiceDeleteNoteError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/user/{userId}/note/{noteId}",
  });
};

/**
 * Retrieves all notes for a user.
 */
export const annotationServiceListsUsersNotes = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    AnnotationServiceListsUsersNotesData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    AnnotationServiceListsUsersNotesResponse,
    AnnotationServiceListsUsersNotesError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/user/{userId}/notes",
  });
};
