// This file is auto-generated by @hey-api/openapi-ts

/**
 * Request to add a bookmark.
 */
export type AnnotationServiceAddBookmarkBody = {
  /**
   * Represents a user's saved bookmark for a specific material.
   */
  bookmark?: {
    /**
     * Unique identifier for the bookmark.
     */
    bookmarkId?: string;
    /**
     * ID of the bookmarked material.
     */
    materialId?: string;
    /**
     * Reference label (e.g., "Article A").
     */
    materialRef?: string;
    /**
     * Optional snippet of text.
     */
    snippet?: string;
    /**
     * Navigation path in the document.
     */
    breadcrumbs?: Array<v2Breadcrumb>;
    /**
     * Title of the document.
     */
    documentTitle?: string;
    /**
     * Localized document type titles.
     */
    documentTypeTitles?: v2DocumentTypeTitles;
    /**
     * Issue date of the document.
     */
    documentIssueDate?: string;
    /**
     * Full document ID.
     */
    documentId?: string;
    /**
     * Last update timestamp.
     */
    updatedAt?: string;
    /**
     * Creation timestamp.
     */
    createdAt?: string;
    /**
     * Deleted flag.
     */
    deleted?: boolean;
  };
};

/**
 * Request to create or update a user note.
 */
export type AnnotationServiceCreateUserNoteBody = {
  /**
   * The note to create or update.
   */
  note?: {
    /**
     * Unique note identifier.
     */
    noteId?: string;
    /**
     * ID of the material the note belongs to.
     */
    materialId?: string;
    /**
     * Reference label for the material.
     */
    materialRef?: string;
    /**
     * Full document ID.
     */
    documentId?: string;
    /**
     * Document reference string.
     */
    documentRef?: string;
    /**
     * Title of the document.
     */
    documentTitle?: string;
    /**
     * Optional plaintext message.
     */
    msg?: string;
    /**
     * Structured (e.g., rich-text) note content.
     */
    jsonMsg?: string;
    /**
     * Title of the note.
     */
    noteTitle?: string;
    /**
     * Last update timestamp.
     */
    updatedAt?: string;
    /**
     * Creation timestamp.
     */
    createdAt?: string;
    /**
     * Deleted flag.
     */
    deleted?: boolean;
  };
};

/**
 * Request to create or update a user note.
 */
export type AnnotationServiceUpdateUserNoteBody = {
  /**
   * The note to create or update.
   */
  note?: {
    /**
     * Unique note identifier.
     */
    noteId?: string;
    /**
     * ID of the material the note belongs to.
     */
    materialId?: string;
    /**
     * Reference label for the material.
     */
    materialRef?: string;
    /**
     * Full document ID.
     */
    documentId?: string;
    /**
     * Document reference string.
     */
    documentRef?: string;
    /**
     * Title of the document.
     */
    documentTitle?: string;
    /**
     * Optional plaintext message.
     */
    msg?: string;
    /**
     * Structured (e.g., rich-text) note content.
     */
    jsonMsg?: string;
    /**
     * Title of the note.
     */
    noteTitle?: string;
    /**
     * Last update timestamp.
     */
    updatedAt?: string;
    /**
     * Creation timestamp.
     */
    createdAt?: string;
    /**
     * Deleted flag.
     */
    deleted?: boolean;
  };
};

export type protobufAny = {
  [key: string]: unknown;
};

export type rpcStatus = {
  code?: number;
  message?: string;
  details?: Array<protobufAny>;
};

/**
 * Response after adding a bookmark.
 */
export type v2AddBookMarkResponse = {
  bookmark?: v2Bookmark;
};

/**
 * Represents a user's saved bookmark for a specific material.
 */
export type v2Bookmark = {
  /**
   * Unique identifier for the bookmark.
   */
  bookmarkId?: string;
  /**
   * ID of the user who created the bookmark.
   */
  userId?: string;
  /**
   * ID of the bookmarked material.
   */
  materialId?: string;
  /**
   * Reference label (e.g., "Article A").
   */
  materialRef?: string;
  /**
   * Optional snippet of text.
   */
  snippet?: string;
  /**
   * Navigation path in the document.
   */
  breadcrumbs?: Array<v2Breadcrumb>;
  /**
   * Title of the document.
   */
  documentTitle?: string;
  /**
   * Localized document type titles.
   */
  documentTypeTitles?: v2DocumentTypeTitles;
  /**
   * Issue date of the document.
   */
  documentIssueDate?: string;
  /**
   * Full document ID.
   */
  documentId?: string;
  /**
   * Last update timestamp.
   */
  updatedAt?: string;
  /**
   * Creation timestamp.
   */
  createdAt?: string;
  /**
   * Deleted flag.
   */
  deleted?: boolean;
};

/**
 * Represents a breadcrumb for navigating through documents.
 */
export type v2Breadcrumb = {
  /**
   * ID of the parent document.
   */
  parentId?: string;
  /**
   * Reference label.
   */
  ref?: string;
  /**
   * Material ID in the breadcrumb path.
   */
  materialId?: string;
};

/**
 * Response containing the created or updated note.
 */
export type v2CreateUpdateNoteResponse = {
  note?: v2UserNote;
};

/**
 * Response after deleting a note.
 */
export type v2DeleteResponse = {
  /**
   * Indicates successful deletion.
   */
  success?: boolean;
  /**
   * Optional message.
   */
  message?: string;
};

/**
 * Represents localized titles for a document type.
 */
export type v2DocumentTypeTitles = {
  /**
   * English title.
   */
  en?: string;
  /**
   * French title.
   */
  fr?: string;
};

/**
 * Response with the fetched bookmark.
 */
export type v2GetBookmarkByIDResponse = {
  bookmark?: v2Bookmark;
};

/**
 * Response with the fetched note.
 */
export type v2GetNoteByIDResponse = {
  note?: v2UserNote;
};

/**
 * Response listing all user bookmarks.
 */
export type v2ListUserBookmarksResponse = {
  /**
   * Pagination info.
   */
  statistics?: v2Statistics;
  /**
   * List of bookmarks.
   */
  bookmarks?: Array<v2Bookmark>;
};

/**
 * Response listing all user notes.
 */
export type v2ListUserNotesResponse = {
  /**
   * Pagination info.
   */
  statistics?: v2Statistics;
  /**
   * List of notes.
   */
  notes?: Array<v2UserNote>;
};

/**
 * Pagination metadata for lists.
 */
export type v2Statistics = {
  currentPage?: string;
  pageCount?: string;
  totalItems?: string;
};

/**
 * Represents a user's personal note attached to a material.
 */
export type v2UserNote = {
  /**
   * Unique note identifier.
   */
  noteId?: string;
  /**
   * ID of the note owner.
   */
  userId?: string;
  /**
   * ID of the material the note belongs to.
   */
  materialId?: string;
  /**
   * Reference label for the material.
   */
  materialRef?: string;
  /**
   * Full document ID.
   */
  documentId?: string;
  /**
   * Document reference string.
   */
  documentRef?: string;
  /**
   * Title of the document.
   */
  documentTitle?: string;
  /**
   * Optional plaintext message.
   */
  msg?: string;
  /**
   * Structured (e.g., rich-text) note content.
   */
  jsonMsg?: string;
  /**
   * Title of the note.
   */
  noteTitle?: string;
  /**
   * Last update timestamp.
   */
  updatedAt?: string;
  /**
   * Creation timestamp.
   */
  createdAt?: string;
  /**
   * Deleted flag.
   */
  deleted?: boolean;
};

export type AnnotationServiceAddBookmarkData = {
  body: AnnotationServiceAddBookmarkBody;
  path: {
    /**
     * ID of the user who created the bookmark.
     */
    "bookmark.userId": string;
  };
};

export type AnnotationServiceAddBookmarkResponse = v2AddBookMarkResponse;

export type AnnotationServiceAddBookmarkError = rpcStatus;

export type AnnotationServiceCreateUserNoteData = {
  body: AnnotationServiceCreateUserNoteBody;
  path: {
    /**
     * ID of the note owner.
     */
    "note.userId": string;
  };
};

export type AnnotationServiceCreateUserNoteResponse =
  v2CreateUpdateNoteResponse;

export type AnnotationServiceCreateUserNoteError = rpcStatus;

export type AnnotationServiceUpdateUserNoteData = {
  body: AnnotationServiceUpdateUserNoteBody;
  path: {
    /**
     * ID of the note owner.
     */
    "note.userId": string;
  };
};

export type AnnotationServiceUpdateUserNoteResponse =
  v2CreateUpdateNoteResponse;

export type AnnotationServiceUpdateUserNoteError = rpcStatus;

export type AnnotationServiceGetBookmarkByIdData = {
  path: {
    bookmarkId: string;
    /**
     * 'user_id' that owns the bookmark & wants to fetch.
     */
    userId: string;
  };
};

export type AnnotationServiceGetBookmarkByIdResponse =
  v2GetBookmarkByIDResponse;

export type AnnotationServiceGetBookmarkByIdError = rpcStatus;

export type AnnotationServiceRemoveBookmarkData = {
  path: {
    /**
     * ID of the bookmark.
     */
    bookmarkId: string;
    /**
     * ID of the user requesting removal.
     */
    userId: string;
  };
  query?: {
    /**
     * ID of the material.
     */
    materialId?: string;
  };
};

export type AnnotationServiceRemoveBookmarkResponse = v2DeleteResponse;

export type AnnotationServiceRemoveBookmarkError = rpcStatus;

export type AnnotationServiceListsUsersBookmarksData = {
  path: {
    userId: string;
  };
  query?: {
    page?: string;
    pageSize?: string;
  };
};

export type AnnotationServiceListsUsersBookmarksResponse =
  v2ListUserBookmarksResponse;

export type AnnotationServiceListsUsersBookmarksError = rpcStatus;

export type AnnotationServiceListMaterialNotesData = {
  path: {
    materialId: string;
    userId: string;
  };
  query?: {
    page?: string;
    pageSize?: string;
  };
};

export type AnnotationServiceListMaterialNotesResponse =
  v2ListUserNotesResponse;

export type AnnotationServiceListMaterialNotesError = rpcStatus;

export type AnnotationServiceGetNoteByIdData = {
  path: {
    noteId: string;
    /**
     * 'user_id' that owns the note & wants to fetch.
     */
    userId: string;
  };
};

export type AnnotationServiceGetNoteByIdResponse = v2GetNoteByIDResponse;

export type AnnotationServiceGetNoteByIdError = rpcStatus;

export type AnnotationServiceDeleteNoteData = {
  path: {
    /**
     * ID of the note to delete.
     */
    noteId: string;
    /**
     * User ID making the request.
     */
    userId: string;
  };
  query?: {
    /**
     * Material ID for validation.
     */
    materialId?: string;
  };
};

export type AnnotationServiceDeleteNoteResponse = v2DeleteResponse;

export type AnnotationServiceDeleteNoteError = rpcStatus;

export type AnnotationServiceListsUsersNotesData = {
  path: {
    userId: string;
  };
  query?: {
    page?: string;
    pageSize?: string;
  };
};

export type AnnotationServiceListsUsersNotesResponse = v2ListUserNotesResponse;

export type AnnotationServiceListsUsersNotesError = rpcStatus;
