// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-axios";
import type {
  SubscriptionsDeleteKycDocumentData,
  SubscriptionsDeleteKycDocumentError,
  SubscriptionsDeleteKycDocumentResponse,
  SubscriptionsListKycDocumentsData,
  SubscriptionsListKycDocumentsError,
  SubscriptionsListKycDocumentsResponse,
  SubscriptionsGetKycDocumentData,
  SubscriptionsGetKycDocumentError,
  SubscriptionsGetKycDocumentResponse,
  SubscriptionsUpdateKycDocumentStatusData,
  SubscriptionsUpdateKycDocumentStatusError,
  SubscriptionsUpdateKycDocumentStatusResponse,
  SubscriptionsAdminCreatePlanData,
  SubscriptionsAdminCreatePlanError,
  SubscriptionsAdminCreatePlanResponse,
  SubscriptionsAdminUpdatePlanData,
  SubscriptionsAdminUpdatePlanError,
  SubscriptionsAdminUpdatePlanResponse,
  SubscriptionsAdminListPlansData,
  SubscriptionsAdminListPlansError,
  SubscriptionsAdminListPlansResponse,
  SubscriptionsAdminDeletePlanData,
  SubscriptionsAdminDeletePlanError,
  SubscriptionsAdminDeletePlanResponse,
  SubscriptionsAdminActivateUserSubscriptionData,
  SubscriptionsAdminActivateUserSubscriptionError,
  SubscriptionsAdminActivateUserSubscriptionResponse,
  SubscriptionsAdminSuspendUserSubscriptionData,
  SubscriptionsAdminSuspendUserSubscriptionError,
  SubscriptionsAdminSuspendUserSubscriptionResponse,
  SubscriptionsAdminVerifyUserSubscriptionData,
  SubscriptionsAdminVerifyUserSubscriptionError,
  SubscriptionsAdminVerifyUserSubscriptionResponse,
  SubscriptionsSaveKycDocumentsData,
  SubscriptionsSaveKycDocumentsError,
  SubscriptionsSaveKycDocumentsResponse,
  SubscriptionsUpdateUserSubscriptionData,
  SubscriptionsUpdateUserSubscriptionError,
  SubscriptionsUpdateUserSubscriptionResponse,
  SubscriptionsListPlansData,
  SubscriptionsListPlansError,
  SubscriptionsListPlansResponse,
  SubscriptionsGetPlanData,
  SubscriptionsGetPlanError,
  SubscriptionsGetPlanResponse,
  SubscriptionsListUserSubscriptionsData,
  SubscriptionsListUserSubscriptionsError,
  SubscriptionsListUserSubscriptionsResponse,
  SubscriptionsCreateUserSubscriptionData,
  SubscriptionsCreateUserSubscriptionError,
  SubscriptionsCreateUserSubscriptionResponse,
  SubscriptionsGetActiveUserSubscriptionData,
  SubscriptionsGetActiveUserSubscriptionError,
  SubscriptionsGetActiveUserSubscriptionResponse,
  SubscriptionsSendOrganizationPlanIntentToAdminData,
  SubscriptionsSendOrganizationPlanIntentToAdminError,
  SubscriptionsSendOrganizationPlanIntentToAdminResponse,
  SubscriptionsGetUserSubscriptionData,
  SubscriptionsGetUserSubscriptionError,
  SubscriptionsGetUserSubscriptionResponse,
  SubscriptionsCancelUserSubscriptionData,
  SubscriptionsCancelUserSubscriptionError,
  SubscriptionsCancelUserSubscriptionResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Delete a KYC document
 */
export const subscriptionsDeleteKycDocument = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    SubscriptionsDeleteKycDocumentData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).delete<
    SubscriptionsDeleteKycDocumentResponse,
    SubscriptionsDeleteKycDocumentError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/user/{userId}/client/kyc/documents/{id}",
  });
};

/**
 * List all KYC documents with pagination and filters
 */
export const subscriptionsListKycDocuments = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<SubscriptionsListKycDocumentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    SubscriptionsListKycDocumentsResponse,
    SubscriptionsListKycDocumentsError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/user/{userId}/kyc/documents",
  });
};

/**
 * Get a single KYC document by ID
 */
export const subscriptionsGetKycDocument = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<SubscriptionsGetKycDocumentData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    SubscriptionsGetKycDocumentResponse,
    SubscriptionsGetKycDocumentError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/user/{userId}/kyc/documents/{id}",
  });
};

/**
 * Update KYC document status
 */
export const subscriptionsUpdateKycDocumentStatus = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    SubscriptionsUpdateKycDocumentStatusData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).patch<
    SubscriptionsUpdateKycDocumentStatusResponse,
    SubscriptionsUpdateKycDocumentStatusError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/user/{userId}/kyc/documents/{id}/status",
  });
};

/**
 * Admin: Create a new subscription plan
 */
export const subscriptionsAdminCreatePlan = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<SubscriptionsAdminCreatePlanData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    SubscriptionsAdminCreatePlanResponse,
    SubscriptionsAdminCreatePlanError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/users/{plan.userId}/subscription-plans",
  });
};

/**
 * Admin: Update an existing subscription plan
 */
export const subscriptionsAdminUpdatePlan = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<SubscriptionsAdminUpdatePlanData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    SubscriptionsAdminUpdatePlanResponse,
    SubscriptionsAdminUpdatePlanError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/users/{plan.userId}/subscription-plans/{plan.planId}",
  });
};

/**
 * Admin: List all subscription plans with full visibility
 * Includes inactive and hidden plans for administrative purposes
 */
export const subscriptionsAdminListPlans = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<SubscriptionsAdminListPlansData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    SubscriptionsAdminListPlansResponse,
    SubscriptionsAdminListPlansError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/users/{userId}/subscription-plans",
  });
};

/**
 * Admin: Delete a subscription plan by ID
 * Fails if plan has active subscriptions unless force flag is set
 */
export const subscriptionsAdminDeletePlan = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<SubscriptionsAdminDeletePlanData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    SubscriptionsAdminDeletePlanResponse,
    SubscriptionsAdminDeletePlanError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/users/{userId}/subscription-plans/{planId}",
  });
};

/**
 * Activate a user subscription
 */
export const subscriptionsAdminActivateUserSubscription = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    SubscriptionsAdminActivateUserSubscriptionData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    SubscriptionsAdminActivateUserSubscriptionResponse,
    SubscriptionsAdminActivateUserSubscriptionError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/users/{userId}/subscriptions/{subscriptionId}/activate",
  });
};

/**
 * Suspend a user subscription
 * Temporarily disables an active subscription
 */
export const subscriptionsAdminSuspendUserSubscription = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    SubscriptionsAdminSuspendUserSubscriptionData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    SubscriptionsAdminSuspendUserSubscriptionResponse,
    SubscriptionsAdminSuspendUserSubscriptionError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/users/{userId}/subscriptions/{subscriptionId}/suspend",
  });
};

/**
 * Verify a user subscription
 * Approves or rejects verification for special plans (e.g., Student)
 */
export const subscriptionsAdminVerifyUserSubscription = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    SubscriptionsAdminVerifyUserSubscriptionData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    SubscriptionsAdminVerifyUserSubscriptionResponse,
    SubscriptionsAdminVerifyUserSubscriptionError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/users/{userId}/subscriptions/{subscriptionId}/verify",
  });
};

/**
 * Save kyc documents
 */
export const subscriptionsSaveKycDocuments = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<SubscriptionsSaveKycDocumentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    SubscriptionsSaveKycDocumentsResponse,
    SubscriptionsSaveKycDocumentsError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/users/{document.userId}/kyc/documents",
  });
};

/**
 * Update an active user subscription settings
 * Allows updating auto-renewal and verification documents
 */
export const subscriptionsUpdateUserSubscription = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    SubscriptionsUpdateUserSubscriptionData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).put<
    SubscriptionsUpdateUserSubscriptionResponse,
    SubscriptionsUpdateUserSubscriptionError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/users/{subscription.userId}/subscriptions/{subscription.subscriptionId}",
  });
};

/**
 * List all available subscription plans visible to clients
 * Returns paginated list of active and visible plans
 */
export const subscriptionsListPlans = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<SubscriptionsListPlansData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    SubscriptionsListPlansResponse,
    SubscriptionsListPlansError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/users/{userId}/subscription-plans",
  });
};

/**
 * Get a specific subscription plan by ID or name
 */
export const subscriptionsGetPlan = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<SubscriptionsGetPlanData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    SubscriptionsGetPlanResponse,
    SubscriptionsGetPlanError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/users/{userId}/subscription-plans/{planId}",
  });
};

/**
 * List a user's subscription instances
 * Returns subscription history with pagination support
 */
export const subscriptionsListUserSubscriptions = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    SubscriptionsListUserSubscriptionsData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    SubscriptionsListUserSubscriptionsResponse,
    SubscriptionsListUserSubscriptionsError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/users/{userId}/subscriptions",
  });
};

/**
 * Create a new subscription for a user
 * Initiates payment flow and returns subscription with payment details
 */
export const subscriptionsCreateUserSubscription = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    SubscriptionsCreateUserSubscriptionData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    SubscriptionsCreateUserSubscriptionResponse,
    SubscriptionsCreateUserSubscriptionError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/users/{userId}/subscriptions",
  });
};

/**
 * Get the currently active subscription for a user
 * Returns the subscription with status 'active'
 */
export const subscriptionsGetActiveUserSubscription = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    SubscriptionsGetActiveUserSubscriptionData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    SubscriptionsGetActiveUserSubscriptionResponse,
    SubscriptionsGetActiveUserSubscriptionError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/users/{userId}/subscriptions/active",
  });
};

/**
 * Notifies the organization admin that a user has expressed interest
 * in subscribing to an organization subscription plan.
 * This does not activate a subscription or initiate payment.
 */
export const subscriptionsSendOrganizationPlanIntentToAdmin = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    SubscriptionsSendOrganizationPlanIntentToAdminData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    SubscriptionsSendOrganizationPlanIntentToAdminResponse,
    SubscriptionsSendOrganizationPlanIntentToAdminError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/users/{userId}/subscriptions/organization/intent",
  });
};

/**
 * Get a specific user subscription by ID
 */
export const subscriptionsGetUserSubscription = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    SubscriptionsGetUserSubscriptionData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    SubscriptionsGetUserSubscriptionResponse,
    SubscriptionsGetUserSubscriptionError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/users/{userId}/subscriptions/{subscriptionId}",
  });
};

/**
 * Cancel a user subscription
 * Marks subscription as canceled and records cancellation metadata
 */
export const subscriptionsCancelUserSubscription = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    SubscriptionsCancelUserSubscriptionData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    SubscriptionsCancelUserSubscriptionResponse,
    SubscriptionsCancelUserSubscriptionError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/users/{userId}/subscriptions/{subscriptionId}/cancel",
  });
};
