// This file is auto-generated by @hey-api/openapi-ts

export type protobufAny = {
  [key: string]: unknown;
};

export type rpcStatus = {
  code?: number;
  message?: string;
  details?: Array<protobufAny>;
};

export type SubscriptionsAdminActivateUserSubscriptionBody = {
  adminUserId?: string;
  startDate?: string;
  durationDays?: number;
};

export type SubscriptionsAdminCreatePlanBody = {
  plan?: {
    planId?: string;
    tier?: v2SubscriptionTierType;
    displayName?: v2MultilingualText;
    pricing?: v2Pricing;
    features?: v2PlanFeatures;
    benefits?: v2BenefitsList;
    description?: v2MultilingualText;
    isActive?: boolean;
    isVisible?: boolean;
    deletedAt?: string;
    createdAt?: string;
    updatedAt?: string;
  };
};

export type SubscriptionsAdminSuspendUserSubscriptionBody = {
  adminUserId?: string;
  reason?: string;
};

export type SubscriptionsAdminUpdatePlanBody = {
  plan?: {
    tier?: v2SubscriptionTierType;
    displayName?: v2MultilingualText;
    pricing?: v2Pricing;
    features?: v2PlanFeatures;
    benefits?: v2BenefitsList;
    description?: v2MultilingualText;
    isActive?: boolean;
    isVisible?: boolean;
    deletedAt?: string;
    createdAt?: string;
    updatedAt?: string;
  };
};

export type SubscriptionsAdminVerifyUserSubscriptionBody = {
  adminUserId?: string;
  verificationStatus?: v2VerificationStatus;
  verificationNotes?: string;
};

export type SubscriptionsCancelUserSubscriptionBody = {
  cancellationReason?: string;
};

export type SubscriptionsCreateUserSubscriptionBody = {
  planId?: string;
  preferedBillingCycle?: v2BillingCycle;
};

export type SubscriptionsSaveKycDocumentsBody = {
  document?: {
    id?: string;
    documentUrl?: string;
    documentType?: string;
    schoolName?: string;
    userName?: string;
    userEmail?: string;
    userPhone?: string;
    startDate?: string;
    endDate?: string;
    location?: string;
    status?: v2KycDocumentStatus;
    createdAt?: string;
    updatedAt?: string;
    deletedAt?: string;
  };
};

/**
 * OrganizationPlanIntentRequest represents a user's intent to subscribe
 * to an organization subscription plan. This request is used only to
 * notify the organization admin and does not activate a subscription or
 * initiate payment.
 */
export type SubscriptionsSendOrganizationPlanIntentToAdminBody = {
  userName?: string;
  userRole?: string;
  organizationName?: string;
  email?: string;
  preferedBillingCycle?: v2BillingCycle;
};

export type SubscriptionsUpdateKycDocumentStatusBody = {
  status?: v2KycDocumentStatus;
};

export type SubscriptionsUpdateUserSubscriptionBody = {
  subscription?: {
    plan?: v2PlanSummary;
    status?: v2SubscriptionStatus;
    billingCycle?: v2BillingCycle;
    startDate?: string;
    endDate?: string;
    daysRemaining?: number;
    autoRenew?: boolean;
    canceledAt?: string;
    canceledBy?: string;
    cancellationReason?: string;
    payment?: v2PaymentInfo;
    createdAt?: string;
    updatedAt?: string;
  };
};

export type v2BenefitsList = {
  en?: Array<string>;
  fr?: Array<string>;
};

export type v2BillingCycle =
  | "BILLING_CYCLE_UNSPECIFIED"
  | "BILLING_CYCLE_MONTHLY"
  | "BILLING_CYCLE_YEARLY";

export type v2FeatureLimit = {
  limit?: number;
  unlimited?: boolean;
  shareable?: boolean;
};

export type v2GetKycDocumentResponse = {
  document?: v2KycDocument;
};

export type v2GetPlanResponse = {
  plan?: v2SubscriptionPlan;
};

export type v2GetUserSubscriptionResponse = {
  subscription?: v2Subscription;
};

export type v2KycDocument = {
  id?: string;
  userId?: string;
  documentUrl?: string;
  documentType?: string;
  schoolName?: string;
  userName?: string;
  userEmail?: string;
  userPhone?: string;
  startDate?: string;
  endDate?: string;
  location?: string;
  status?: v2KycDocumentStatus;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: string;
};

/**
 * - KYC_DOCUMENT_STATUS_UNSPECIFIED: Default/unknown status
 * - KYC_DOCUMENT_STATUS_PENDING: Awaiting review
 * - KYC_DOCUMENT_STATUS_APPROVED: Verified and approved
 * - KYC_DOCUMENT_STATUS_REJECTED: Rejected during review
 * - KYC_DOCUMENT_STATUS_EXPIRED: Expired review
 */
export type v2KycDocumentStatus =
  | "KYC_DOCUMENT_STATUS_UNSPECIFIED"
  | "KYC_DOCUMENT_STATUS_PENDING"
  | "KYC_DOCUMENT_STATUS_APPROVED"
  | "KYC_DOCUMENT_STATUS_REJECTED"
  | "KYC_DOCUMENT_STATUS_EXPIRED";

export type v2ListKycDocumentsResponse = {
  documents?: Array<v2KycDocument>;
  pagination?: v2Pagination;
};

export type v2ListPlansResponse = {
  plans?: Array<v2SubscriptionPlan>;
  pagination?: v2Pagination;
};

export type v2ListUserSubscriptionsResponse = {
  subscriptions?: Array<v2Subscription>;
  pagination?: v2Pagination;
};

export type v2MultilingualText = {
  en?: string;
  fr?: string;
};

/**
 * OrganizationPlanIntentResponse contains confirmation details sent back
 * to the user after notifying the organization admin.
 */
export type v2OrganizationPlanIntentResponse = {
  planName?: string;
  adminEmail?: string;
  success?: boolean;
};

export type v2Pagination = {
  page?: number;
  pageSize?: number;
  totalCount?: string;
  totalPages?: string;
};

export type v2PaymentInfo = {
  paymentId?: string;
  amountXaf?: string;
  amountUsd?: string;
  paymentMethod?: v2PaymentMethod;
  status?: string;
  checkoutUrl?: string;
};

export type v2PaymentMethod =
  | "PAYMENT_METHOD_UNSPECIFIED"
  | "PAYMENT_METHOD_STRIPE"
  | "PAYMENT_METHOD_PAWAPAY";

export type v2PlanFeatures = {
  libraryAccess?: string;
  bookmarks?: v2FeatureLimit;
  notes?: v2FeatureLimit;
  folders?: v2FeatureLimit;
  catalogues?: v2FeatureLimit;
};

export type v2PlanSummary = {
  planId?: string;
  tier?: v2SubscriptionTierType;
  displayName?: v2MultilingualText;
  features?: v2PlanFeatures;
};

export type v2Pricing = {
  monthlyPriceXaf?: string;
  /**
   * Yearly price in XAF as decimal string.
   */
  yearlyPriceXaf?: string;
};

export type v2SaveKycDocumentResponse = {
  document?: v2KycDocument;
};

/**
 * - SORT_BY_COST_USD: Sort by costs in 'XAF'
 * - SORT_BY_COST_XAF: Sort by costs in 'USD'
 */
export type v2SortBy =
  | "SORT_BY_UNSPECIFIED"
  | "SORT_BY_COST_USD"
  | "SORT_BY_COST_XAF";

/**
 * - ASC: Sort in ascending order (A → Z)
 * - DESC: Sort in descending order (Z → A)
 */
export type v2SortOrder = "SORT_ORDER_UNSPECIFIED" | "ASC" | "DESC";

export type v2Subscription = {
  subscriptionId?: string;
  userId?: string;
  plan?: v2PlanSummary;
  status?: v2SubscriptionStatus;
  billingCycle?: v2BillingCycle;
  startDate?: string;
  endDate?: string;
  daysRemaining?: number;
  autoRenew?: boolean;
  canceledAt?: string;
  canceledBy?: string;
  cancellationReason?: string;
  payment?: v2PaymentInfo;
  createdAt?: string;
  updatedAt?: string;
};

export type v2SubscriptionPlan = {
  planId?: string;
  tier?: v2SubscriptionTierType;
  userId?: string;
  displayName?: v2MultilingualText;
  pricing?: v2Pricing;
  features?: v2PlanFeatures;
  benefits?: v2BenefitsList;
  description?: v2MultilingualText;
  isActive?: boolean;
  isVisible?: boolean;
  deletedAt?: string;
  createdAt?: string;
  updatedAt?: string;
};

/**
 * - SUBSCRIPTION_STATUS_PENDING: Subscription created but not yet active (awaiting payment or verification)
 * - SUBSCRIPTION_STATUS_ACTIVE: Subscription is active and user has access to features
 * - SUBSCRIPTION_STATUS_EXPIRED: Subscription period has ended naturally
 * - SUBSCRIPTION_STATUS_CANCELED: Subscription was canceled by user or admin
 * - SUBSCRIPTION_STATUS_SUSPENDED: Subscription was suspended by admin (temporary disable)
 */
export type v2SubscriptionStatus =
  | "SUBSCRIPTION_STATUS_UNSPECIFIED"
  | "SUBSCRIPTION_STATUS_PENDING"
  | "SUBSCRIPTION_STATUS_ACTIVE"
  | "SUBSCRIPTION_STATUS_EXPIRED"
  | "SUBSCRIPTION_STATUS_CANCELED"
  | "SUBSCRIPTION_STATUS_SUSPENDED";

export type v2SubscriptionTierType =
  | "SUBSCRIPTION_TIER_TYPE_UNSPECIFIED"
  | "SUBSCRIPTION_TIER_TYPE_FREE"
  | "SUBSCRIPTION_TIER_TYPE_STUDENT"
  | "SUBSCRIPTION_TIER_TYPE_PROFESSIONAL"
  | "SUBSCRIPTION_TIER_TYPE_ORGANIZATION";

export type v2UpdateKycDocumentStatusResponse = {
  document?: v2KycDocument;
};

/**
 * - VERIFICATION_STATUS_UNSPECIFIED: Default/unknown status
 * - VERIFICATION_STATUS_PENDING: Awaiting review
 * - VERIFICATION_STATUS_APPROVED: Verified and approved
 * - VERIFICATION_STATUS_REJECTED: Rejected during review
 */
export type v2VerificationStatus =
  | "VERIFICATION_STATUS_UNSPECIFIED"
  | "VERIFICATION_STATUS_PENDING"
  | "VERIFICATION_STATUS_APPROVED"
  | "VERIFICATION_STATUS_REJECTED";

export type SubscriptionsDeleteKycDocumentData = {
  path: {
    /**
     * kyc document trying to delete (soft delete)
     */
    id: string;
    /**
     * actor id that's trying to perform this action.
     */
    userId: string;
  };
};

export type SubscriptionsDeleteKycDocumentResponse = unknown;

export type SubscriptionsDeleteKycDocumentError = rpcStatus;

export type SubscriptionsListKycDocumentsData = {
  path: {
    /**
     * optional user_id or actor requesting all the kyc documents
     */
    userId: string;
  };
  query?: {
    /**
     * Optional document type filter
     */
    documentType?: string;
    /**
     * Page number
     */
    page?: number;
    /**
     * Number of items per page
     */
    pageSize?: number;
    /**
     * Optional status filter
     *
     * - KYC_DOCUMENT_STATUS_UNSPECIFIED: Default/unknown status
     * - KYC_DOCUMENT_STATUS_PENDING: Awaiting review
     * - KYC_DOCUMENT_STATUS_APPROVED: Verified and approved
     * - KYC_DOCUMENT_STATUS_REJECTED: Rejected during review
     * - KYC_DOCUMENT_STATUS_EXPIRED: Expired review
     */
    status?:
      | "KYC_DOCUMENT_STATUS_UNSPECIFIED"
      | "KYC_DOCUMENT_STATUS_PENDING"
      | "KYC_DOCUMENT_STATUS_APPROVED"
      | "KYC_DOCUMENT_STATUS_REJECTED"
      | "KYC_DOCUMENT_STATUS_EXPIRED";
  };
};

export type SubscriptionsListKycDocumentsResponse = v2ListKycDocumentsResponse;

export type SubscriptionsListKycDocumentsError = rpcStatus;

export type SubscriptionsGetKycDocumentData = {
  path: {
    /**
     * Document UUID
     */
    id: string;
    /**
     * user requesting the document
     */
    userId: string;
  };
};

export type SubscriptionsGetKycDocumentResponse = v2GetKycDocumentResponse;

export type SubscriptionsGetKycDocumentError = rpcStatus;

export type SubscriptionsUpdateKycDocumentStatusData = {
  body: SubscriptionsUpdateKycDocumentStatusBody;
  path: {
    /**
     * kyc document_id
     */
    id: string;
    /**
     * actor trying to perform this action
     */
    userId: string;
  };
};

export type SubscriptionsUpdateKycDocumentStatusResponse =
  v2UpdateKycDocumentStatusResponse;

export type SubscriptionsUpdateKycDocumentStatusError = rpcStatus;

export type SubscriptionsAdminCreatePlanData = {
  body: SubscriptionsAdminCreatePlanBody;
  path: {
    /**
     * The admin user who created this plan
     */
    "plan.userId": string;
  };
};

export type SubscriptionsAdminCreatePlanResponse = v2GetPlanResponse;

export type SubscriptionsAdminCreatePlanError = rpcStatus;

export type SubscriptionsAdminUpdatePlanData = {
  body: SubscriptionsAdminUpdatePlanBody;
  path: {
    /**
     * Unique plan identifier (UUID)
     */
    "plan.planId": string;
    /**
     * The admin user who created this plan
     */
    "plan.userId": string;
  };
};

export type SubscriptionsAdminUpdatePlanResponse = v2GetPlanResponse;

export type SubscriptionsAdminUpdatePlanError = rpcStatus;

export type SubscriptionsAdminListPlansData = {
  path: {
    /**
     * Admin user ID
     */
    userId: string;
  };
  query?: {
    /**
     * Filter: only active plans
     */
    isActive?: boolean;
    /**
     * Filter: only visible plans
     */
    isVisible?: boolean;
    /**
     * Pagination: page number
     */
    page?: number;
    /**
     * Pagination: results per page
     */
    pageSize?: number;
    /**
     * Sort field
     */
    sortBy?: string;
    /**
     * Sort order
     */
    sortOrder?: string;
  };
};

export type SubscriptionsAdminListPlansResponse = v2ListPlansResponse;

export type SubscriptionsAdminListPlansError = rpcStatus;

export type SubscriptionsAdminDeletePlanData = {
  path: {
    /**
     * Plan ID to delete
     */
    planId: string;
    /**
     * Admin user ID
     */
    userId: string;
  };
  query?: {
    /**
     * If true, force delete even if users are subscribed
     */
    force?: boolean;
  };
};

export type SubscriptionsAdminDeletePlanResponse = unknown;

export type SubscriptionsAdminDeletePlanError = rpcStatus;

export type SubscriptionsAdminActivateUserSubscriptionData = {
  body: SubscriptionsAdminActivateUserSubscriptionBody;
  path: {
    /**
     * Subscription ID to activate
     */
    subscriptionId: string;
    /**
     * User ID (subscription owner)
     */
    userId: string;
  };
};

export type SubscriptionsAdminActivateUserSubscriptionResponse =
  v2GetUserSubscriptionResponse;

export type SubscriptionsAdminActivateUserSubscriptionError = rpcStatus;

export type SubscriptionsAdminSuspendUserSubscriptionData = {
  body: SubscriptionsAdminSuspendUserSubscriptionBody;
  path: {
    /**
     * Subscription ID to suspend
     */
    subscriptionId: string;
    /**
     * User ID (subscription owner)
     */
    userId: string;
  };
};

export type SubscriptionsAdminSuspendUserSubscriptionResponse =
  v2GetUserSubscriptionResponse;

export type SubscriptionsAdminSuspendUserSubscriptionError = rpcStatus;

export type SubscriptionsAdminVerifyUserSubscriptionData = {
  body: SubscriptionsAdminVerifyUserSubscriptionBody;
  path: {
    /**
     * Subscription ID to verify
     */
    subscriptionId: string;
    /**
     * User ID (subscription owner)
     */
    userId: string;
  };
};

export type SubscriptionsAdminVerifyUserSubscriptionResponse =
  v2GetUserSubscriptionResponse;

export type SubscriptionsAdminVerifyUserSubscriptionError = rpcStatus;

export type SubscriptionsSaveKycDocumentsData = {
  body: SubscriptionsSaveKycDocumentsBody;
  path: {
    /**
     * User submitting the document
     */
    "document.userId": string;
  };
};

export type SubscriptionsSaveKycDocumentsResponse = v2SaveKycDocumentResponse;

export type SubscriptionsSaveKycDocumentsError = rpcStatus;

export type SubscriptionsUpdateUserSubscriptionData = {
  body: SubscriptionsUpdateUserSubscriptionBody;
  path: {
    /**
     * Unique subscription instance identifier (UUID)
     */
    "subscription.subscriptionId": string;
    /**
     * User who owns this subscription
     */
    "subscription.userId": string;
  };
};

export type SubscriptionsUpdateUserSubscriptionResponse =
  v2GetUserSubscriptionResponse;

export type SubscriptionsUpdateUserSubscriptionError = rpcStatus;

export type SubscriptionsListPlansData = {
  path: {
    /**
     * Authenticated user ID
     */
    userId: string;
  };
  query?: {
    /**
     * Filter: only active plans
     */
    isActive?: boolean;
    /**
     * Filter: only visible plans
     */
    isVisible?: boolean;
    /**
     * Pagination: page number (starts at 1)
     */
    page?: number;
    /**
     * Pagination: results per page
     */
    pageSize?: number;
    /**
     * Sort field (e.g.,"cost_usd", "cost_xaf"). default's 'cost_xaf'
     *
     * - SORT_BY_COST_USD: Sort by costs in 'XAF'
     * - SORT_BY_COST_XAF: Sort by costs in 'USD'
     */
    sortBy?: "SORT_BY_UNSPECIFIED" | "SORT_BY_COST_USD" | "SORT_BY_COST_XAF";
    /**
     * Sort order ("asc" or "desc")
     *
     * - ASC: Sort in ascending order (A → Z)
     * - DESC: Sort in descending order (Z → A)
     */
    sortOrder?: "SORT_ORDER_UNSPECIFIED" | "ASC" | "DESC";
  };
};

export type SubscriptionsListPlansResponse = v2ListPlansResponse;

export type SubscriptionsListPlansError = rpcStatus;

export type SubscriptionsGetPlanData = {
  path: {
    /**
     * Plan ID to retrieve
     */
    planId: string;
    /**
     * User performing action
     */
    userId: string;
  };
  query?: {
    /**
     * Plan name to retrieve
     */
    planName?:
      | "SUBSCRIPTION_TIER_TYPE_UNSPECIFIED"
      | "SUBSCRIPTION_TIER_TYPE_FREE"
      | "SUBSCRIPTION_TIER_TYPE_STUDENT"
      | "SUBSCRIPTION_TIER_TYPE_PROFESSIONAL"
      | "SUBSCRIPTION_TIER_TYPE_ORGANIZATION";
  };
};

export type SubscriptionsGetPlanResponse = v2GetPlanResponse;

export type SubscriptionsGetPlanError = rpcStatus;

export type SubscriptionsListUserSubscriptionsData = {
  path: {
    /**
     * User whose subscriptions to list
     */
    userId: string;
  };
  query?: {
    /**
     * Pagination: page number
     */
    page?: number;
    /**
     * Pagination: results per page
     */
    pageSize?: number;
    /**
     * Filter: only return specific status (e.g., "ACTIVE")
     *
     * - SUBSCRIPTION_STATUS_PENDING: Subscription created but not yet active (awaiting payment or verification)
     * - SUBSCRIPTION_STATUS_ACTIVE: Subscription is active and user has access to features
     * - SUBSCRIPTION_STATUS_EXPIRED: Subscription period has ended naturally
     * - SUBSCRIPTION_STATUS_CANCELED: Subscription was canceled by user or admin
     * - SUBSCRIPTION_STATUS_SUSPENDED: Subscription was suspended by admin (temporary disable)
     */
    status?:
      | "SUBSCRIPTION_STATUS_UNSPECIFIED"
      | "SUBSCRIPTION_STATUS_PENDING"
      | "SUBSCRIPTION_STATUS_ACTIVE"
      | "SUBSCRIPTION_STATUS_EXPIRED"
      | "SUBSCRIPTION_STATUS_CANCELED"
      | "SUBSCRIPTION_STATUS_SUSPENDED";
  };
};

export type SubscriptionsListUserSubscriptionsResponse =
  v2ListUserSubscriptionsResponse;

export type SubscriptionsListUserSubscriptionsError = rpcStatus;

export type SubscriptionsCreateUserSubscriptionData = {
  body: SubscriptionsCreateUserSubscriptionBody;
  path: {
    /**
     * User for whom to create a subscription
     */
    userId: string;
  };
};

export type SubscriptionsCreateUserSubscriptionResponse =
  v2GetUserSubscriptionResponse;

export type SubscriptionsCreateUserSubscriptionError = rpcStatus;

export type SubscriptionsGetActiveUserSubscriptionData = {
  path: {
    /**
     * User whose active subscription is queried
     */
    userId: string;
  };
};

export type SubscriptionsGetActiveUserSubscriptionResponse =
  v2GetUserSubscriptionResponse;

export type SubscriptionsGetActiveUserSubscriptionError = rpcStatus;

export type SubscriptionsSendOrganizationPlanIntentToAdminData = {
  body: SubscriptionsSendOrganizationPlanIntentToAdminBody;
  path: {
    /**
     * ID of the user expressing interest in the organization plan
     */
    userId: string;
  };
};

export type SubscriptionsSendOrganizationPlanIntentToAdminResponse =
  v2OrganizationPlanIntentResponse;

export type SubscriptionsSendOrganizationPlanIntentToAdminError = rpcStatus;

export type SubscriptionsGetUserSubscriptionData = {
  path: {
    /**
     * Subscription ID to retrieve
     */
    subscriptionId: string;
    /**
     * User ID (must own this subscription)
     */
    userId: string;
  };
};

export type SubscriptionsGetUserSubscriptionResponse =
  v2GetUserSubscriptionResponse;

export type SubscriptionsGetUserSubscriptionError = rpcStatus;

export type SubscriptionsCancelUserSubscriptionData = {
  body: SubscriptionsCancelUserSubscriptionBody;
  path: {
    /**
     * Subscription ID to cancel
     */
    subscriptionId: string;
    /**
     * User ID
     */
    userId: string;
  };
};

export type SubscriptionsCancelUserSubscriptionResponse =
  v2GetUserSubscriptionResponse;

export type SubscriptionsCancelUserSubscriptionError = rpcStatus;
