// This file is auto-generated by @hey-api/openapi-ts

import type { OptionsLegacyParser } from "@hey-api/client-axios";
import {
  queryOptions,
  type UseMutationOptions,
  infiniteQueryOptions,
  type InfiniteData,
} from "@tanstack/react-query";
import type {
  AnnotationServiceAddBookmarkData,
  AnnotationServiceAddBookmarkError,
  AnnotationServiceAddBookmarkResponse,
  AnnotationServiceCreateUserNoteData,
  AnnotationServiceCreateUserNoteError,
  AnnotationServiceCreateUserNoteResponse,
  AnnotationServiceUpdateUserNoteData,
  AnnotationServiceUpdateUserNoteError,
  AnnotationServiceUpdateUserNoteResponse,
  AnnotationServiceGetBookmarkByIdData,
  AnnotationServiceRemoveBookmarkData,
  AnnotationServiceRemoveBookmarkError,
  AnnotationServiceRemoveBookmarkResponse,
  AnnotationServiceListsUsersBookmarksData,
  AnnotationServiceListsUsersBookmarksError,
  AnnotationServiceListsUsersBookmarksResponse,
  AnnotationServiceListMaterialNotesData,
  AnnotationServiceListMaterialNotesError,
  AnnotationServiceListMaterialNotesResponse,
  AnnotationServiceGetNoteByIdData,
  AnnotationServiceDeleteNoteData,
  AnnotationServiceDeleteNoteError,
  AnnotationServiceDeleteNoteResponse,
  AnnotationServiceListsUsersNotesData,
  AnnotationServiceListsUsersNotesError,
  AnnotationServiceListsUsersNotesResponse,
} from "../types.gen";
import type { AxiosError } from "axios";
import {
  client,
  annotationServiceAddBookmark,
  annotationServiceCreateUserNote,
  annotationServiceUpdateUserNote,
  annotationServiceGetBookmarkById,
  annotationServiceRemoveBookmark,
  annotationServiceListsUsersBookmarks,
  annotationServiceListMaterialNotes,
  annotationServiceGetNoteById,
  annotationServiceDeleteNote,
  annotationServiceListsUsersNotes,
} from "../sdk.gen";

type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};

export const annotationServiceAddBookmarkQueryKey = (
  options: OptionsLegacyParser<AnnotationServiceAddBookmarkData>,
) => [createQueryKey("annotationServiceAddBookmark", options)];

export const annotationServiceAddBookmarkOptions = (
  options: OptionsLegacyParser<AnnotationServiceAddBookmarkData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await annotationServiceAddBookmark({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: annotationServiceAddBookmarkQueryKey(options),
  });
};

export const annotationServiceAddBookmarkMutation = (
  options?: Partial<OptionsLegacyParser<AnnotationServiceAddBookmarkData>>,
) => {
  const mutationOptions: UseMutationOptions<
    AnnotationServiceAddBookmarkResponse,
    AxiosError<AnnotationServiceAddBookmarkError>,
    OptionsLegacyParser<AnnotationServiceAddBookmarkData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await annotationServiceAddBookmark({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const annotationServiceCreateUserNoteQueryKey = (
  options: OptionsLegacyParser<AnnotationServiceCreateUserNoteData>,
) => [createQueryKey("annotationServiceCreateUserNote", options)];

export const annotationServiceCreateUserNoteOptions = (
  options: OptionsLegacyParser<AnnotationServiceCreateUserNoteData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await annotationServiceCreateUserNote({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: annotationServiceCreateUserNoteQueryKey(options),
  });
};

export const annotationServiceCreateUserNoteMutation = (
  options?: Partial<OptionsLegacyParser<AnnotationServiceCreateUserNoteData>>,
) => {
  const mutationOptions: UseMutationOptions<
    AnnotationServiceCreateUserNoteResponse,
    AxiosError<AnnotationServiceCreateUserNoteError>,
    OptionsLegacyParser<AnnotationServiceCreateUserNoteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await annotationServiceCreateUserNote({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const annotationServiceUpdateUserNoteMutation = (
  options?: Partial<OptionsLegacyParser<AnnotationServiceUpdateUserNoteData>>,
) => {
  const mutationOptions: UseMutationOptions<
    AnnotationServiceUpdateUserNoteResponse,
    AxiosError<AnnotationServiceUpdateUserNoteError>,
    OptionsLegacyParser<AnnotationServiceUpdateUserNoteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await annotationServiceUpdateUserNote({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const annotationServiceGetBookmarkByIdQueryKey = (
  options: OptionsLegacyParser<AnnotationServiceGetBookmarkByIdData>,
) => [createQueryKey("annotationServiceGetBookmarkById", options)];

export const annotationServiceGetBookmarkByIdOptions = (
  options: OptionsLegacyParser<AnnotationServiceGetBookmarkByIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await annotationServiceGetBookmarkById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: annotationServiceGetBookmarkByIdQueryKey(options),
  });
};

export const annotationServiceRemoveBookmarkMutation = (
  options?: Partial<OptionsLegacyParser<AnnotationServiceRemoveBookmarkData>>,
) => {
  const mutationOptions: UseMutationOptions<
    AnnotationServiceRemoveBookmarkResponse,
    AxiosError<AnnotationServiceRemoveBookmarkError>,
    OptionsLegacyParser<AnnotationServiceRemoveBookmarkData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await annotationServiceRemoveBookmark({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const annotationServiceListsUsersBookmarksQueryKey = (
  options: OptionsLegacyParser<AnnotationServiceListsUsersBookmarksData>,
) => [createQueryKey("annotationServiceListsUsersBookmarks", options)];

export const annotationServiceListsUsersBookmarksOptions = (
  options: OptionsLegacyParser<AnnotationServiceListsUsersBookmarksData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await annotationServiceListsUsersBookmarks({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: annotationServiceListsUsersBookmarksQueryKey(options),
  });
};

const createInfiniteParams = <
  K extends Pick<
    QueryKey<OptionsLegacyParser>[0],
    "body" | "headers" | "path" | "query"
  >,
>(
  queryKey: QueryKey<OptionsLegacyParser>,
  page: K,
) => {
  const params = queryKey[0];
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...queryKey[0].path,
      ...page.path,
    };
  }
  if (page.query) {
    params.query = {
      ...queryKey[0].query,
      ...page.query,
    };
  }
  return params as unknown as typeof page;
};

export const annotationServiceListsUsersBookmarksInfiniteQueryKey = (
  options: OptionsLegacyParser<AnnotationServiceListsUsersBookmarksData>,
): QueryKey<OptionsLegacyParser<AnnotationServiceListsUsersBookmarksData>> => [
  createQueryKey("annotationServiceListsUsersBookmarks", options, true),
];

export const annotationServiceListsUsersBookmarksInfiniteOptions = (
  options: OptionsLegacyParser<AnnotationServiceListsUsersBookmarksData>,
) => {
  return infiniteQueryOptions<
    AnnotationServiceListsUsersBookmarksResponse,
    AxiosError<AnnotationServiceListsUsersBookmarksError>,
    InfiniteData<AnnotationServiceListsUsersBookmarksResponse>,
    QueryKey<OptionsLegacyParser<AnnotationServiceListsUsersBookmarksData>>,
    | string
    | Pick<
        QueryKey<
          OptionsLegacyParser<AnnotationServiceListsUsersBookmarksData>
        >[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<
            OptionsLegacyParser<AnnotationServiceListsUsersBookmarksData>
          >[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await annotationServiceListsUsersBookmarks({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: annotationServiceListsUsersBookmarksInfiniteQueryKey(options),
    },
  );
};

export const annotationServiceListMaterialNotesQueryKey = (
  options: OptionsLegacyParser<AnnotationServiceListMaterialNotesData>,
) => [createQueryKey("annotationServiceListMaterialNotes", options)];

export const annotationServiceListMaterialNotesOptions = (
  options: OptionsLegacyParser<AnnotationServiceListMaterialNotesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await annotationServiceListMaterialNotes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: annotationServiceListMaterialNotesQueryKey(options),
  });
};

export const annotationServiceListMaterialNotesInfiniteQueryKey = (
  options: OptionsLegacyParser<AnnotationServiceListMaterialNotesData>,
): QueryKey<OptionsLegacyParser<AnnotationServiceListMaterialNotesData>> => [
  createQueryKey("annotationServiceListMaterialNotes", options, true),
];

export const annotationServiceListMaterialNotesInfiniteOptions = (
  options: OptionsLegacyParser<AnnotationServiceListMaterialNotesData>,
) => {
  return infiniteQueryOptions<
    AnnotationServiceListMaterialNotesResponse,
    AxiosError<AnnotationServiceListMaterialNotesError>,
    InfiniteData<AnnotationServiceListMaterialNotesResponse>,
    QueryKey<OptionsLegacyParser<AnnotationServiceListMaterialNotesData>>,
    | string
    | Pick<
        QueryKey<
          OptionsLegacyParser<AnnotationServiceListMaterialNotesData>
        >[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<
            OptionsLegacyParser<AnnotationServiceListMaterialNotesData>
          >[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await annotationServiceListMaterialNotes({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: annotationServiceListMaterialNotesInfiniteQueryKey(options),
    },
  );
};

export const annotationServiceGetNoteByIdQueryKey = (
  options: OptionsLegacyParser<AnnotationServiceGetNoteByIdData>,
) => [createQueryKey("annotationServiceGetNoteById", options)];

export const annotationServiceGetNoteByIdOptions = (
  options: OptionsLegacyParser<AnnotationServiceGetNoteByIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await annotationServiceGetNoteById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: annotationServiceGetNoteByIdQueryKey(options),
  });
};

export const annotationServiceDeleteNoteMutation = (
  options?: Partial<OptionsLegacyParser<AnnotationServiceDeleteNoteData>>,
) => {
  const mutationOptions: UseMutationOptions<
    AnnotationServiceDeleteNoteResponse,
    AxiosError<AnnotationServiceDeleteNoteError>,
    OptionsLegacyParser<AnnotationServiceDeleteNoteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await annotationServiceDeleteNote({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const annotationServiceListsUsersNotesQueryKey = (
  options: OptionsLegacyParser<AnnotationServiceListsUsersNotesData>,
) => [createQueryKey("annotationServiceListsUsersNotes", options)];

export const annotationServiceListsUsersNotesOptions = (
  options: OptionsLegacyParser<AnnotationServiceListsUsersNotesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await annotationServiceListsUsersNotes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: annotationServiceListsUsersNotesQueryKey(options),
  });
};

export const annotationServiceListsUsersNotesInfiniteQueryKey = (
  options: OptionsLegacyParser<AnnotationServiceListsUsersNotesData>,
): QueryKey<OptionsLegacyParser<AnnotationServiceListsUsersNotesData>> => [
  createQueryKey("annotationServiceListsUsersNotes", options, true),
];

export const annotationServiceListsUsersNotesInfiniteOptions = (
  options: OptionsLegacyParser<AnnotationServiceListsUsersNotesData>,
) => {
  return infiniteQueryOptions<
    AnnotationServiceListsUsersNotesResponse,
    AxiosError<AnnotationServiceListsUsersNotesError>,
    InfiniteData<AnnotationServiceListsUsersNotesResponse>,
    QueryKey<OptionsLegacyParser<AnnotationServiceListsUsersNotesData>>,
    | string
    | Pick<
        QueryKey<OptionsLegacyParser<AnnotationServiceListsUsersNotesData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<
            OptionsLegacyParser<AnnotationServiceListsUsersNotesData>
          >[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await annotationServiceListsUsersNotes({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: annotationServiceListsUsersNotesInfiniteQueryKey(options),
    },
  );
};
