// This file is auto-generated by @hey-api/openapi-ts

import type { OptionsLegacyParser } from "@hey-api/client-axios";
import {
  type UseMutationOptions,
  queryOptions,
  infiniteQueryOptions,
  type InfiniteData,
} from "@tanstack/react-query";
import type {
  PaymentsServiceUpdatePaymentStatusData,
  PaymentsServiceUpdatePaymentStatusError,
  PaymentsServiceUpdatePaymentStatusResponse,
  PaymentsServiceListAllPaymentsData,
  PaymentsServiceListAllPaymentsError,
  PaymentsServiceListAllPaymentsResponse,
  PaymentsServiceListPaymentsData,
  PaymentsServiceListPaymentsError,
  PaymentsServiceListPaymentsResponse,
  PaymentsServiceInitiatePaymentsData,
  PaymentsServiceInitiatePaymentsError,
  PaymentsServiceInitiatePaymentsResponse,
  PaymentsServiceGetPaymentByIdData,
  PaymentsServicePawaPayWebhookData,
  PaymentsServicePawaPayWebhookError,
  PaymentsServicePawaPayWebhookResponse,
  PaymentsServiceStripeWebhookData,
  PaymentsServiceStripeWebhookError,
  PaymentsServiceStripeWebhookResponse,
} from "../types.gen";
import type { AxiosError } from "axios";
import {
  paymentsServiceUpdatePaymentStatus,
  client,
  paymentsServiceListAllPayments,
  paymentsServiceListPayments,
  paymentsServiceInitiatePayments,
  paymentsServiceGetPaymentById,
  paymentsServicePawaPayWebhook,
  paymentsServiceStripeWebhook,
} from "../sdk.gen";

export const paymentsServiceUpdatePaymentStatusMutation = (
  options?: Partial<
    OptionsLegacyParser<PaymentsServiceUpdatePaymentStatusData>
  >,
) => {
  const mutationOptions: UseMutationOptions<
    PaymentsServiceUpdatePaymentStatusResponse,
    AxiosError<PaymentsServiceUpdatePaymentStatusError>,
    OptionsLegacyParser<PaymentsServiceUpdatePaymentStatusData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await paymentsServiceUpdatePaymentStatus({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};

export const paymentsServiceListAllPaymentsQueryKey = (
  options: OptionsLegacyParser<PaymentsServiceListAllPaymentsData>,
) => [createQueryKey("paymentsServiceListAllPayments", options)];

export const paymentsServiceListAllPaymentsOptions = (
  options: OptionsLegacyParser<PaymentsServiceListAllPaymentsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await paymentsServiceListAllPayments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: paymentsServiceListAllPaymentsQueryKey(options),
  });
};

const createInfiniteParams = <
  K extends Pick<
    QueryKey<OptionsLegacyParser>[0],
    "body" | "headers" | "path" | "query"
  >,
>(
  queryKey: QueryKey<OptionsLegacyParser>,
  page: K,
) => {
  const params = queryKey[0];
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...queryKey[0].path,
      ...page.path,
    };
  }
  if (page.query) {
    params.query = {
      ...queryKey[0].query,
      ...page.query,
    };
  }
  return params as unknown as typeof page;
};

export const paymentsServiceListAllPaymentsInfiniteQueryKey = (
  options: OptionsLegacyParser<PaymentsServiceListAllPaymentsData>,
): QueryKey<OptionsLegacyParser<PaymentsServiceListAllPaymentsData>> => [
  createQueryKey("paymentsServiceListAllPayments", options, true),
];

export const paymentsServiceListAllPaymentsInfiniteOptions = (
  options: OptionsLegacyParser<PaymentsServiceListAllPaymentsData>,
) => {
  return infiniteQueryOptions<
    PaymentsServiceListAllPaymentsResponse,
    AxiosError<PaymentsServiceListAllPaymentsError>,
    InfiniteData<PaymentsServiceListAllPaymentsResponse>,
    QueryKey<OptionsLegacyParser<PaymentsServiceListAllPaymentsData>>,
    | string
    | Pick<
        QueryKey<OptionsLegacyParser<PaymentsServiceListAllPaymentsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<OptionsLegacyParser<PaymentsServiceListAllPaymentsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await paymentsServiceListAllPayments({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: paymentsServiceListAllPaymentsInfiniteQueryKey(options),
    },
  );
};

export const paymentsServiceListPaymentsQueryKey = (
  options: OptionsLegacyParser<PaymentsServiceListPaymentsData>,
) => [createQueryKey("paymentsServiceListPayments", options)];

export const paymentsServiceListPaymentsOptions = (
  options: OptionsLegacyParser<PaymentsServiceListPaymentsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await paymentsServiceListPayments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: paymentsServiceListPaymentsQueryKey(options),
  });
};

export const paymentsServiceListPaymentsInfiniteQueryKey = (
  options: OptionsLegacyParser<PaymentsServiceListPaymentsData>,
): QueryKey<OptionsLegacyParser<PaymentsServiceListPaymentsData>> => [
  createQueryKey("paymentsServiceListPayments", options, true),
];

export const paymentsServiceListPaymentsInfiniteOptions = (
  options: OptionsLegacyParser<PaymentsServiceListPaymentsData>,
) => {
  return infiniteQueryOptions<
    PaymentsServiceListPaymentsResponse,
    AxiosError<PaymentsServiceListPaymentsError>,
    InfiniteData<PaymentsServiceListPaymentsResponse>,
    QueryKey<OptionsLegacyParser<PaymentsServiceListPaymentsData>>,
    | string
    | Pick<
        QueryKey<OptionsLegacyParser<PaymentsServiceListPaymentsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<OptionsLegacyParser<PaymentsServiceListPaymentsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await paymentsServiceListPayments({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: paymentsServiceListPaymentsInfiniteQueryKey(options),
    },
  );
};

export const paymentsServiceInitiatePaymentsQueryKey = (
  options: OptionsLegacyParser<PaymentsServiceInitiatePaymentsData>,
) => [createQueryKey("paymentsServiceInitiatePayments", options)];

export const paymentsServiceInitiatePaymentsOptions = (
  options: OptionsLegacyParser<PaymentsServiceInitiatePaymentsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await paymentsServiceInitiatePayments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: paymentsServiceInitiatePaymentsQueryKey(options),
  });
};

export const paymentsServiceInitiatePaymentsMutation = (
  options?: Partial<OptionsLegacyParser<PaymentsServiceInitiatePaymentsData>>,
) => {
  const mutationOptions: UseMutationOptions<
    PaymentsServiceInitiatePaymentsResponse,
    AxiosError<PaymentsServiceInitiatePaymentsError>,
    OptionsLegacyParser<PaymentsServiceInitiatePaymentsData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await paymentsServiceInitiatePayments({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const paymentsServiceGetPaymentByIdQueryKey = (
  options: OptionsLegacyParser<PaymentsServiceGetPaymentByIdData>,
) => [createQueryKey("paymentsServiceGetPaymentById", options)];

export const paymentsServiceGetPaymentByIdOptions = (
  options: OptionsLegacyParser<PaymentsServiceGetPaymentByIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await paymentsServiceGetPaymentById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: paymentsServiceGetPaymentByIdQueryKey(options),
  });
};

export const paymentsServicePawaPayWebhookQueryKey = (
  options: OptionsLegacyParser<PaymentsServicePawaPayWebhookData>,
) => [createQueryKey("paymentsServicePawaPayWebhook", options)];

export const paymentsServicePawaPayWebhookOptions = (
  options: OptionsLegacyParser<PaymentsServicePawaPayWebhookData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await paymentsServicePawaPayWebhook({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: paymentsServicePawaPayWebhookQueryKey(options),
  });
};

export const paymentsServicePawaPayWebhookMutation = (
  options?: Partial<OptionsLegacyParser<PaymentsServicePawaPayWebhookData>>,
) => {
  const mutationOptions: UseMutationOptions<
    PaymentsServicePawaPayWebhookResponse,
    AxiosError<PaymentsServicePawaPayWebhookError>,
    OptionsLegacyParser<PaymentsServicePawaPayWebhookData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await paymentsServicePawaPayWebhook({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const paymentsServiceStripeWebhookQueryKey = (
  options: OptionsLegacyParser<PaymentsServiceStripeWebhookData>,
) => [createQueryKey("paymentsServiceStripeWebhook", options)];

export const paymentsServiceStripeWebhookOptions = (
  options: OptionsLegacyParser<PaymentsServiceStripeWebhookData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await paymentsServiceStripeWebhook({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: paymentsServiceStripeWebhookQueryKey(options),
  });
};

export const paymentsServiceStripeWebhookMutation = (
  options?: Partial<OptionsLegacyParser<PaymentsServiceStripeWebhookData>>,
) => {
  const mutationOptions: UseMutationOptions<
    PaymentsServiceStripeWebhookResponse,
    AxiosError<PaymentsServiceStripeWebhookError>,
    OptionsLegacyParser<PaymentsServiceStripeWebhookData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await paymentsServiceStripeWebhook({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
