// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-axios";
import type {
  DocumentsMaterialsServiceCreateDocumentV2Data,
  DocumentsMaterialsServiceCreateDocumentV2Error,
  DocumentsMaterialsServiceCreateDocumentV2Response,
  DocumentsMaterialsServiceCreateCategoryData,
  DocumentsMaterialsServiceCreateCategoryError,
  DocumentsMaterialsServiceCreateCategoryResponse,
  DocumentsMaterialsServiceUpdateCategoryData,
  DocumentsMaterialsServiceUpdateCategoryError,
  DocumentsMaterialsServiceUpdateCategoryResponse,
  DocumentsMaterialsServiceDeleteMaterialByIdData,
  DocumentsMaterialsServiceDeleteMaterialByIdError,
  DocumentsMaterialsServiceDeleteMaterialByIdResponse,
  DocumentsMaterialsServiceListCategoriesData,
  DocumentsMaterialsServiceListCategoriesError,
  DocumentsMaterialsServiceListCategoriesResponse,
  DocumentsMaterialsServiceGetDocumentListsUnderCatalogueData,
  DocumentsMaterialsServiceGetDocumentListsUnderCatalogueError,
  DocumentsMaterialsServiceGetDocumentListsUnderCatalogueResponse,
  DocumentsMaterialsServiceListPublishedDocumentsData,
  DocumentsMaterialsServiceListPublishedDocumentsError,
  DocumentsMaterialsServiceListPublishedDocumentsResponse,
  DocumentsMaterialsServiceListPublishedDocumentTypesData,
  DocumentsMaterialsServiceListPublishedDocumentTypesError,
  DocumentsMaterialsServiceListPublishedDocumentTypesResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Creates a new document.
 */
export const documentsMaterialsServiceCreateDocumentV2 = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    DocumentsMaterialsServiceCreateDocumentV2Data,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    DocumentsMaterialsServiceCreateDocumentV2Response,
    DocumentsMaterialsServiceCreateDocumentV2Error,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/document",
  });
};

/**
 * Creates a new category. (use 'user_id' of the user performing this action)
 */
export const documentsMaterialsServiceCreateCategory = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    DocumentsMaterialsServiceCreateCategoryData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    DocumentsMaterialsServiceCreateCategoryResponse,
    DocumentsMaterialsServiceCreateCategoryError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/document/{category.userId}/category",
  });
};

/**
 * Updates an existing category by its ID. (use 'user_id' of the user
 * performing this action)
 */
export const documentsMaterialsServiceUpdateCategory = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    DocumentsMaterialsServiceUpdateCategoryData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).patch<
    DocumentsMaterialsServiceUpdateCategoryResponse,
    DocumentsMaterialsServiceUpdateCategoryError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/document/{category.userId}/category",
  });
};

/**
 * Deletes a material by its unique ID.
 */
export const documentsMaterialsServiceDeleteMaterialById = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    DocumentsMaterialsServiceDeleteMaterialByIdData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).delete<
    DocumentsMaterialsServiceDeleteMaterialByIdResponse,
    DocumentsMaterialsServiceDeleteMaterialByIdError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/document/{materialId}/material",
  });
};

/**
 * Retrieves a list of available catalogues (categories) with optional filters
 * and pagination.
 */
export const documentsMaterialsServiceListCategories = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    DocumentsMaterialsServiceListCategoriesData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    DocumentsMaterialsServiceListCategoriesResponse,
    DocumentsMaterialsServiceListCategoriesError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/published/{userId}/catalogues",
  });
};

/**
 * Retrieves documents lists under a particular catalogue with pagination,
 * filtering, sorting and search. (use 'user_id' of the user performing this
 * action)
 */
export const documentsMaterialsServiceGetDocumentListsUnderCatalogue = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    DocumentsMaterialsServiceGetDocumentListsUnderCatalogueData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    DocumentsMaterialsServiceGetDocumentListsUnderCatalogueResponse,
    DocumentsMaterialsServiceGetDocumentListsUnderCatalogueError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/published/{userId}/catalogues/{catalogueId}/documents",
  });
};

/**
 * Lists all published documents with optional pagination and filtering by
 * category and/or document type
 */
export const documentsMaterialsServiceListPublishedDocuments = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    DocumentsMaterialsServiceListPublishedDocumentsData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    DocumentsMaterialsServiceListPublishedDocumentsResponse,
    DocumentsMaterialsServiceListPublishedDocumentsError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/published/{userId}/documents",
  });
};

/**
 * Lists all unique document types from published documents with optional
 * pagination (make sure to include the 'user_id' of the user performing this
 * action)
 */
export const documentsMaterialsServiceListPublishedDocumentTypes = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    DocumentsMaterialsServiceListPublishedDocumentTypesData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    DocumentsMaterialsServiceListPublishedDocumentTypesResponse,
    DocumentsMaterialsServiceListPublishedDocumentTypesError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/published/{userId}/types",
  });
};
