// This file is auto-generated by @hey-api/openapi-ts

/**
 * Request to create a new category.
 */
export type DocumentsMaterialsServiceCreateCategoryBody = {
  category?: {
    /**
     * Unique identifier of the category.
     */
    categoryId?: string;
    /**
     * Titles of the category in different languages.
     */
    titles?: v2Titles;
    /**
     * Labels assigned to the category.
     */
    labels?: Array<string>;
    /**
     * Multilingual description of the category.
     */
    description?: v2DescriptionJSON;
    /**
     * number of documents linked to this specific category.
     */
    documentCount?: number;
    /**
     * Timestamp of category creation.
     */
    createdAt?: string;
    /**
     * Timestamp of last update.
     */
    updatedAt?: string;
  };
};

/**
 * Request to update an existing category.
 */
export type DocumentsMaterialsServiceUpdateCategoryBody = {
  category?: {
    /**
     * Unique identifier of the category.
     */
    categoryId?: string;
    /**
     * Titles of the category in different languages.
     */
    titles?: v2Titles;
    /**
     * Labels assigned to the category.
     */
    labels?: Array<string>;
    /**
     * Multilingual description of the category.
     */
    description?: v2DescriptionJSON;
    /**
     * number of documents linked to this specific category.
     */
    documentCount?: number;
    /**
     * Timestamp of category creation.
     */
    createdAt?: string;
    /**
     * Timestamp of last update.
     */
    updatedAt?: string;
  };
};

export type protobufAny = {
  [key: string]: unknown;
};

export type rpcStatus = {
  code?: number;
  message?: string;
  details?: Array<protobufAny>;
};

/**
 * * A full date, with non-zero year, month, and day values
 * * A month and day value, with a zero year, such as an anniversary
 * * A year on its own, with zero month and day values
 * * A year and month value, with a zero day, such as a credit card expiration
 * date
 *
 * Related types are [google.type.TimeOfDay][google.type.TimeOfDay] and
 * `google.protobuf.Timestamp`.
 */
export type typeDate = {
  /**
   * Year of the date. Must be from 1 to 9999, or 0 to specify a date without
   * a year.
   */
  year?: number;
  /**
   * Month of a year. Must be from 1 to 12, or 0 to specify a year without a
   * month and day.
   */
  month?: number;
  /**
   * Day of a month. Must be from 1 to 31 and valid for the year and month, or 0
   * to specify a year by itself or a year and month where the day isn't
   * significant.
   */
  day?: number;
};

/**
 * Represents a breadcrumb for navigating through documents.
 */
export type v2Breadcrumb = {
  /**
   * ID of the parent document.
   */
  parentId?: string;
  /**
   * Reference label.
   */
  ref?: string;
  /**
   * Material ID in the breadcrumb path.
   */
  materialId?: string;
};

export type v2Category = {
  /**
   * Unique identifier of the category.
   */
  categoryId?: string;
  /**
   * Titles of the category in different languages.
   */
  titles?: v2Titles;
  /**
   * Labels assigned to the category.
   */
  labels?: Array<string>;
  /**
   * Multilingual description of the category.
   */
  description?: v2DescriptionJSON;
  /**
   * ID of the user who created the category.
   */
  userId?: string;
  /**
   * number of documents linked to this specific category.
   */
  documentCount?: number;
  /**
   * Timestamp of category creation.
   */
  createdAt?: string;
  /**
   * Timestamp of last update.
   */
  updatedAt?: string;
};

/**
 * Response after creating a new category.
 */
export type v2CreateCategoryResponse = {
  category?: v2Category;
};

/**
 * Requests for documents creation.
 */
export type v2CreateDocumentRequest = {
  document?: v2Document;
};

/**
 * Response after creating a new document.
 */
export type v2CreateDocumentResponse = {
  document?: v2Document;
};

/**
 * Response after deleting material by id.
 */
export type v2DeleteMaterialResponse = {
  materialId?: string;
  message?: string;
};

/**
 * Multilingual description of the category.
 */
export type v2DescriptionJSON = {
  en?: string;
  fr?: string;
};

export type v2Document = {
  /**
   * Unique identifier of the document.
   */
  id?: string;
  /**
   * Unique reference code for the document.
   */
  ref?: string;
  /**
   * Suffix number for the document (internal use).
   */
  suffixDocumentNumber?: string;
  /**
   * User-friendly document number.
   */
  documentNumber?: string;
  /**
   * ID of the root material associated with the document.
   */
  rootMaterialId?: string;
  /**
   * ID of the user who created the document.
   */
  userId?: string;
  /**
   * Optional message related to the document.
   */
  message?: string;
  /**
   * Title of the document.
   */
  title?: string;
  /**
   * Indicates if the document content has been extracted.
   */
  isExtracted?: boolean;
  /**
   * Header text of the document.
   */
  header?: string;
  /**
   * Revision number of the document.
   */
  revisionId?: number;
  /**
   * Footer text of the document.
   */
  footer?: string;
  /**
   * ID of the associated document type.
   */
  documentTypeId?: string;
  /**
   * Reference to the associated document type.
   */
  documentType?: v2DocumentType;
  /**
   * Number of materials linked to the document.
   */
  materialCount?: string;
  /**
   * Language of the document.
   */
  language?: string;
  /**
   * List of category IDs linked to the document.
   */
  categoryIds?: Array<string>;
  /**
   * References to categories linked to the document.
   */
  categories?: Array<v2Category>;
  /**
   * Current status of the document.
   */
  status?: string;
  /**
   * Version of the document.
   */
  version?: string;
  /**
   * List of owner notes.
   */
  ownersNotes?: Array<v2OwnerNote>;
  /**
   * Date the document was issued.
   */
  issueDate?: string;
  /**
   * Sources related to the document.
   */
  source?: Array<string>;
  /**
   * Raw text content of the document.
   */
  rawText?: string;
  jsonHeader?: string;
  jsonFooter?: string;
  /**
   * Timestamp of document creation.
   */
  createdAt?: string;
  /**
   * Timestamp of last update.
   */
  updatedAt?: string;
  /**
   * List of child materials linked to the document.
   */
  children?: Array<v2Material>;
};

export type v2DocumentType = {
  /**
   * Unique identifier of the document type.
   */
  id?: string;
  /**
   * List of years with document counts.
   */
  years?: Array<v2Year>;
  /**
   * URL of the image representing the document type.
   */
  imageUrl?: string;
  /**
   * Titles of the document type in different languages.
   */
  titles?: v2Titles;
  /**
   * Caption for the document type.
   */
  caption?: string;
  /**
   * ID of the user who created the document type.
   */
  userId?: string;
  /**
   * Count of documents under this document type.
   */
  documentCount?: string;
  /**
   * Timestamp of document type creation.
   */
  createdAt?: string;
  /**
   * Timestamp of last update.
   */
  updatedAt?: string;
};

export type v2ListCategoriesResponse = {
  statistics?: v2Statistics;
  categories?: Array<v2Category>;
};

/**
 * Response message for retrieving published documents.
 */
export type v2ListPublishedDocumentsResponse = {
  statistics?: v2Statistics;
  documents?: Array<v2PublishedDocument>;
};

export type v2ListPublishedDocumentTypesResponse = {
  statistics?: v2Statistics;
  documentTypes?: Array<v2DocumentType>;
};

/**
 * Main Material resource definition.
 */
export type v2Material = {
  /**
   * Unique identifier for the material.
   */
  id?: string;
  /**
   * Title of the material.
   */
  title?: string;
  /**
   * Reference identifier for the material.
   */
  ref?: string;
  /**
   * Type of the material (e.g., root, division, article).
   */
  materialType?: string;
  /**
   * Status of the material (e.g., inProgress, validated).
   */
  status?: string;
  /**
   * Revision number of the material.
   */
  revisionId?: number;
  /**
   * Human-readable material number.
   */
  materialNumber?: string;
  /**
   * Suffix for the material number.
   */
  suffixMaterialNumber?: number;
  /**
   * Position of the material in its parent context.
   */
  position?: string;
  /**
   * Tags or labels associated with the material.
   */
  labels?: Array<string>;
  /**
   * ID of the document the material is linked to.
   */
  documentId?: string;
  /**
   * Title of the linked document.
   */
  documentTitle?: string;
  /**
   * Parent material ID.
   */
  parentId?: string;
  /**
   * ID of the user who created the material.
   */
  userId?: string;
  /**
   * Content of the material.
   */
  body?: string;
  /**
   * JSON content of the material.
   */
  jsonBody?: string;
  /**
   * Breadcrumb trail for navigation.
   */
  breadcrumbs?: Array<v2Breadcrumb>;
  /**
   * Sub-materials (children) under this material.
   */
  children?: Array<v2Material>;
  /**
   * Timestamp of creation.
   */
  createdAt?: string;
  /**
   * Timestamp of last update.
   */
  updatedAt?: string;
};

export type v2OwnerNote = {
  /**
   * Message from the owner.
   */
  msg?: string;
  /**
   * Name of the owner.
   */
  name?: string;
  /**
   * Timestamp of the note.
   */
  timestamp?: string;
};

export type v2PublishedDocument = {
  documentId?: string;
  ref?: string;
  documentNumber?: string;
  documentType?: v2DocumentType;
  materialCount?: string;
  documentSuffixNumber?: string;
  language?: string;
  jsonHeader?: string;
  jsonFooter?: string;
  title?: string;
  issueDate?: string;
  updatedAt?: string;
  createdAt?: string;
  userId?: string;
  status?: string;
  documentTypeId?: string;
  rootMaterialId?: string;
  /**
   * Categories this document was published with.
   */
  categories?: Array<v2Category>;
  ownersNotes?: Array<v2OwnerNote>;
};

/**
 * - SORT_BY_TITLE_EN: Sort by English title
 * - SORT_BY_TITLE_FR: Sort by French title
 *
 * Sort by issue date
 * SORT_BY_ISSUE_DATE = 3;
 * Sort by updated timestamp
 * SORT_BY_UPDATED_AT = 4;
 */
export type v2SortBy =
  | "SORT_BY_UNSPECIFIED"
  | "SORT_BY_TITLE_EN"
  | "SORT_BY_TITLE_FR";

/**
 * - ASC: Sort in ascending order (A → Z)
 * - DESC: Sort in descending order (Z → A)
 */
export type v2SortOrder = "SORT_ORDER_UNSPECIFIED" | "ASC" | "DESC";

/**
 * Pagination metadata for lists.
 */
export type v2Statistics = {
  currentPage?: string;
  pageCount?: string;
  totalItems?: string;
};

/**
 * Multilingual titles for the category.
 */
export type v2Titles = {
  en?: string;
  fr?: string;
};

/**
 * Response after updating a category.
 */
export type v2UpdateCategoryResponse = {
  category?: v2Category;
};

export type v2Year = {
  /**
   * Year associated with documents.
   */
  year?: number;
  /**
   * Count of documents for the year.
   */
  documentCount?: number;
};

export type DocumentsMaterialsServiceCreateDocumentV2Data = {
  /**
   * Requests for documents creation.
   */
  body: v2CreateDocumentRequest;
};

export type DocumentsMaterialsServiceCreateDocumentV2Response =
  v2CreateDocumentResponse;

export type DocumentsMaterialsServiceCreateDocumentV2Error = rpcStatus;

export type DocumentsMaterialsServiceCreateCategoryData = {
  body: DocumentsMaterialsServiceCreateCategoryBody;
  path: {
    /**
     * ID of the user who created the category.
     */
    "category.userId": string;
  };
};

export type DocumentsMaterialsServiceCreateCategoryResponse =
  v2CreateCategoryResponse;

export type DocumentsMaterialsServiceCreateCategoryError = rpcStatus;

export type DocumentsMaterialsServiceUpdateCategoryData = {
  body: DocumentsMaterialsServiceUpdateCategoryBody;
  path: {
    /**
     * ID of the user who created the category.
     */
    "category.userId": string;
  };
};

export type DocumentsMaterialsServiceUpdateCategoryResponse =
  v2UpdateCategoryResponse;

export type DocumentsMaterialsServiceUpdateCategoryError = rpcStatus;

export type DocumentsMaterialsServiceDeleteMaterialByIdData = {
  path: {
    /**
     * material to be deleted.
     */
    materialId: string;
  };
  query?: {
    /**
     * 'user_id' that's performing this delete operation.
     */
    userId?: string;
  };
};

export type DocumentsMaterialsServiceDeleteMaterialByIdResponse =
  v2DeleteMaterialResponse;

export type DocumentsMaterialsServiceDeleteMaterialByIdError = rpcStatus;

export type DocumentsMaterialsServiceListCategoriesData = {
  path: {
    /**
     * 'user_id' trying to perform this list operation
     */
    userId: string;
  };
  query?: {
    /**
     * 'catalogue_id' to fetch all the documents lists (renamed from catalogue_id
     * for clarity)
     */
    catalogueId?: string;
    /**
     * 'document_type_id' to filter documents by document type
     */
    documentTypeId?: string;
    /**
     * Page number for pagination
     */
    page?: string;
    /**
     * Number of items per page
     */
    pageSize?: string;
    /**
     * Optional search keyword for filtering
     */
    searchKey?: string;
    /**
     * sort by determines which field to sort by in the category response
     *
     * - SORT_BY_TITLE_EN: Sort by English title
     * - SORT_BY_TITLE_FR: Sort by French title
     *
     * Sort by issue date
     * SORT_BY_ISSUE_DATE = 3;
     * Sort by updated timestamp
     * SORT_BY_UPDATED_AT = 4;
     */
    sortBy?: "SORT_BY_UNSPECIFIED" | "SORT_BY_TITLE_EN" | "SORT_BY_TITLE_FR";
    /**
     * Sort order (ascending or descending)
     *
     * - ASC: Sort in ascending order (A → Z)
     * - DESC: Sort in descending order (Z → A)
     */
    sortOrder?: "SORT_ORDER_UNSPECIFIED" | "ASC" | "DESC";
  };
};

export type DocumentsMaterialsServiceListCategoriesResponse =
  v2ListCategoriesResponse;

export type DocumentsMaterialsServiceListCategoriesError = rpcStatus;

export type DocumentsMaterialsServiceGetDocumentListsUnderCatalogueData = {
  path: {
    /**
     * 'catalogue_id' to fetch all the documents lists (renamed from catalogue_id
     * for clarity)
     */
    catalogueId: string;
    /**
     * 'user_id' trying to perform this list operation
     */
    userId: string;
  };
  query?: {
    /**
     * 'document_type_id' to filter documents by document type
     */
    documentTypeId?: string;
    /**
     * Page number for pagination
     */
    page?: string;
    /**
     * Number of items per page
     */
    pageSize?: string;
    /**
     * Optional search keyword for filtering
     */
    searchKey?: string;
    /**
     * sort by determines which field to sort by in the category response
     *
     * - SORT_BY_TITLE_EN: Sort by English title
     * - SORT_BY_TITLE_FR: Sort by French title
     *
     * Sort by issue date
     * SORT_BY_ISSUE_DATE = 3;
     * Sort by updated timestamp
     * SORT_BY_UPDATED_AT = 4;
     */
    sortBy?: "SORT_BY_UNSPECIFIED" | "SORT_BY_TITLE_EN" | "SORT_BY_TITLE_FR";
    /**
     * Sort order (ascending or descending)
     *
     * - ASC: Sort in ascending order (A → Z)
     * - DESC: Sort in descending order (Z → A)
     */
    sortOrder?: "SORT_ORDER_UNSPECIFIED" | "ASC" | "DESC";
  };
};

export type DocumentsMaterialsServiceGetDocumentListsUnderCatalogueResponse =
  v2ListPublishedDocumentsResponse;

export type DocumentsMaterialsServiceGetDocumentListsUnderCatalogueError =
  rpcStatus;

export type DocumentsMaterialsServiceListPublishedDocumentsData = {
  path: {
    /**
     * 'user_id' trying to perform this list operation
     */
    userId: string;
  };
  query?: {
    /**
     * 'catalogue_id' to fetch all the documents lists (renamed from catalogue_id
     * for clarity)
     */
    catalogueId?: string;
    /**
     * 'document_type_id' to filter documents by document type
     */
    documentTypeId?: string;
    /**
     * Day of a month. Must be from 1 to 31 and valid for the year and month, or 0
     * to specify a year by itself or a year and month where the day isn't
     * significant.
     */
    "issueDateFrom.day"?: number;
    /**
     * Month of a year. Must be from 1 to 12, or 0 to specify a year without a
     * month and day.
     */
    "issueDateFrom.month"?: number;
    /**
     * Year of the date. Must be from 1 to 9999, or 0 to specify a date without
     * a year.
     */
    "issueDateFrom.year"?: number;
    /**
     * Day of a month. Must be from 1 to 31 and valid for the year and month, or 0
     * to specify a year by itself or a year and month where the day isn't
     * significant.
     */
    "issueDateTo.day"?: number;
    /**
     * Month of a year. Must be from 1 to 12, or 0 to specify a year without a
     * month and day.
     */
    "issueDateTo.month"?: number;
    /**
     * Year of the date. Must be from 1 to 9999, or 0 to specify a date without
     * a year.
     */
    "issueDateTo.year"?: number;
    /**
     * Page number for pagination
     */
    page?: string;
    /**
     * Number of items per page
     */
    pageSize?: string;
    /**
     * Optional search keyword for filtering
     */
    searchKey?: string;
    /**
     * sort by determines which field to sort by in the category response
     *
     * - SORT_BY_TITLE_EN: Sort by English title
     * - SORT_BY_TITLE_FR: Sort by French title
     *
     * Sort by issue date
     * SORT_BY_ISSUE_DATE = 3;
     * Sort by updated timestamp
     * SORT_BY_UPDATED_AT = 4;
     */
    sortBy?: "SORT_BY_UNSPECIFIED" | "SORT_BY_TITLE_EN" | "SORT_BY_TITLE_FR";
    /**
     * Sort order (ascending or descending)
     *
     * - ASC: Sort in ascending order (A → Z)
     * - DESC: Sort in descending order (Z → A)
     */
    sortOrder?: "SORT_ORDER_UNSPECIFIED" | "ASC" | "DESC";
  };
};

export type DocumentsMaterialsServiceListPublishedDocumentsResponse =
  v2ListPublishedDocumentsResponse;

export type DocumentsMaterialsServiceListPublishedDocumentsError = rpcStatus;

export type DocumentsMaterialsServiceListPublishedDocumentTypesData = {
  path: {
    /**
     * 'user_id' trying to perform this list operation
     */
    userId: string;
  };
  query?: {
    /**
     * Page number for pagination
     */
    page?: string;
    /**
     * Number of items per page
     */
    pageSize?: string;
  };
};

export type DocumentsMaterialsServiceListPublishedDocumentTypesResponse =
  v2ListPublishedDocumentTypesResponse;

export type DocumentsMaterialsServiceListPublishedDocumentTypesError =
  rpcStatus;
