// This file is auto-generated by @hey-api/openapi-ts

import type { OptionsLegacyParser } from "@hey-api/client-axios";
import {
  queryOptions,
  type UseMutationOptions,
  infiniteQueryOptions,
  type InfiniteData,
} from "@tanstack/react-query";
import type {
  DocumentsMaterialsServiceCreateDocumentV2Data,
  DocumentsMaterialsServiceCreateDocumentV2Error,
  DocumentsMaterialsServiceCreateDocumentV2Response,
  DocumentsMaterialsServiceCreateCategoryData,
  DocumentsMaterialsServiceCreateCategoryError,
  DocumentsMaterialsServiceCreateCategoryResponse,
  DocumentsMaterialsServiceUpdateCategoryData,
  DocumentsMaterialsServiceUpdateCategoryError,
  DocumentsMaterialsServiceUpdateCategoryResponse,
  DocumentsMaterialsServiceDeleteMaterialByIdData,
  DocumentsMaterialsServiceDeleteMaterialByIdError,
  DocumentsMaterialsServiceDeleteMaterialByIdResponse,
  DocumentsMaterialsServiceListCategoriesData,
  DocumentsMaterialsServiceListCategoriesError,
  DocumentsMaterialsServiceListCategoriesResponse,
  DocumentsMaterialsServiceGetDocumentListsUnderCatalogueData,
  DocumentsMaterialsServiceGetDocumentListsUnderCatalogueError,
  DocumentsMaterialsServiceGetDocumentListsUnderCatalogueResponse,
  DocumentsMaterialsServiceListPublishedDocumentsData,
  DocumentsMaterialsServiceListPublishedDocumentsError,
  DocumentsMaterialsServiceListPublishedDocumentsResponse,
  DocumentsMaterialsServiceListPublishedDocumentTypesData,
  DocumentsMaterialsServiceListPublishedDocumentTypesError,
  DocumentsMaterialsServiceListPublishedDocumentTypesResponse,
} from "../types.gen";
import type { AxiosError } from "axios";
import {
  client,
  documentsMaterialsServiceCreateDocumentV2,
  documentsMaterialsServiceCreateCategory,
  documentsMaterialsServiceUpdateCategory,
  documentsMaterialsServiceDeleteMaterialById,
  documentsMaterialsServiceListCategories,
  documentsMaterialsServiceGetDocumentListsUnderCatalogue,
  documentsMaterialsServiceListPublishedDocuments,
  documentsMaterialsServiceListPublishedDocumentTypes,
} from "../sdk.gen";

type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};

export const documentsMaterialsServiceCreateDocumentV2QueryKey = (
  options: OptionsLegacyParser<DocumentsMaterialsServiceCreateDocumentV2Data>,
) => [createQueryKey("documentsMaterialsServiceCreateDocumentV2", options)];

export const documentsMaterialsServiceCreateDocumentV2Options = (
  options: OptionsLegacyParser<DocumentsMaterialsServiceCreateDocumentV2Data>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await documentsMaterialsServiceCreateDocumentV2({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: documentsMaterialsServiceCreateDocumentV2QueryKey(options),
  });
};

export const documentsMaterialsServiceCreateDocumentV2Mutation = (
  options?: Partial<
    OptionsLegacyParser<DocumentsMaterialsServiceCreateDocumentV2Data>
  >,
) => {
  const mutationOptions: UseMutationOptions<
    DocumentsMaterialsServiceCreateDocumentV2Response,
    AxiosError<DocumentsMaterialsServiceCreateDocumentV2Error>,
    OptionsLegacyParser<DocumentsMaterialsServiceCreateDocumentV2Data>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await documentsMaterialsServiceCreateDocumentV2({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const documentsMaterialsServiceCreateCategoryQueryKey = (
  options: OptionsLegacyParser<DocumentsMaterialsServiceCreateCategoryData>,
) => [createQueryKey("documentsMaterialsServiceCreateCategory", options)];

export const documentsMaterialsServiceCreateCategoryOptions = (
  options: OptionsLegacyParser<DocumentsMaterialsServiceCreateCategoryData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await documentsMaterialsServiceCreateCategory({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: documentsMaterialsServiceCreateCategoryQueryKey(options),
  });
};

export const documentsMaterialsServiceCreateCategoryMutation = (
  options?: Partial<
    OptionsLegacyParser<DocumentsMaterialsServiceCreateCategoryData>
  >,
) => {
  const mutationOptions: UseMutationOptions<
    DocumentsMaterialsServiceCreateCategoryResponse,
    AxiosError<DocumentsMaterialsServiceCreateCategoryError>,
    OptionsLegacyParser<DocumentsMaterialsServiceCreateCategoryData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await documentsMaterialsServiceCreateCategory({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const documentsMaterialsServiceUpdateCategoryMutation = (
  options?: Partial<
    OptionsLegacyParser<DocumentsMaterialsServiceUpdateCategoryData>
  >,
) => {
  const mutationOptions: UseMutationOptions<
    DocumentsMaterialsServiceUpdateCategoryResponse,
    AxiosError<DocumentsMaterialsServiceUpdateCategoryError>,
    OptionsLegacyParser<DocumentsMaterialsServiceUpdateCategoryData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await documentsMaterialsServiceUpdateCategory({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const documentsMaterialsServiceDeleteMaterialByIdMutation = (
  options?: Partial<
    OptionsLegacyParser<DocumentsMaterialsServiceDeleteMaterialByIdData>
  >,
) => {
  const mutationOptions: UseMutationOptions<
    DocumentsMaterialsServiceDeleteMaterialByIdResponse,
    AxiosError<DocumentsMaterialsServiceDeleteMaterialByIdError>,
    OptionsLegacyParser<DocumentsMaterialsServiceDeleteMaterialByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await documentsMaterialsServiceDeleteMaterialById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const documentsMaterialsServiceListCategoriesQueryKey = (
  options: OptionsLegacyParser<DocumentsMaterialsServiceListCategoriesData>,
) => [createQueryKey("documentsMaterialsServiceListCategories", options)];

export const documentsMaterialsServiceListCategoriesOptions = (
  options: OptionsLegacyParser<DocumentsMaterialsServiceListCategoriesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await documentsMaterialsServiceListCategories({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: documentsMaterialsServiceListCategoriesQueryKey(options),
  });
};

const createInfiniteParams = <
  K extends Pick<
    QueryKey<OptionsLegacyParser>[0],
    "body" | "headers" | "path" | "query"
  >,
>(
  queryKey: QueryKey<OptionsLegacyParser>,
  page: K,
) => {
  const params = queryKey[0];
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...queryKey[0].path,
      ...page.path,
    };
  }
  if (page.query) {
    params.query = {
      ...queryKey[0].query,
      ...page.query,
    };
  }
  return params as unknown as typeof page;
};

export const documentsMaterialsServiceListCategoriesInfiniteQueryKey = (
  options: OptionsLegacyParser<DocumentsMaterialsServiceListCategoriesData>,
): QueryKey<
  OptionsLegacyParser<DocumentsMaterialsServiceListCategoriesData>
> => [createQueryKey("documentsMaterialsServiceListCategories", options, true)];

export const documentsMaterialsServiceListCategoriesInfiniteOptions = (
  options: OptionsLegacyParser<DocumentsMaterialsServiceListCategoriesData>,
) => {
  return infiniteQueryOptions<
    DocumentsMaterialsServiceListCategoriesResponse,
    AxiosError<DocumentsMaterialsServiceListCategoriesError>,
    InfiniteData<DocumentsMaterialsServiceListCategoriesResponse>,
    QueryKey<OptionsLegacyParser<DocumentsMaterialsServiceListCategoriesData>>,
    | string
    | Pick<
        QueryKey<
          OptionsLegacyParser<DocumentsMaterialsServiceListCategoriesData>
        >[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<
            OptionsLegacyParser<DocumentsMaterialsServiceListCategoriesData>
          >[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await documentsMaterialsServiceListCategories({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey:
        documentsMaterialsServiceListCategoriesInfiniteQueryKey(options),
    },
  );
};

export const documentsMaterialsServiceGetDocumentListsUnderCatalogueQueryKey = (
  options: OptionsLegacyParser<DocumentsMaterialsServiceGetDocumentListsUnderCatalogueData>,
) => [
  createQueryKey(
    "documentsMaterialsServiceGetDocumentListsUnderCatalogue",
    options,
  ),
];

export const documentsMaterialsServiceGetDocumentListsUnderCatalogueOptions = (
  options: OptionsLegacyParser<DocumentsMaterialsServiceGetDocumentListsUnderCatalogueData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } =
        await documentsMaterialsServiceGetDocumentListsUnderCatalogue({
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        });
      return data;
    },
    queryKey:
      documentsMaterialsServiceGetDocumentListsUnderCatalogueQueryKey(options),
  });
};

export const documentsMaterialsServiceGetDocumentListsUnderCatalogueInfiniteQueryKey =
  (
    options: OptionsLegacyParser<DocumentsMaterialsServiceGetDocumentListsUnderCatalogueData>,
  ): QueryKey<
    OptionsLegacyParser<DocumentsMaterialsServiceGetDocumentListsUnderCatalogueData>
  > => [
    createQueryKey(
      "documentsMaterialsServiceGetDocumentListsUnderCatalogue",
      options,
      true,
    ),
  ];

export const documentsMaterialsServiceGetDocumentListsUnderCatalogueInfiniteOptions =
  (
    options: OptionsLegacyParser<DocumentsMaterialsServiceGetDocumentListsUnderCatalogueData>,
  ) => {
    return infiniteQueryOptions<
      DocumentsMaterialsServiceGetDocumentListsUnderCatalogueResponse,
      AxiosError<DocumentsMaterialsServiceGetDocumentListsUnderCatalogueError>,
      InfiniteData<DocumentsMaterialsServiceGetDocumentListsUnderCatalogueResponse>,
      QueryKey<
        OptionsLegacyParser<DocumentsMaterialsServiceGetDocumentListsUnderCatalogueData>
      >,
      | string
      | Pick<
          QueryKey<
            OptionsLegacyParser<DocumentsMaterialsServiceGetDocumentListsUnderCatalogueData>
          >[0],
          "body" | "headers" | "path" | "query"
        >
    >(
      // @ts-ignore
      {
        queryFn: async ({ pageParam, queryKey, signal }) => {
          // @ts-ignore
          const page: Pick<
            QueryKey<
              OptionsLegacyParser<DocumentsMaterialsServiceGetDocumentListsUnderCatalogueData>
            >[0],
            "body" | "headers" | "path" | "query"
          > =
            typeof pageParam === "object"
              ? pageParam
              : {
                  query: {
                    page: pageParam,
                  },
                };
          const params = createInfiniteParams(queryKey, page);
          const { data } =
            await documentsMaterialsServiceGetDocumentListsUnderCatalogue({
              ...options,
              ...params,
              signal,
              throwOnError: true,
            });
          return data;
        },
        queryKey:
          documentsMaterialsServiceGetDocumentListsUnderCatalogueInfiniteQueryKey(
            options,
          ),
      },
    );
  };

export const documentsMaterialsServiceListPublishedDocumentsQueryKey = (
  options: OptionsLegacyParser<DocumentsMaterialsServiceListPublishedDocumentsData>,
) => [
  createQueryKey("documentsMaterialsServiceListPublishedDocuments", options),
];

export const documentsMaterialsServiceListPublishedDocumentsOptions = (
  options: OptionsLegacyParser<DocumentsMaterialsServiceListPublishedDocumentsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await documentsMaterialsServiceListPublishedDocuments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: documentsMaterialsServiceListPublishedDocumentsQueryKey(options),
  });
};

export const documentsMaterialsServiceListPublishedDocumentsInfiniteQueryKey = (
  options: OptionsLegacyParser<DocumentsMaterialsServiceListPublishedDocumentsData>,
): QueryKey<
  OptionsLegacyParser<DocumentsMaterialsServiceListPublishedDocumentsData>
> => [
  createQueryKey(
    "documentsMaterialsServiceListPublishedDocuments",
    options,
    true,
  ),
];

export const documentsMaterialsServiceListPublishedDocumentsInfiniteOptions = (
  options: OptionsLegacyParser<DocumentsMaterialsServiceListPublishedDocumentsData>,
) => {
  return infiniteQueryOptions<
    DocumentsMaterialsServiceListPublishedDocumentsResponse,
    AxiosError<DocumentsMaterialsServiceListPublishedDocumentsError>,
    InfiniteData<DocumentsMaterialsServiceListPublishedDocumentsResponse>,
    QueryKey<
      OptionsLegacyParser<DocumentsMaterialsServiceListPublishedDocumentsData>
    >,
    | string
    | Pick<
        QueryKey<
          OptionsLegacyParser<DocumentsMaterialsServiceListPublishedDocumentsData>
        >[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<
            OptionsLegacyParser<DocumentsMaterialsServiceListPublishedDocumentsData>
          >[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await documentsMaterialsServiceListPublishedDocuments({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey:
        documentsMaterialsServiceListPublishedDocumentsInfiniteQueryKey(
          options,
        ),
    },
  );
};

export const documentsMaterialsServiceListPublishedDocumentTypesQueryKey = (
  options: OptionsLegacyParser<DocumentsMaterialsServiceListPublishedDocumentTypesData>,
) => [
  createQueryKey(
    "documentsMaterialsServiceListPublishedDocumentTypes",
    options,
  ),
];

export const documentsMaterialsServiceListPublishedDocumentTypesOptions = (
  options: OptionsLegacyParser<DocumentsMaterialsServiceListPublishedDocumentTypesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } =
        await documentsMaterialsServiceListPublishedDocumentTypes({
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        });
      return data;
    },
    queryKey:
      documentsMaterialsServiceListPublishedDocumentTypesQueryKey(options),
  });
};

export const documentsMaterialsServiceListPublishedDocumentTypesInfiniteQueryKey =
  (
    options: OptionsLegacyParser<DocumentsMaterialsServiceListPublishedDocumentTypesData>,
  ): QueryKey<
    OptionsLegacyParser<DocumentsMaterialsServiceListPublishedDocumentTypesData>
  > => [
    createQueryKey(
      "documentsMaterialsServiceListPublishedDocumentTypes",
      options,
      true,
    ),
  ];

export const documentsMaterialsServiceListPublishedDocumentTypesInfiniteOptions =
  (
    options: OptionsLegacyParser<DocumentsMaterialsServiceListPublishedDocumentTypesData>,
  ) => {
    return infiniteQueryOptions<
      DocumentsMaterialsServiceListPublishedDocumentTypesResponse,
      AxiosError<DocumentsMaterialsServiceListPublishedDocumentTypesError>,
      InfiniteData<DocumentsMaterialsServiceListPublishedDocumentTypesResponse>,
      QueryKey<
        OptionsLegacyParser<DocumentsMaterialsServiceListPublishedDocumentTypesData>
      >,
      | string
      | Pick<
          QueryKey<
            OptionsLegacyParser<DocumentsMaterialsServiceListPublishedDocumentTypesData>
          >[0],
          "body" | "headers" | "path" | "query"
        >
    >(
      // @ts-ignore
      {
        queryFn: async ({ pageParam, queryKey, signal }) => {
          // @ts-ignore
          const page: Pick<
            QueryKey<
              OptionsLegacyParser<DocumentsMaterialsServiceListPublishedDocumentTypesData>
            >[0],
            "body" | "headers" | "path" | "query"
          > =
            typeof pageParam === "object"
              ? pageParam
              : {
                  query: {
                    page: pageParam,
                  },
                };
          const params = createInfiniteParams(queryKey, page);
          const { data } =
            await documentsMaterialsServiceListPublishedDocumentTypes({
              ...options,
              ...params,
              signal,
              throwOnError: true,
            });
          return data;
        },
        queryKey:
          documentsMaterialsServiceListPublishedDocumentTypesInfiniteQueryKey(
            options,
          ),
      },
    );
  };
