// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-axios";
import type {
  UserServiceGetOtpByRequestIdData,
  UserServiceGetOtpByRequestIdError,
  UserServiceGetOtpByRequestIdResponse,
  UserServiceCancelAdminInvitationData,
  UserServiceCancelAdminInvitationError,
  UserServiceCancelAdminInvitationResponse,
  UserServiceInviteAdminData,
  UserServiceInviteAdminError,
  UserServiceInviteAdminResponse,
  UserServiceResendAdminInvitationData,
  UserServiceResendAdminInvitationError,
  UserServiceResendAdminInvitationResponse,
  UserServiceGenerateNewFiresbaseCustomTokenData,
  UserServiceGenerateNewFiresbaseCustomTokenError,
  UserServiceGenerateNewFiresbaseCustomTokenResponse,
  UserServiceCompleteProfileData,
  UserServiceCompleteProfileError,
  UserServiceCompleteProfileResponse,
  UserServiceActivateAdminUsersAccountData,
  UserServiceActivateAdminUsersAccountError,
  UserServiceActivateAdminUsersAccountResponse,
  UserServiceAuthenticateData,
  UserServiceAuthenticateError,
  UserServiceAuthenticateResponse,
  UserServiceRefreshAccessTokenData,
  UserServiceRefreshAccessTokenError,
  UserServiceRefreshAccessTokenResponse,
  UserServiceResetPasswordData,
  UserServiceResetPasswordError,
  UserServiceResetPasswordResponse,
  UserServiceSendResetPasswordEmailVerificationLinkData,
  UserServiceSendResetPasswordEmailVerificationLinkError,
  UserServiceSendResetPasswordEmailVerificationLinkResponse,
  UserServiceSendResetPasswordOtpData,
  UserServiceSendResetPasswordOtpError,
  UserServiceSendResetPasswordOtpResponse,
  UserServiceSendSignupEmailVerificationLinkData,
  UserServiceSendSignupEmailVerificationLinkError,
  UserServiceSendSignupEmailVerificationLinkResponse,
  UserServiceSendSignupOtpData,
  UserServiceSendSignupOtpError,
  UserServiceSendSignupOtpResponse,
  UserServiceSignupData,
  UserServiceSignupError,
  UserServiceSignupResponse,
  UserServiceVerifyOtpData,
  UserServiceVerifyOtpError,
  UserServiceVerifyOtpResponse,
  UserServiceVerifyEmailData,
  UserServiceVerifyEmailError,
  UserServiceVerifyEmailResponse,
  UserServiceUpdateUserData,
  UserServiceUpdateUserError,
  UserServiceUpdateUserResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * GetOtpByRequestID retrieves the OTP value for a given request ID.
 * Admin-only endpoint for testing and troubleshooting OTP delivery issues.
 */
export const userServiceGetOtpByRequestId = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<UserServiceGetOtpByRequestIdData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UserServiceGetOtpByRequestIdResponse,
    UserServiceGetOtpByRequestIdError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/user/{actor}/users/get-otp-by-request-id/{requestId}",
  });
};

/**
 * CancelAdminInvitation cancels a pending admin invitation and invalidates
 * all verification links. The invitation cannot be reactivated - a new
 * invitation must be sent if needed.
 */
export const userServiceCancelAdminInvitation = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    UserServiceCancelAdminInvitationData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    UserServiceCancelAdminInvitationResponse,
    UserServiceCancelAdminInvitationError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/user/{userId}/cancel-admin-invitation",
  });
};

/**
 * InviteAdmin sends an invitation email to create a new admin user with a
 * specific role. Invitation link expires after 6 minutes. Requires admin
 * privileges.
 */
export const userServiceInviteAdmin = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UserServiceInviteAdminData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UserServiceInviteAdminResponse,
    UserServiceInviteAdminError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/user/{userId}/invite-admin",
  });
};

/**
 * ResendAdminInvitation resends an invitation email to a pending admin user.
 * Generates a new verification link and resets account to pending status.
 */
export const userServiceResendAdminInvitation = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    UserServiceResendAdminInvitationData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).put<
    UserServiceResendAdminInvitationResponse,
    UserServiceResendAdminInvitationError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/admin/user/{userId}/resend-admin-invitation",
  });
};

/**
 * GenerateNewFiresbaseCustomToken creates a custom Firebase token for
 * server-side authentication flows.
 */
export const userServiceGenerateNewFiresbaseCustomToken = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    UserServiceGenerateNewFiresbaseCustomTokenData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    UserServiceGenerateNewFiresbaseCustomTokenResponse,
    UserServiceGenerateNewFiresbaseCustomTokenError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/auth/firebase/{userId}/users/token/generate",
  });
};

/**
 * CompleteProfile adds or updates additional profile information (name,
 * location, contact details). Cannot be used to change existing email or
 * phone number.
 */
export const userServiceCompleteProfile = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<UserServiceCompleteProfileData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    UserServiceCompleteProfileResponse,
    UserServiceCompleteProfileError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/client/users/{userId}/complete-profile",
  });
};

/**
 * ActivateAdminUsersAccount activates an admin account after email
 * verification. Completes user profile with name and password, then changes
 * status to activated.
 */
export const userServiceActivateAdminUsersAccount = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    UserServiceActivateAdminUsersAccountData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    UserServiceActivateAdminUsersAccountResponse,
    UserServiceActivateAdminUsersAccountError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/public/user/{userId}/activate-admin-account",
  });
};

/**
 * Authenticate verifies user credentials (email/password or phone/password)
 * and returns access/refresh tokens.
 */
export const userServiceAuthenticate = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UserServiceAuthenticateData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UserServiceAuthenticateResponse,
    UserServiceAuthenticateError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/public/users/authenticate",
  });
};

/**
 * RefreshAccessToken exchanges a valid refresh token for a new access token.
 */
export const userServiceRefreshAccessToken = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<UserServiceRefreshAccessTokenData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UserServiceRefreshAccessTokenResponse,
    UserServiceRefreshAccessTokenError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/public/users/refresh-access-token",
  });
};

export const userServiceResetPassword = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UserServiceResetPasswordData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UserServiceResetPasswordResponse,
    UserServiceResetPasswordError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/public/users/reset-password",
  });
};

export const userServiceSendResetPasswordEmailVerificationLink = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    UserServiceSendResetPasswordEmailVerificationLinkData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    UserServiceSendResetPasswordEmailVerificationLinkResponse,
    UserServiceSendResetPasswordEmailVerificationLinkError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/public/users/send-reset-password-email-verification-link",
  });
};

export const userServiceSendResetPasswordOtp = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    UserServiceSendResetPasswordOtpData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    UserServiceSendResetPasswordOtpResponse,
    UserServiceSendResetPasswordOtpError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/public/users/send-reset-password-otp",
  });
};

/**
 * SendSignupEmailVerificationLink sends an email verification link to confirm
 * email ownership. Link expires after 6 minutes and is rate limited to 20
 * requests per day.
 */
export const userServiceSendSignupEmailVerificationLink = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    UserServiceSendSignupEmailVerificationLinkData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    UserServiceSendSignupEmailVerificationLinkResponse,
    UserServiceSendSignupEmailVerificationLinkError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/public/users/send-signup-email-verification-link",
  });
};

/**
 * SendSignupOtp sends a one-time password via SMS to verify phone number
 * during signup. Rate limited to 20 requests per day per phone number.
 */
export const userServiceSendSignupOtp = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UserServiceSendSignupOtpData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UserServiceSendSignupOtpResponse,
    UserServiceSendSignupOtpError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/public/users/send-signup-otp",
  });
};

/**
 * Signup creates a new user account after verifying authentication factors
 * (email or SMS OTP). Returns access and refresh tokens upon successful
 * account creation.
 */
export const userServiceSignup = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UserServiceSignupData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UserServiceSignupResponse,
    UserServiceSignupError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/public/users/signup",
  });
};

/**
 * VerifyOtp validates a one-time password sent via SMS to confirm phone
 * number ownership.
 */
export const userServiceVerifyOtp = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UserServiceVerifyOtpData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UserServiceVerifyOtpResponse,
    UserServiceVerifyOtpError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/public/users/verify-otp",
  });
};

/**
 * VerifyEmail validates an email verification token and marks the email as
 * verified.
 */
export const userServiceVerifyEmail = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UserServiceVerifyEmailData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UserServiceVerifyEmailResponse,
    UserServiceVerifyEmailError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/public/users/{token}/verify-email-token",
  });
};

/**
 * UpdateUser updates user profile information.
 * Requires authentication and user ownership or admin privileges.
 */
export const userServiceUpdateUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UserServiceUpdateUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UserServiceUpdateUserResponse,
    UserServiceUpdateUserError,
    ThrowOnError
  >({
    ...options,
    url: "/v2/api/users/{user.userId}",
  });
};
