// This file is auto-generated by @hey-api/openapi-ts

export type protobufAny = {
  [key: string]: unknown;
};

export type rpcStatus = {
  code?: number;
  message?: string;
  details?: Array<protobufAny>;
};

/**
 * Request to activate admin users account.
 */
export type UserServiceActivateAdminUsersAccountBody = {
  password?: string;
  fullName?: string;
};

/**
 * CancelAdminInvitationRequest cancels a pending admin invitation.
 */
export type UserServiceCancelAdminInvitationBody = {
  email?: string;
  canceledBy?: string;
};

export type UserServiceCompleteProfileBody = {
  fullName?: string;
  email?: string;
  phoneNumber?: string;
  location?: string;
};

export type UserServiceGenerateNewFiresbaseCustomTokenBody = unknown;

/**
 * InviteAdminRequest sends an invitation to create a new admin user.
 */
export type UserServiceInviteAdminBody = {
  email?: string;
  role?: v2AdminRole;
  /**
   * name of the admin user who initiated the invitation
   */
  createdBy?: string;
};

/**
 * ResendAdminInvitationRequest resends an invitation to a pending admin user.
 */
export type UserServiceResendAdminInvitationBody = {
  email?: string;
  role?: v2AdminRole;
  resentBy?: string;
};

export type UserServiceUpdateUserBody = {
  user?: {
    fullName?: string;
    email?: string;
    photoUrl?: string;
    telephone?: string;
    country?: string;
    city?: string;
    address?: string;
    profession?: string;
    userAccountStatus?: v2UserAccountStatus;
    createdBy?: string;
    passwordRequestStatus?: v2PasswordRequestStatus;
    userRole?: v2UserRole;
    createdAt?: string;
    updatedAt?: string;
  };
};

/**
 * response after activating/notifying user about account created.
 */
export type v2ActivateAdminUsersAccountResponse = {
  message?: string;
};

export type v2AdditionalFactor = {
  factorType?: v2FactorType;
  factorHint?: string;
};

export type v2AdminRole =
  | "ADMIN_ROLE_UNSPECIFIED"
  | "ADMIN_ROLE_SUPER_ADMIN"
  | "ADMIN_ROLE_LIBRARY_ADMINISTRATOR"
  | "ADMIN_ROLE_DOCUMENTS_MANAGER"
  | "ADMIN_ROLE_DOCUMENTS_EDITOR"
  | "ADMIN_ROLE_DOCUMENTS_WRITER"
  | "ADMIN_ROLE_CUSTOMERS_ADMINISTRATOR"
  | "ADMIN_ROLE_ACCOUNTS_MANAGER";

export type v2AuthenticateRequest = {
  authFactors?: Array<v2AuthFactor>;
};

export type v2AuthenticateResponse = {
  loginComplete?: boolean;
  additionalFactor?: v2AdditionalFactor;
  tokens?: v2Tokens;
  userId?: string;
};

export type v2AuthFactor = {
  type?: v2FactorType;
  id?: string;
  secretValue?: string;
};

/**
 * CancelAdminInvitationResponse confirms the invitation was cancelled
 * successfully.
 */
export type v2CancelAdminInvitationResponse = {
  message?: string;
};

export type v2CompleteProfileResponse = {
  user?: v2User;
};

export type v2CustomNewFirebaseTokenResponse = {
  token?: string;
};

export type v2FactorType =
  | "FACTOR_TYPE_UNSPECIFIED"
  | "FACTOR_TYPE_EMAIL_PASSWORD"
  | "FACTOR_TYPE_SMS_OTP"
  | "FACTOR_TYPE_EMAIL_VERIFICATION"
  | "FACTOR_TYPE_PHONE_PASSWORD";

export type v2GetOtpByRequestIDResponse = {
  factorId?: string;
  factorType?: v2FactorType;
  secretValue?: string;
};

/**
 * InviteAdminResponse confirms the invitation was sent successfully.
 */
export type v2InviteAdminResponse = {
  message?: string;
};

/**
 * - PASSWORD_REQUEST_STATUS_UNSPECIFIED: No active request
 * - REQUESTED: Password reset requested
 * - COMPLETED: Password successfully changed
 * - EXPIRED: Reset link expired
 */
export type v2PasswordRequestStatus =
  | "PASSWORD_REQUEST_STATUS_UNSPECIFIED"
  | "REQUESTED"
  | "COMPLETED"
  | "EXPIRED";

export type v2RefreshAccessTokenRequest = {
  refreshToken?: string;
};

export type v2RefreshAccessTokenResponse = {
  accessToken?: string;
};

/**
 * ResendAdminInvitationResponse confirms the invitation was resent
 * successfully.
 */
export type v2ResendAdminInvitationResponse = {
  message?: string;
};

export type v2ResetPasswordRequest = {
  authFactor?: v2AuthFactor;
  phoneNumber?: string;
  email?: string;
  newPassword?: string;
};

export type v2ResetPasswordResponse = unknown;

export type v2SendResetPasswordEmailVerificationLinkRequest = {
  email?: string;
};

export type v2SendResetPasswordEmailVerificationLinkResponse = {
  message?: string;
};

export type v2SendResetPasswordOtpRequest = {
  phoneNumber?: string;
};

export type v2SendResetPasswordOtpResponse = {
  requestId?: string;
};

export type v2SendSignupEmailVerificationLinkRequest = {
  email?: string;
};

export type v2SendSignupEmailVerificationLinkResponse = {
  message?: string;
};

export type v2SendSignupOtpRequest = {
  phoneNumber?: string;
};

export type v2SendSignUpOtpResponse = {
  requestId?: string;
};

export type v2SignupRequest = {
  authFactor?: v2AuthFactor;
  profession?: string;
  password?: string;
  email?: string;
  phoneNumber?: string;
};

export type v2SignupResponse = {
  userId?: string;
  tokens?: v2Tokens;
};

export type v2Tokens = {
  accessToken?: string;
  refreshToken?: string;
};

export type v2UpdateUserResponse = {
  user?: v2User;
};

export type v2User = {
  userId?: string;
  fullName?: string;
  email?: string;
  photoUrl?: string;
  telephone?: string;
  country?: string;
  city?: string;
  address?: string;
  profession?: string;
  userAccountStatus?: v2UserAccountStatus;
  createdBy?: string;
  passwordRequestStatus?: v2PasswordRequestStatus;
  userRole?: v2UserRole;
  createdAt?: string;
  updatedAt?: string;
};

/**
 * - USER_ACCOUNT_STATUS_UNSPECIFIED: Default/unknown status
 * - ACTIVE: Account is active and usable
 * - SUSPENDED: Temporarily suspended
 * - DEACTIVATED: User deactivated their account
 * - BANNED: Permanently banned
 * - PENDING_VERIFICATION: Awaiting email/phone verification
 */
export type v2UserAccountStatus =
  | "USER_ACCOUNT_STATUS_UNSPECIFIED"
  | "ACTIVE"
  | "SUSPENDED"
  | "DEACTIVATED"
  | "BANNED"
  | "PENDING_VERIFICATION";

/**
 * - USER_ROLE_GUEST: Free tier with limited access
 * - USER_ROLE_STUDENT: Student subscription
 * - USER_ROLE_PROFESSIONAL: Professional subscription
 * - USER_ROLE_ORGANIZATION: Organization/enterprise subscription
 */
export type v2UserRole =
  | "USER_ROLE_UNSPECIFIED"
  | "USER_ROLE_GUEST"
  | "USER_ROLE_STUDENT"
  | "USER_ROLE_PROFESSIONAL"
  | "USER_ROLE_ORGANIZATION";

export type v2VerifyEmailResponse = {
  verified?: boolean;
  email?: string;
  id?: string;
};

export type v2VerifyOtpRequest = {
  authFactor?: v2AuthFactor;
};

export type v2VerifyOtpResponse = {
  valid?: boolean;
};

export type UserServiceGetOtpByRequestIdData = {
  path: {
    /**
     * Admin user ID making the request
     */
    actor: string;
    /**
     * OTP request ID to look up
     */
    requestId: string;
  };
};

export type UserServiceGetOtpByRequestIdResponse = v2GetOtpByRequestIDResponse;

export type UserServiceGetOtpByRequestIdError = rpcStatus;

export type UserServiceCancelAdminInvitationData = {
  body: UserServiceCancelAdminInvitationBody;
  path: {
    /**
     * ID of the admin user cancelling this invitation (for authorization)
     */
    userId: string;
  };
};

export type UserServiceCancelAdminInvitationResponse =
  v2CancelAdminInvitationResponse;

export type UserServiceCancelAdminInvitationError = rpcStatus;

export type UserServiceInviteAdminData = {
  body: UserServiceInviteAdminBody;
  path: {
    /**
     * documents_manager)
     *
     * ID of the admin user making this invitation request
     */
    userId: string;
  };
};

export type UserServiceInviteAdminResponse = v2InviteAdminResponse;

export type UserServiceInviteAdminError = rpcStatus;

export type UserServiceResendAdminInvitationData = {
  body: UserServiceResendAdminInvitationBody;
  path: {
    /**
     * ID of the admin user resending this invitation (for authorization)
     */
    userId: string;
  };
};

export type UserServiceResendAdminInvitationResponse =
  v2ResendAdminInvitationResponse;

export type UserServiceResendAdminInvitationError = rpcStatus;

export type UserServiceGenerateNewFiresbaseCustomTokenData = {
  body: UserServiceGenerateNewFiresbaseCustomTokenBody;
  path: {
    userId: string;
  };
};

export type UserServiceGenerateNewFiresbaseCustomTokenResponse =
  v2CustomNewFirebaseTokenResponse;

export type UserServiceGenerateNewFiresbaseCustomTokenError = rpcStatus;

export type UserServiceCompleteProfileData = {
  body: UserServiceCompleteProfileBody;
  path: {
    userId: string;
  };
};

export type UserServiceCompleteProfileResponse = v2CompleteProfileResponse;

export type UserServiceCompleteProfileError = rpcStatus;

export type UserServiceActivateAdminUsersAccountData = {
  body: UserServiceActivateAdminUsersAccountBody;
  path: {
    /**
     * user_id of the admin user to be activated
     */
    userId: string;
  };
};

export type UserServiceActivateAdminUsersAccountResponse =
  v2ActivateAdminUsersAccountResponse;

export type UserServiceActivateAdminUsersAccountError = rpcStatus;

export type UserServiceAuthenticateData = {
  body: v2AuthenticateRequest;
};

export type UserServiceAuthenticateResponse = v2AuthenticateResponse;

export type UserServiceAuthenticateError = rpcStatus;

export type UserServiceRefreshAccessTokenData = {
  body: v2RefreshAccessTokenRequest;
};

export type UserServiceRefreshAccessTokenResponse =
  v2RefreshAccessTokenResponse;

export type UserServiceRefreshAccessTokenError = rpcStatus;

export type UserServiceResetPasswordData = {
  body: v2ResetPasswordRequest;
};

export type UserServiceResetPasswordResponse = v2ResetPasswordResponse;

export type UserServiceResetPasswordError = rpcStatus;

export type UserServiceSendResetPasswordEmailVerificationLinkData = {
  body: v2SendResetPasswordEmailVerificationLinkRequest;
};

export type UserServiceSendResetPasswordEmailVerificationLinkResponse =
  v2SendResetPasswordEmailVerificationLinkResponse;

export type UserServiceSendResetPasswordEmailVerificationLinkError = rpcStatus;

export type UserServiceSendResetPasswordOtpData = {
  body: v2SendResetPasswordOtpRequest;
};

export type UserServiceSendResetPasswordOtpResponse =
  v2SendResetPasswordOtpResponse;

export type UserServiceSendResetPasswordOtpError = rpcStatus;

export type UserServiceSendSignupEmailVerificationLinkData = {
  body: v2SendSignupEmailVerificationLinkRequest;
};

export type UserServiceSendSignupEmailVerificationLinkResponse =
  v2SendSignupEmailVerificationLinkResponse;

export type UserServiceSendSignupEmailVerificationLinkError = rpcStatus;

export type UserServiceSendSignupOtpData = {
  body: v2SendSignupOtpRequest;
};

export type UserServiceSendSignupOtpResponse = v2SendSignUpOtpResponse;

export type UserServiceSendSignupOtpError = rpcStatus;

export type UserServiceSignupData = {
  body: v2SignupRequest;
};

export type UserServiceSignupResponse = v2SignupResponse;

export type UserServiceSignupError = rpcStatus;

export type UserServiceVerifyOtpData = {
  body: v2VerifyOtpRequest;
};

export type UserServiceVerifyOtpResponse = v2VerifyOtpResponse;

export type UserServiceVerifyOtpError = rpcStatus;

export type UserServiceVerifyEmailData = {
  path: {
    token: string;
  };
};

export type UserServiceVerifyEmailResponse = v2VerifyEmailResponse;

export type UserServiceVerifyEmailError = rpcStatus;

export type UserServiceUpdateUserData = {
  body: UserServiceUpdateUserBody;
  path: {
    /**
     * Unique user identifier
     */
    "user.userId": string;
  };
};

export type UserServiceUpdateUserResponse = v2UpdateUserResponse;

export type UserServiceUpdateUserError = rpcStatus;
